### ISSUE TITLE
Can't bulk import domains:  Unable to read rows: KeyError('ip_address')

### ISSUE THREAD

**Issue by fastlorenzo** [GhostManager/Ghostwriter#1]
When trying to import the domains using the provided template, I receive the following error:

` Unable to read rows: KeyError('ip_address') `

I'll dig in the code and make a PR if I can fix it

**Comment by fastlorenzo** [comment]
Another error exists, if you try to import domains that don't exist in the database yet, you get an error as well. 

I fixed both, will make a PR

**Comment by covertgeek** [comment]
This is resolved by PR #2.  Closing issue for now.
