### ISSUE TITLE
Domain Age Calculation Wrong

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#100]
How to reproduce:
1. log in as admin
2. go to: infrastructe - domains -add domain
Use the following paramters (whatever domain-name and registrar you like):
registration date: 06/23/2020
exipration date: 05/04/2021

Save.

Observed behavior: Domain description shows the age at "315 days days"
Expected behavior: Domain description shows the correct age.

**Comment by chrismaddalena** [comment]
Thanks for reporting this :) 

The model function returns the calculation with "days" added and the webpage was also adding "days" to the value. We have fixed it for the next release.

**Comment by er4z0r** [comment]
Thank you for the quick response, Chris, but that this not what I meant.
If you check the registration date (06/23/2020) and the date I posted this issue, you will realize that it is not 315 days old. 
The duplicate "days" was just an additional wrinkle.  Sorry for not stating it more clearly

**Comment by chrismaddalena** [comment]
I see what you mean, @er4z0r. Is the date on your server set to the current date?

This is the logic for that calculation:

```python
        if self.is_expired:
            time_delta = self.expiration - self.creation
        else:
            time_delta = date.today() - self.creation
        return "{} days".format(time_delta.days)
```

The `is_expired()`property on the domain is `True` or `False` based `date.today() > self.expiration` – i.e., if the domain's expiration date (May 4, 2021 for your example) is in the past.

If the domain is expired, Ghostwriter calculates the age based on how long you owned the domain (number of days between registration and expiration). The time delta between 06/23/2020 and 05/04/2021 is 315 days. Of course, the expiration date is in the future, so you should see 113 days (days between registration and today, October 14th).

**Comment by er4z0r** [comment]
> Is the date on your server set to the current date?

I am running this in the docker dev setup (localy.yml). 
The output below suggests to me, that the date in the container is indeed set correctly:

```bash
er4z0r@laptop-er4z0r:Ghostwriter/(master) $ docker exec -it ghostwriter_django_1 /bin/sh
/app # date
Thu Oct 15 08:33:44 UTC 2020

docker exec -it ghostwriter_queue_1 /bin/sh
/app # date
Thu Oct 15 08:38:37 UTC 2020

er4z0r@laptop-er4z0r:Ghostwriter/(master) $ docker exec -it ghostwriter_postgres_1 /bin/sh
# date
Thu Oct 15 08:38:51 UTC 2020

er4z0r@laptop-er4z0r:Ghostwriter/(master) $ docker exec -it ghostwriter_redis_1 /bin/sh
/data # date
Thu Oct 15 08:39:08 UTC 2020
               
```

**Comment by er4z0r** [comment]
Found it! This is one of those glorious 'gotta love dynamically typed languages' moments: The code you mentioned uses `is_expired`  like a field while it is actually a method. So the condition in the if-statement always evaluates to true which results in the first code-path always being taken. Once you change that to `is_expired()` the calculation works as expected.

**Comment by chrismaddalena** [comment]
That was the issue, a mis-applied decorator. We reworked this and it is now fixed.
