### ISSUE TITLE
"reporting_severity" does not exist

### ISSUE THREAD

**Issue by spankywetfish** [GhostManager/Ghostwriter#12]
When running the initial database setup, model population fails with the following...

```Starting ghostwriter_postgres_1 ... done
PostgreSQL is available
Loading /app/ghostwriter/reporting/fixtures/initial.json...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "reporting_severity" does not exist
LINE 1: UPDATE "reporting_severity" SET "severity" = 'Informational'...
               ^
```

This error cascades into rolodex and shepherd.

**Comment by covertgeek** [comment]
It appears that the initial database setup was not completed prior to inserting the data.  Performing a `docker-compose -f local.yml up -d` should create the database if it hasn't already been done.

Another option is to manually create the database.  For instance, on a local instance, the following will do it.

```
docker-compose -f local.yml run --rm django python manage.py migrate
```

If using production, just replace `local.yml` with `production.yml`.

**Comment by spankywetfish** [comment]
> It appears that the initial database setup was not completed prior to inserting the data. Performing a `docker-compose -f local.yml up -d` should create the database if it hasn't already been done.
> 
> Another option is to manually create the database. For instance, on a local instance, the following will do it.
> 
> ```
> docker-compose -f local.yml run --rm django python manage.py migrate
> ```
> 
> If using production, just replace `local.yml` with `production.yml`.

Thanks, no idea how i missed that step.

**Comment by covertgeek** [comment]
No worries.  Feel free to reopen the issue if it still persists.
