### ISSUE TITLE
'manage.py' were not copied to the /app path with local.yml

### ISSUE THREAD

**Issue by wishlog** [GhostManager/Ghostwriter#129]
I tried to follow the wiki to create db and try to create the super account with the manage.py script with below error:

```
$ docker-compose -f local.yml run --rm django python manage.py createsuperuser
Starting ghostwriter_postgres_1 ... done
Creating ghostwriter_django_run ... done
PostgreSQL is available
python: can't open file 'manage.py': [Errno 2] No such file or directory
```

It happens that the manage.py cannot be copied to the /app path:

```
$ docker-compose -f local.yml run --rm django ls -la
Starting ghostwriter_postgres_1 ... done
Creating ghostwriter_django_run ... done
PostgreSQL is available
total 4
drwxr-xr-x    3 root     root            60 Nov 27 07:48 .
drwxr-xr-x    1 root     root          4096 Nov 27 13:01 ..
drwxr-xr-x    3 root     root            60 Nov 27 07:48 ghostwriter
```

Any quickfix idea?

**Comment by wishlog** [comment]
I'm not sure if that's just me or anyone meet the same issue, it works after I add the folder manually:

Adding the folder with:
ADD . . 

in the ./compose/local/django/Dockerfile file after 
WORKDIR /app

**Comment by chrismaddalena** [comment]
I haven't seen that happen before, but have seen the container fail to install a library or experience some other general setup issues. Usually they are resolved after re-building the container. I've been toying with the idea of prebuilt container for releases to help avoid that.

Thanks for sharing your solution! I'll keep an eye on this to see if it becomes a common problem.
