### ISSUE TITLE
Setting User Password Admin Console

### ISSUE THREAD

**Issue by g1ldedm1n1on** [GhostManager/Ghostwriter#13]
I am having trouble finding how to create and pre-load users with passwords.  Logging in with the administrator account, I can create users but there is no password field or options. I can set Full Name, User Name, Email Address and the two advanced options.  Only way I have been able to find to create a user with specific password is to set DJANGO_ACCOUNT_ALLOW_REGISTRATION to true.

![Screen Shot 2019-08-06 at 9 56 18 AM](https://user-images.githubusercontent.com/5016447/62550847-8d4bb200-b830-11e9-8cd5-5550439d2469.png)

**Comment by covertgeek** [comment]
This was an oversight on my part.  A fix has been merged that modifies the admin interface to allow for setting the password.  Please sync the code and try again.

**Comment by g1ldedm1n1on** [comment]
Thank you! Validated merge fixed it.
