### ISSUE TITLE
[FR] support for evidence files in oplog

### ISSUE THREAD

**Issue by tbennett6421** [GhostManager/Ghostwriter#132]
I have a feature request. I love the oplog, but I was wondering if it would be possible to amend the oplog to support file uploads. 

for example, say I run the following commands to enumerate the network.
nmap -sC -sV -O -n -vv -T4 10.10.10.1-254 -p- -oA tcp-full-sweep

It would be awesome if the oplog entry could support adding multiple files. so that I could attack the tcp-full-sweep.xml,nmap,gnmap to the entry. Then anyone could view the results of that scan without trying to examine the output column, sometimes I run commands that dump stderr, stdout to separate files or I run a command that generates a file per host.

the nmap example is nice, because the output is difficult to work with in ghostwriter. Ideally if ghostwriter is able to act as a file repository this could be used to render evidence files for reporting or use the command to fill in the field for reproduction from the defender side in the findings window.

**Comment by andrewchiles** [comment]
Thanks @tbennett6421, this is something we'd like to support in 2021 more generally in a "tagging" feature for the oplog. Tagging would providing us the ability to generically tag a TTP, Objective, Finding, Evidence, etc in an oplog entry.

**Comment by chrismaddalena** [comment]
This issue is closed but tracked on the road map.

**Comment by chrismaddalena** [comment]
This will be released with v6.3.0 tomorrow 😄
