### ISSUE TITLE
[BUG]  HTML entity recursive replacement on oplog edit

### ISSUE THREAD

**Issue by tbennett6421** [GhostManager/Ghostwriter#133]
I noticed in the oplog that if a command includes an html entity, it gets encoded. if that entry is edited over and over again, the html entity is re-encoded multiple times

Here is an example
```bash
dnsrecon -d $rhost -t zonewalk  > dns-$domain.walk.txt
```

if this command is entered into the oplog `command` and then edited, `>` is replaced with `&gt;`. Editing this again replaces `&gt;` with `&amp;gt;` and each iterative edit will recursively update the html entity.

Such as like this.
```bash
dnsrecon -d $rhost -t zonewalk  &amp;amp;amp;amp;amp;gt; dns-$domain.walk.txt
```

Not sure what the intended behavior should be, perhaps using a textarea field or a `<pre>` tag? However I figured I should report it.

**Comment by andrewchiles** [comment]
Thanks @tbennett6421 for this report. I hadn't seen this bug before, but confirmed and we will will work on a fix as time allows!

**Comment by andrewchiles** [comment]
**Update**: This will be fixed in Master when the next GW release is pushed to GitHub. Current estimate is end of Q1 2021

**Comment by chrismaddalena** [comment]
This is resolved with the latest release: https://github.com/GhostManager/Ghostwriter/releases/tag/v2.1
