### ISSUE TITLE
Cannot import image into the report

### ISSUE THREAD

**Issue by NaveenNguyen** [GhostManager/Ghostwriter#139]
Hi,

I am not able to import the image into the report.

I created a client, added a project, added findings, and everything else is fine with the report. I can export the report successfully without the evidence.

But when I attach the evidence and try to export the report in docx. I'm getting the below error message:-

_**Great Failure
Encountered an error generating the document: no style with name `Caption`**_

I am using jpg & png format report only.

**Comment by andrewchiles** [comment]
I'd guess this is likely due to your report template, but @chrismaddalena can confirm. Check your template to make sure you've included all the required styles, including "Caption" and passes linting. 

- https://ghostwriter.wiki/features/reporting/report-templates/word-template-styles
- https://ghostwriter.wiki/features/reporting/report-templates/report-template-linting

**Comment by NaveenNguyen** [comment]
Can you please show an example for including "Caption" in the template?
Should I add it using the syntax "{{.caption }}"

**Comment by andrewchiles** [comment]
This is not something we've run into before, but think we have an answer. "Caption" should be a built-in style with Word. This style is applied whenever you insert an evidence file or use the `{{.caption}}` keyword. 

However, if that style has never been used in your template document then it may not actually exist in the file (thanks Microsoft). This is an oversight in the linting process, but we will add a check in a future release.

**In your template, try this:**

- Add a new line of text
- Highlight the line
- Apply the default "Caption" Style to the line
- Save the template
- Close Word
- Re-open the template
- Delete this line
- Save the template
- Re-upload the template to Ghostwriter 
- Generate your report

Please let us know if this fixes your issue and we'll get the linting changes pushed into the project!

**Comment by NaveenNguyen** [comment]
Hi, 

Thank you so much. The issue got fixed. It was simple, I just created a new style in the name 'caption' in my word template.

**Comment by chrismaddalena** [comment]
Thanks for bringing this up!

For the record, we added some additional template linting checks to look for the caption style and a few others. If they are missing from the template, Ghostwriter's linter will display a warning. If you use the template anyway, the reporting engine will make its own version of the style, which you can then edit to make adjustments.

Word's built-in styles are only added to your template's `styles.xml` when you use them. Once you have applied the style at least once, it will be part of the XML. All other unused "latent" and built-in styles only exist in the Word application. So, if you apply a style like `Caption` once, save the document (for good measure), and then undo the style, the `styles.xml` will contain the `Caption` style.

I also added some notes about this to the wiki. The linter warnings direct you there for this information.
