### ISSUE TITLE
Another Database Setup Error

### ISSUE THREAD

**Issue by Simon-Davies** [GhostManager/Ghostwriter#147]
After running: docker-compose -f local.yml run --rm django /seed_data

I get the below:

WARNING: Image for service django was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating ghostwriter_django_run ... done
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...

**Comment by envelope000** [comment]
I'm having the same issues. I've tried multiple installs, tried modifying the .postgress env files or leaving them as is, ensured all packages up to date, pip up to date, no other install errors. up -d command completes for production, and attempts to seed indicate postgresql is not running. Examining the logs for the postgres container, I see user does not exist errors for the user indicated in the env file, whether postgres or custom. Upon attempts inside the container to directly add the user via createuser, I'm getting errors that role 'postgres' does not exist.

**Comment by chrismaddalena** [comment]
@Simon-Davies Check-out my response to your other issues, #146.

Until everything has been built and migrated, you'll be unable to use PostgreSQL and encounter a lot of problems.

@envelope000 The issue with `crytopgraphy` is related to that library being a dependency of Django. You want the latest version, but the very latest release switched-up something to start requiring Rust and `cargo` be installed. This is included in the next release, but if you want to fix this right now you can add these lines to the `Dockerfile` file:

```docker
    # Rust and Cargo required by the ``cryptography`` Python package
    && apk add rust \
    && apk add cargo
```

Add those lines to the end of the `RUN apk update\` block.

**Comment by Kaicastledine** [comment]
Try checking the logs for Postgres:

docker-compose -f local.yml logs postgres  

You might find if you have changed the password for PostGres previously and have been wiping images/containers that you need to wipe volumes as well.

This will remove all volumes - Caution if you have any to keep
 
docker volume rm $(docker volume ls -q)
