### ISSUE TITLE
Bug: Comma in client name produces error

### ISSUE THREAD

**Issue by coffeegist** [GhostManager/Ghostwriter#149]
## Issue 
If a client has a comma in the name (potentially other characters as well), the report generation succeeds, but the report is unable to be downloaded. 

## Reproduction 
Using the sample client name `SpecterOps, Inc.`, create a client, project, and report using the template provided. 
Add a finding or two to the report.
Generate the report. 

## Expected behavior
A report is generated and immediately served/downloaded 

## Actual behavior 
User receives a `ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION` error due to the comma in the filename being served.

**Comment by chrismaddalena** [comment]
Ah! Good catch. That's an easy fix, and it's done. We could scrub the filename (we will), but wrapping the filename in quotes resolves this. I just did that and tested it successfully.

Thanks for letting us know! It'll be fixed in the next release (should be within a week).

**Comment by chrismaddalena** [comment]
This is resolved with the latest release: https://github.com/GhostManager/Ghostwriter/releases/tag/v2.1
