### ISSUE TITLE
Enhancement: vulnerability total counter

### ISSUE THREAD

**Issue by federicodotta** [GhostManager/Ghostwriter#161]
Hi,

it would be great to have a field in the finding with the "total position" among all the vulnerabilities.

To explain me better, we give to each vulnerability an unique identifier (like V01, V02, etc.), ordering the issues from most critical to less critical.

At the moment each vulnerability in a GhostWriter report contains two identifiers: "id" and "position":

- "id" is generated when a vulnerability is added to a report, but it is based on when the issue has been added to the report and not on the position of the issue in the report
- "position" is relative only to the severity of the issue

When all the issues are inserted in the report using for example a for loop, it is possible to generate this unique identifier using Jinja variables, Jinja "count" filter or Jinja "loop.index", but it is less comfortable outside loops.

Is it possible to add a new field to the vulnerabilities that contain the total position of the vulnerabilities in the report, as in the following picture?

![image](https://user-images.githubusercontent.com/1651767/117288363-b49f3b00-ae6b-11eb-8b97-510fd220c2d0.png)

Thank you a lot for your great work!
Federico

**Comment by federicodotta** [comment]
Hi @chrismaddalena, 

Yes, it is perfect! Thank you!

And thank you for this tool you freely made available to the community. It is simply great!

Federico

**Comment by chrismaddalena** [comment]
No problem, @federicodotta. This is now live in v2.2.1.
