### ISSUE TITLE
Enhancement: adding a tag to display evidence(s) from the docx/pptx templates

### ISSUE THREAD

**Issue by federicodotta** [GhostManager/Ghostwriter#162]
Hi,

first, thank you again for your great tool! 

It would be great to have a tag that can be inserted in the report docx/pptx template as a placeholder for evidences.

At the moment, if I haven't missed something, evidences can be put in the report only by editing one of the sections of  "Update finding page" in from GhostWriter GUI, using a specific tag generated from the friendly name of the evidence.

In some reports, we put all the evidences together in a dedicated section and consequently, if possible, it would be great to have a tag for the docx/pptx that is replaced by all the evidences (something like finding.evidence_rt ) or even better a tag that prints a single evidence, that can be used by looping in the finding.evidence array.

Thank you a lot for your great job!
Federico

**Comment by chrismaddalena** [comment]
We included this in v4.1 so I'm marking this as closed 😄 

You can now upload evidence to a report, not just findings, and reference them in multiple sections.
