### ISSUE TITLE
Ghostwriter on Portainer

### ISSUE THREAD

**Issue by Stasky745** [GhostManager/Ghostwriter#169]
I'm trying to install Ghostwriter on a server I'm building right now. This server is an Ubuntu 20.10 with docker and contains Portainer and some other containers.

Is there somewhere I can get a way to install it through Portainer so I can easily manage it?

If not, port 8000 is in use right now. I've changed local.yml to contain 8001:8001 instead of 8000:8000, but when trying to access http://<ip>:8001/admin I get a `not found` error. What should I do to be able to install Ghostwriter in this docker?

**Comment by jpredo** [comment]
At  a quick glance, the port mapping (8000:8000), maps an external port to an internal port on the container. Changing both without changing fundamental code within the application will break things.

You should change it to `8001:8000`
