### ISSUE TITLE
Unable to create users

### ISSUE THREAD

**Issue by dbuentello** [GhostManager/Ghostwriter#17]
## Users created using the admin panel are unable to login. 

1. For example, the user (crobin) was created via the admin panel. 
<img width="1666" alt="new_user" src="https://user-images.githubusercontent.com/8379733/63207064-c6ccba80-c085-11e9-96f0-cfff9e21d880.png">

2. After logging out (and using a private browser) I receive an error when logging in with the new user.
<img width="676" alt="new_user_login_fail" src="https://user-images.githubusercontent.com/8379733/63207067-ca604180-c085-11e9-8855-aadcf07d6860.png">

**The workaround is to enable signups in the settings file.**

**Comment by dbuentello** [comment]
The non-hashed password is odd. 

Looking at the admin page code, this commit (7506a1059cbe9a61d337ff7330e7a8488be1dd4e) modifies `ghostwriter/users/admin.py` but doesn't show up in the file's history https://github.com/GhostManager/Ghostwriter/commits/master/ghostwriter/users/admin.py

**Comment by covertgeek** [comment]
This has been resolved by #18.   Please let us know if this continues to be an issue.
