### ISSUE TITLE
Enhancement: Domain association on IP address level

### ISSUE THREAD

**Issue by fastlorenzo** [GhostManager/Ghostwriter#173]
Within a project, under infrastructure, it should be possible to associate a domain to an IP address and not to a full server.
The use case would be when you have a server with multiple IP addresses, you want to track exactly to which IP the domain name is pointing to, not just the server.

Additionally, it is not possible to have multiple IP addresses assigned to a VPS. There should be a possibility to add them, as it is done with static servers.

Maybe reworking the internal storage of servers, and merging `transientserver` with `staticserver` models would simplify it.
You could then have a separate model to keep track of IP addresses and link them to the correct server.

The server model would have a field used to identify if the server is `static` or `vps`.

**Comment by chrismaddalena** [comment]
@fastlorenzo I think this flew under my radar when I was super busy last year. This is a really good point, and I'm sorry I missed it until now.

I agree that the whole system needs to be overhauled. Checking out a server or domain is straight forward and I like the workflow, but adding in cloud assets and then associating servers, domains, and IP addresses is not good.

i.e., Tracking individual bits of infrastructure still works well, but trying to link them to each other to represent their relationships and how they were used gets complicated and messy.

It's high on my list to refactor this. I'm open to suggestions like yours above.

**Comment by fastlorenzo** [comment]
no issues, everyone is pretty busy 😄 

I think the solution I gave in the initial post would be the easiest: keeping 1 model for servers, and 1 model for IP address. Then having a specific "tag" on the server that states if this is bare metal or cloud could be an option.
This would simplify development and maintenance.

You could then link IP addresses with servers, as well as domains/subdomains with IP addresses.
