### ISSUE TITLE
Change default font family in Finding Library

### ISSUE THREAD

**Issue by ta1c0** [GhostManager/Ghostwriter#180]
Hello,

I would like to change the font family for some findings to be Calibri (Body).
Is it possible?

Thank you

**Comment by chrismaddalena** [comment]
Yes, you can select a font family in the format menu while editing a finding.

**Comment by ta1c0** [comment]
Hey,

There are indeed some other fonts there, but Calibri (Body) isn't one of them.
![image](https://user-images.githubusercontent.com/86191609/129166057-067f2d19-1fd6-4c3e-bb3b-4480a524ceb4.png)

**Comment by ta1c0** [comment]
Hey chrismaddalena,

Can you please advise me what can I do to add the required font to the fonts list?

**Comment by chrismaddalena** [comment]
@ta1c0 Sorry I missed your question. There is a way to add custom fonts to the WYSIWYG. That is described here:

https://www.tiny.cloud/blog/tinymce-custom-font-family/

Assuming it's a built-in font that doesn't need to be imported, the easiest option is editing the _config.js_ file under _ghostwriter/static/js/tinymce/_. Go to line 26 and add `font_formats` to `default_config`. As described on that page, you'd add this to get started:

```
font_formats: "Andale Mono=andale mono,times; Arial=arial,helvetica,sans-serif; Arial Black=arial black,avant garde; Book Antiqua=book antiqua,palatino; Comic Sans MS=comic sans ms,sans-serif; Courier New=courier new,courier; Georgia=georgia,palatino; Helvetica=helvetica; Impact=impact,chicago; Symbol=symbol; Tahoma=tahoma,arial,helvetica,sans-serif; Terminal=terminal,monaco; Times New Roman=times new roman,times; Trebuchet MS=trebuchet ms,geneva; Verdana=verdana,geneva; Webdings=webdings; Wingdings=wingdings,zapf dingbats",
```

Copy that line, add a comma to the end of line 140, hit Enter to make a new line, and paste that `font_formats` config. Save the file and refresh Ghostwriter. Hold SHIFT when you refresh to convince your browser to reload the TinyMCE config and not use its cache.

You can make sure it is working by doing something like deleting the last few fonts, like `ebdings=webdings; Wingdings=wingdings,zapf dingbats`. Delete those, save the file, refresh the webpage, and check Format > Fonts. Webdings, Wingdings, Zaof, and Dingbats should be gone from the bottom of the list.

If you wanted to add Calibri, you'd tack on `Calibiri=calibri;` to the list. The first bit is the name you'll see in the menu. TinyMCE doesn't sort that list, so if you wanted Calibri to appear alphabetically you'd want to insert it before Comic Sans, like so:

`...; Book Antiqua=book antiqua,palatino; Calibiri=calibri; Comic Sans ...`

Going forward, I'll see about including `font_formats` in the config so it's easier to customize. There are a few fonts in there we could probably remove to make the list easier to navigate for reporting, like Webdings and Comic Sans.

Hope that helps.
