### ISSUE TITLE
Image evidence not displaying correctly in exported report

### ISSUE THREAD

**Issue by nmrdyer** [GhostManager/Ghostwriter#187]
Hi,
I have encountered an issue where the images I have uploaded as evidence are not submitted to the document correctly. When viewing the exported Word report, the image is partially added. Image attached.

![GW-Image Issue](https://user-images.githubusercontent.com/15686487/139050853-800edee8-0d01-4b39-943b-8c4de41d7b51.png)

Any help in troubleshooting would be appreciated. Thanks

**Comment by chrismaddalena** [comment]
@nmrdyer, Does the image look complete when you view it in Ghostwriter?

Sometimes images appear incomplete or missing in Word, but it's just a hiccup with the rendering. If you click crop or try to resize the image it often appears properly. Assuming it appears correct in the web interface, does it remain like this if you try moving the image or cropping it?

**Comment by nmrdyer** [comment]
Hi, 
I found the issue in the end, sorry I should have updated and closed theis issue. 
The problem was with the Word document. To fix, I had to change the "Line Spacing" option in "Paragraph" . It was set to "Exactly" which was causing the problem. Changing that fixed the issue and the images reder as they should now.

**Comment by chrismaddalena** [comment]
@nmrdyer Very interesting. Thanks for letting me know! I keep thinking I need to build a little troubleshooting FAQ for determining if something might be a problem with Ghostwriter vs. Word. This would be a good one to document.
