### ISSUE TITLE
Idea : API for finding management in reports

### ISSUE THREAD

**Issue by Gimpy42** [GhostManager/Ghostwriter#192]
It would be great if we could search the finding template library and add the wanted template to an existing report using an api.
This could allow us to run extension that would add existing finding to a report based on tool results automatically.

**Comment by chrismaddalena** [comment]
@Gimpy42 The API will be available very soon! We are developing a GraphQL API with Hasura. It's actually well on its way to being ready for testing, but we pressed pause on it to review the codebase and make sure everything was ready for it.

For context, I wrote about that here: https://posts.specterops.io/ghostwriter-looking-back-at-2021-6b580acabb7e

I am currently weighing the option of adding in some sort of feature flag for the API so we can make it available to use without waiting for it to be 100% complete. I am expecting to have it available, at least for testing and feedback, this quarter. Implementing a feature flag might take as long as finishing the API, so you might just see it roll out as a beta release.

With GraphQL, you'll have access to pretty much every part of Ghostwriter. It'll look like you're sending data to Ghostwriter, but Nginx will proxy your GraphQL queries to Hasura, which connects directly to the backend PostgreSQL database. Unlike REST API endpoints that always return specific information, you tell GraphQL exactly what you want via some simple JSON.

If you wanted to write a script that searches your finding library for keywords and returns just the title and ID, you could do that. If you wanted to then be able to select one of the results and have Ghostwriter add it to a report, you could do that.

I want the API to enable all kinds of middleware/extensions. For example, we like that Ghostwriter can send Slack notifications, but some people would rather use MatterMost or Teams. Maintaining the ability for Ghostwriter to talk to every possible domain registrar, monitoring API, cloud service, chat app, etc. is not feasible. (I am, after all, just one person.) The API will empower anyone to create scripts or full-on integrations for Ghostwriter. Even better, if they break, you can just not use them, and fixing them wouldn't require a release and deployment of a new version of Ghostwriter.

I'm also toying with the idea of creating some sort of plugin framework. Drop your script into a folder and make it available as a scheduled task or hook for a scheduled task. That would be good for sending notifications to email or chat clients and other things.

**Comment by Gimpy42** [comment]
Nice, that is wonderful. Every time we identify a need you guy seems to be already working on it.
I am eager to test this out when it goes live.

**Comment by chrismaddalena** [comment]
I'm closing this since the GraphQL API seems to have met the need. Of course, the API is still new and can be enhanced to make use cases like this easier. Let me know if the API doesn't fully address this need.

Note that there is a minor bug (of a sort) documented in #226 that affects this particular situation. That will be resolved in an upcoming hotfix, but a temporary solution is also in that thread.
