### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by dante-asriel-price** [GhostManager/Ghostwriter#204]
I'm following the wiki instructions to try to install Ghostwriter
After copying the envs_templates into a .envs directory and running the docker-compose -f local.yml up -d command I get this error:
Building postgres
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'postgres' failed to build : Build failed

I have searched through the .yml and .py scripts in the directories but cannot find the --iidfile flag in anything
I have also ran docker build --help, but hasn't helped.

**Comment by chrismaddalena** [comment]
Hey @dante-asriel-price – an error like that usually means you have an older version of Docker installed. Ghostwriter uses one of the latest Alpine Linux images that requires Docker v20+.

If you check Docker and docker-compose, do you have v20 and v2.2.x?

```
$ docker -v
Docker version 20.10.12, build e91ed57
$ docker-compose -v
Docker Compose version v2.2.3
```

**Comment by dante-asriel-price** [comment]
Okay, that actually answers that question. where I'm installing it has
Docker version 1.13.1, build 7d71120/1.13.1
docker-compose version 1.29.2, build 5becea4c

This server is already running a docker container so I'm going to move it to another server and do it there. 
Thank you so much

**Comment by chrismaddalena** [comment]
Glad that helped! I'll close this for now, but feel free to re-open this if that doesn't solve the issue.
