### ISSUE TITLE
Evidence & Finding Content not rendering in report

### ISSUE THREAD

**Issue by sanitycheck** [GhostManager/Ghostwriter#205]
First of thank you for all the great work that has been done on this project! I've been using Ghostwriter for the past couple years freelance work and it has been truly fantastic. Recently I took on a new role as an Offensive Security Team Lead at an organization that has never heard of an automated reporting solution. I'm trying to integrate the latest release into our workflow but I'm having some issues with getting evidence and finding content to render properly in the report/template. I have the following template for my findings

![image](https://user-images.githubusercontent.com/22825354/160148553-6748dafd-a102-4dcb-9adc-75649cf79eeb.png)

However, when I try to render finding content into the report the html code is included along with it. On top of this I cannot seem to get evidence/images to render in the report either (See "{{.cors}}"). 
![image](https://user-images.githubusercontent.com/22825354/160149911-c7f6f0c1-fc20-4429-9f95-abba5d900c56.png)
I am using '@' syntax to format these into WYSIWYG editor so I don't know what could be causing the issue. Any assistance in resolving these issues would be greatly appreciated!

**Comment by chrismaddalena** [comment]
@sanitycheck Hey! Glad you have found Ghostwriter helpful!

This should be a simple fix. You have `{{ finding.description }}` in your screenshot. That dumps the plaintext from the database directly into the document without any parsing–i.e., the raw HTML.

To get the parsed rich text version (with the HTML converted to OpenXML for Word and your evidence inserted), reference the `RichText` object version like so:

`{{ finding.description_rt }}`

Updating your template to include `_rt` at the end of your finding sections should take care of this. There is more info available here:

https://www.ghostwriter.wiki/features/reporting/report-templates/word-template-variables#findings-attributes-html-and-rich-text-attributes

Hope that helps!

**Comment by sanitycheck** [comment]
Hey @chrismaddalena sorry for the late reply on this. It had been such a long time since I had to recreate a template I completely forgot that Ghostwriter created richtext objects from the format. append `_rt` to the objects worked like a charm! Thanks so much for your help!
