### ISSUE TITLE
Enhancement: import issues in report

### ISSUE THREAD

**Issue by federicodotta** [GhostManager/Ghostwriter#212]
Hi!

Your great tool allows to import bulk template issues in the administration console.

It would be great to be able to import also issues in a specific report in the same way. This way, we can code modules for common tools (like Burp Suite) and for our internal tools that produce output in the GhostWriter format and import them directly in a specific report. Maybe the same code that imports the template can be used for the purpose.

What do you think about it?

Thank you for your great tool and for your support.

Federico

**Comment by chrismaddalena** [comment]
Hey @federicodotta,

Do you mean you want to be able to parse issues flagged by Burp Suite (as an example) and then add them as new findings for a specific report?

If so, that could be done now with the GraphQL API. You could convert the issues to JSON and then insert them into a report as new findings.

I can also look into adding such an import to the user interface.

**Comment by federicodotta** [comment]
Hi @chrismaddalena,

Sorry, I miss that feature via GraphQL. It is more than enough! Great!

Thank you for your support and for your great tool! I close the issue!

Federico

**Comment by chrismaddalena** [comment]
No problem, @federicodotta! I hope the API helps. If you develop a way to take issues from an external tool and push them to Ghostwriter, I'd love to hear about it.

**Comment by federicodotta** [comment]
Hi @chrismaddalena,

Sure! At the moment we are using GraphQL API of GhostWriter in two different ways:

1. First a collection of scripts, tools and templates to  allow our pentester to automatically generate final report using GhostWriter from the MD notes of the assessment
2. Secondly, we are integrating GhostWriter into our internal scanning tools, to push the found issues directly to the final GhostWriter report

GhostWriter is in our opinion one of the best tools for the report generation because it allows to greatly customize the Word model of the report (and it is free! Thank you!). With a set of tool to generate the report directly from the notes and a good set of issue templates it can speed up the reporting phase of the assessment a lot, minimizing the required effort directly on the Word document.

When we will finish this integration, if you are interested we can definitely share our collection of scripts and tools.

Federico

**Comment by chrismaddalena** [comment]
@federicodotta I love to hear that! I'm glad Ghostwriter helps you and your team. Thank you for the kind words 😄 

I absolutely want to hear more whenever you get it to the stage where you can share more with me. This is exactly what I hoped people would do with the GraphQL API.
