### ISSUE TITLE
Error in DNS domain health status update. 

### ISSUE THREAD

**Issue by dmaynor** [GhostManager/Ghostwriter#22]
Error: 'NoneType' object has no attribute 'split' : Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 377, in worker res = f(*task['args'], **task['kwargs']) File "/app/ghostwriter/shepherd/tasks.py", line 220, in check_domains lab_results = domain_review.check_domain_status() File "/app/ghostwriter/modules/review.py", line 482, in check_domain_status 'timestamp': address['last_resolved']. AttributeError: 'NoneType' object has no attribute 'split'

Task logs:
Id:
aec500e4fe1c433e909495f9e04d31c3
Name:
mobile-november-item-hotel
Func:
ghostwriter.shepherd.tasks.check_domains
Hook:
ghostwriter.shepherd.tasks.send_slack_complete_msg
Args:
Kwargs:
{}
Result:
'NoneType' object has no attribute 'split' : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 377, in worker
res = f(*task['args'], **task['kwargs'])
File "/app/ghostwriter/shepherd/tasks.py", line 220, in check_domains
lab_results = domain_review.check_domain_status()
File "/app/ghostwriter/modules/review.py", line 482, in check_domain_status
'timestamp': address['last_resolved'].
AttributeError: 'NoneType' object has no attribute 'split'
Group:
Domain Updates
Started:
Aug. 27, 2019, 6:11 p.m.
Stopped:
Aug. 27, 2019, 8:45 p.m.
Success:
False

**Comment by chrismaddalena** [comment]
I missed this a very long time (obviously). This was fixed a while back, and we've recently rewritten that bit of Ghostwriter. This should no longer be an issue.
