### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by MoJo1760** [GhostManager/Ghostwriter#220]
**Describe the bug**
Updated documentation on ghostwriter.wiki is incorrect for installation

**To Reproduce**

1. git clone https://github.com/GhostManager/Ghostwriter.git
2. cd Ghostwriter
3. ./ghotstwriter-cli-[mac||linux] install prod

**Expected Behavior**
Installation should commence

**Additional context**
The documentation appears to be correct for branch release-v3.0.0, however branch master is the default for git clone.

**Comment by chrismaddalena** [comment]
Thanks for taking the time to open an issue about this! This was just the result of the wiki going live a little faster than the code. The wiki updates went live while workflows for running for the merge of the `release-v3.0.0` branch. I had to step away for a little while, so there was some time when the wiki was live with the new installation guide and the code was waiting for me to confirm the merge. Everything is merged now 😃
