### ISSUE TITLE
Error on install - Django - too many open files

### ISSUE THREAD

**Issue by glennatlayla** [GhostManager/Ghostwriter#225]
**Describe the bug**
I'm trying a fresh install of GhostWriter on an Azure VM with a Ubuntu 20.04 image. I modified two lines in production.yml and hardcoded the ports because the install complained about the way the port statements were formatted: 

_(The Compose file './production.yml' is invalid because:
services.postgres.ports is invalid: Invalid port ""5432":5432", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.graphql_engine.ports is invalid: Invalid port ""8080":8080", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
[-] Error from `docker-compose`: exit status 1
2022/06/24 17:15:59 Error trying to build with production.yml: exit status 1)_

That seemed to fix the problem and the installation proceeded until I got the following error after the message: "[+] Waiting for Django application startup to complete..."

_022/06/23 12:24:42 Failed to get container list: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?limit=0": dial unix /var/run/docker.sock: socket: too many open files_

**To Reproduce**
I can delete the GhostWriter directory, run another git clone command, re-execute the _./ghostwriter-cli-linux install_ command and get the same error 

**Expected Behavior**
I'm not a developer and don't really know how to do anything but follow directions like this and google for error messages. I was crossing my fingers hoping it would work :)

**Screenshots**
See installation log file below.

**Server Specs:**
 - OS: 
 _

> gjohnson@ghost:~$ hostnamectl
>    Static hostname: ghost
>          Icon name: computer-vm
>            Chassis: vm
>         Machine ID: 14b9af0034e8470ab0e59ba9805a77c8
>            Boot ID: f75eebfa37974762a75799c28b42d0a2
>     Virtualization: microsoft
>   Operating System: Ubuntu 20.04.4 LTS
>             Kernel: Linux 5.13.0-1031-azure
>       Architecture: x86-64

_

 - Docker:

> gjohnson@ghost:~$ docker --version
> Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
> gjohnson@ghost:~$ docker-compose -v
> docker-compose version 1.25.0, build unknown

 - Ghostwriter [e.g., 2.2.3 or whatever is printed at the bottom of the left-hand sidebar]

> gjohnson@ghost:~/Projects/Ghostwriter$ more VERSION
> 3.0.0
> 22 June 2022

**Additional context**

[production.yml.txt](https://github.com/GhostManager/Ghostwriter/files/8978721/production.yml.txt)
[ghostwriter-install-log-2.txt](https://github.com/GhostManager/Ghostwriter/files/8978864/ghostwriter-install-log-2.txt)

**Comment by chrismaddalena** [comment]
Hey @glennatlayla, please revert the changes you made to the YAML and then upgrade Docker and docker-compose. You'll need at least v1.26.0 of docker-compose, but I recommend upgrading to v1.29.2 at a minimum.

Versions <1.26.0 won't be able to parse the DotEnv file properly.

**Comment by glennatlayla** [comment]
Thank you! Works like a champ.
