### ISSUE TITLE
GraphQL unable to get report using query

### ISSUE THREAD

**Issue by CapAlex94** [GhostManager/Ghostwriter#226]
Hi, I'm trying to get the report list using the dedicated GraphQL API. Unfortunately, the query does not appear to work when used within a Python script. I have run some tests using the Hasura console and the query works as expected.

I am currently trying to implement the following query:

`query MyQuery {
  report(where: {user: {}}) {
    id
    title
    project {
      codename
    }
  }
}`

Also, this query appears to work only with an admin user or maybe a manager user but not with a normal user.

At the moment, I am trying to implement a GhostWriter module to import issues from external tools and I need to get a list of reports to allow the user to choose a report to import vulnerabilities into.

Thanks for the support and the great tool!

**Comment by chrismaddalena** [comment]
Hi @CapAlex94,

That use of the GraphQL API sounds cool! I'd love to hear more about it if you want to share it when you're finished.

If the query works as an admin user, the query should be good. It sounds like your account with the `user` role does not have access to the reports you're expecting to see. Check out this page describing the role-based access controls:

https://www.ghostwriter.wiki/features/graphql-api/authorization

The short version is a user must be assigned to the project or invited to access the project (or associated client) to access any project data. For example, let's say you have projects A, B, and C, each with a report. By default, an account with the `user` role can't see any of those clients, the projects, or the reports. Their queries would return empty lists. If you add a project assignment for the user to Project A, the user would then be able to query Project A, the client attached to Project A, and Project A's reports and other data.

For now, RBAC only applies to the API, but we intend to expand it to the web UI. The benefit is you can use Ghostwriter and be compliant with requirements for ISO 27001 and similar certifications.

Suppose you don't want to limit access to client data; you can grant users the `manager` role. That disables RBAC by giving everyone the same access they have in the web UI today.

Let me know if you have questions.

**Comment by CapAlex94** [comment]
Thanks for the clarification, but i think the problem is different.

Using the django app an operator with user role can create clients, projects and reports and it is marked as owner of the reports.

![1](https://user-images.githubusercontent.com/622099/175822748-cfd8a1ed-5126-420e-8494-c297da4ac7d5.PNG)

![2](https://user-images.githubusercontent.com/622099/175822754-b16cf7e2-1c77-4cfd-b79e-ce718488cf66.PNG)

Since the operator with user role can create a report why he can't access to his own report using the API?

![3](https://user-images.githubusercontent.com/622099/175822996-1bd92f65-c827-408e-a0dc-d074c2b09e06.PNG)

![4](https://user-images.githubusercontent.com/622099/175823001-e0c3623b-bd14-48fc-ae1b-b3f71860ef14.PNG)

**Comment by CapAlex94** [comment]
Thank you for the clarification. 
But now I have another problem with the mutation "insert_reportedFinding".

If i try to execute the following mutation:

`mutation MyMutation {
  insert_reportedFinding(objects: {affectedEntities: "", cvss_score: 0.0, cvss_vector: "", description: "", findingGuidance: "", findingTypeId: 2, hostDetectionTechniques: "", impact: "", mitigation: "", networkDetectionTechniques: "", position: 10, references: "", replication_steps: "", reportId: 2, severityId:1, title: "",complete:false}) {
    returning {
      affectedEntities
    }
  }
}
`

I get the followin error message:

`{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_reportedFinding.args.objects[0].complete",
        "code": "validation-failed"
      },
      "message": "field \"complete\" not found in type: 'reportedFinding_insert_input'"
    }
  ]
}`

but if I remove the field 'complete' from the mutation I get another error:

`{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_reportedFinding.args.objects",
        "code": "constraint-violation"
      },
      "message": "Not-NULL violation. null value in column \"complete\" violates not-null constraint"
    }
  ]
}`

At the moment i'm performing the query using a basic user but if i use an admin the field "complete" is required and the value "false" is accepted correctly and the issue is inserted inside the report.

Analyzing the "reporting_finding" table, the "complete" field is not defined. Is it therefore possible that there is an error in the definition of the mutation?

**Comment by chrismaddalena** [comment]
That's a bug of a sort. When inserting a finding, I wanted to limit how many fields you'd have to provide and `complete` would always be set to `false`, so I removed it. I don't know if being able to create a finding that is immediately marked as complete would be useful, but enabling the field is an easy fix. The "bug" is the field can't be null and has no default value. The default value is set via Django, but Postgres needs to be aware of it.

The solution is:

* Enable the `complete` field; or
* Configure a default for Postgres on that field

I'll also need to look at the other fields to see if I missed any others like this.

I'll fix this and include it in a release with a few other minor bug fixes. In the meantime, you can continue working with this query by going into the Hasura Console and making a change here (see screenshot). Enable the `complete` field and click Save Permissions. Do that for `user` and `manager`.

![image](https://user-images.githubusercontent.com/10526228/176962630-a42b36c6-d350-482f-bb06-3b2fb8d811b0.png)
