### ISSUE TITLE
GW will not start after upgrade, DJANGO cannot find POSTGRES username

### ISSUE THREAD

**Issue by SecurityJon** [GhostManager/Ghostwriter#227]
Hi all!

I attempted an upgrade from a very old version of GW to the latest and now I can't get GW to start. Issues I've found are:

- DJANGO did not have the right username/password for PostGres. I noted from the Wiki FAQ that this could be resolved by logging into the POSTGRES docker instance and running psql as postgres to update the password. This not work for me as the user for POSTGRES was different than the defaults, and so I would repeatedly get a "Fatal: role postgres does not exist" error. For anyone else struggling with this, the solution is to locate the username in the ".envs/.production/.postgres" file, and then run `docker exec -it ghostwriter_postgres_1 bash` and then `psql -U <username you just got> -d postgres` which will allow you to change/set the password. For me, the username was 'changeme'

- DJango will not start (constantly restarts) with the following error displayed when I run `docker run -ti --entrypoint /bin/sh ghostwriter_production_django` "/entrypoint: line 10: POSTGRES_USER: parameter not set". I have tried running `./ghostwriter-cli-linux config set POSTGRES_USER <username previously used to login to postgres>` and taking the containers up and down with no success. The FAQ says "you must transfer your PostgreSQL username and password to the new configuration file." When I run `./ghostwriter-cli-linux config` I can see that the username and password have been defined correctly and match the ones I previously used to login to POSTGRES

Any debugging I can do to work out why the DJANGO container doesn't seem to be able to start up?

**Comment by SecurityJon** [comment]
Quick update, I can see that the POSTGRES_USER and other required fields are being pulled out of the environment values, and these aren't being passed into the container.

From the production.yml file these look to be pulled out of the environment values from the host, and if that's the case they don't appear to be set there either.

Is there something that pulls the required values out of the config file and puts them inside environment values to be used that perhaps hasn't started each time for me?

**Comment by SecurityJon** [comment]
Another issue I've found that might be connected. 

`docker logs --tail 50 --follow --timestamps ghostwriter_django_1` produces many instances of 
`cp: can't create '/app/ghostwriter/media/templates/template.docx': Permission denied`

I've popped into the container with `docker run -ti --entrypoint /bin/sh ghostwriter_production_django` and manually created the 'templates' directory which didn't exist, and manually created that directory and file so I'm sure it's not a permission issue, I'm assuming that something is expecting the 'templates' directory to already exist to populate it with the 'template.docx' file. I can't immediately see where that is mapped to the filesystem though, in the DockerFile I can see it appears to be mapped to `production_data` which I can't immediately see.

**Comment by SecurityJon** [comment]
@chrismaddalena  Apologies - I tend to do a walkthrough while I'm sorting out issues.

Unfortunately neither of those suggestions helped.

```[root@ghostwriter Ghostwriter]# ./ghostwriter-cli-linux config get POSTGRES_USER
[+] Getting configuration values:

 Setting        Value
 –––––––        –––––––
 POSTGRES_USER  changeme
```

```
[root@ghostwriter Ghostwriter]# docker-compose -v
docker-compose version 1.29.2, build 5becea4c
```

```
[root@ghostwriter Ghostwriter]# docker -v
Docker version 20.10.13, build a224086
```

Same issue:

```
[root@ghostwriter Ghostwriter]# docker run -ti ghostwriter_production_django
/entrypoint: line 10: POSTGRES_USER: parameter not set
```

**Comment by SecurityJon** [comment]
Further, here are the logs from django

```
[root@ghostwriter Ghostwriter]# sudo docker logs --tail 50 --follow --timestamps ghostwriter_django_1
2022-06-28T07:36:37.548969524Z PostgreSQL is available
2022-06-28T07:36:39.764780422Z 0 static files copied.
2022-06-28T07:36:42.839535829Z CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0005_auto_20210629_1511, 0006_auto_20210922_2325 in sites).
2022-06-28T07:36:42.839559928Z To fix them run 'python manage.py makemigrations --merge'
```

**Comment by SecurityJon** [comment]
For anyone else struggling with this - I didn't manage to solve the issue. What I did manage to do was to get a new instance of GW span up with my old data which seemed to work ok. This is dirty but it worked for me. You will need to know your old logins.

1. Take a copy of the _data directories in `/var/lib/docker/volumes/ghostwriter_production_data` and `/var/lib/docker/volumes/ghostwriter_production_postgres_data`
2. Using Docker commands, delete all images, containers, processes for GW. For me this meant wiping out everything in Docker
3. Delete the GhostWriter folder you downloaded from Git
4. You should now be left with nothing for GW on the system apart from the backup of the two _data folders mentioned earlier
5. Download and install GhostWriter again as per the Wiki instructions
6. Stop Ghostwriter from running with `./ghostwriter containers stop`
7. Wipe out the _data folders in `/var/lib/docker/volumes/ghostwriter_production_data` and `/var/lib/docker/volumes/ghostwriter_production_postgres_data` and replace them with the ones you copied earlier
8. Not sure if required, but I chmod/chown those directories to match the ones I just deleted
9. In your installed GhostWriter folder use the ghostwriter-cli to set the POSTGRES user and password in GhostWriter that matches your old database. For me this was changeme:changeme. Also set your ALLOWEDHOSTS if you're accessing this from another machine
10. Start up GhostWriter again and login with your old credentials. This should work ok. The new 'admin' credentials that are presented in the ghostwriter-cli config command will not work as they are not present in your old data

**Comment by chrismaddalena** [comment]
@SecurityJon Sorry the suggested solutions didn't help. I'm glad you were able to figure something out, though. Thanks for sharing your solution.

Everything is working now, right?

**Comment by SecurityJon** [comment]
Yep!

I had to change some file system permissions as I couldn’t upload templates anymore but apart from that all seems to be working correctly.

**Comment by AnubisSec** [comment]
I was able to recover from this exact scenario by doing the following: 

1. `cat .envs/.production/.postgres` to get the username/password of your postgres setup that was set before upgrading (my username was `ghostwriter` for example, which that and diff password was the issue).
2. Then do `sudo ./ghostwriter-cli config set POSTGRES_PASSWORD <whatever password from step 1>`
3. Then do `sudo ./ghostwriter-cli config set POSTGRES_USER <whatever user from step 1>`
4. Finally, I had to reset the `DJANGO_ALLOWED_HOSTS` even though it was set in my DotEnv file by doing: `sudo ./ghostwriter-cli config allowhost <your domain name>`
5. Then do the usual `sudo ./ghostwriter-cli containers down` and then `up` to reset the containers

I hope this helps others, and you @chrismaddalena for any future issues people run into!

**Comment by chrismaddalena** [comment]
Thanks for sharing, @AnubisSec! I have added an FAQ section in the wiki with an in-depth discussion of transferring the Postgres configuration. Hopefully, that will help anyone running into this in the future.

https://www.ghostwriter.wiki/getting-help/faq#ghostwriter-cli-reports-an-issue-with-postgresql
