### ISSUE TITLE
Support for HTML tables in reports

### ISSUE THREAD

**Issue by inode-** [GhostManager/Ghostwriter#231]
In my tests the HTML tables rendered correctly in the HTML web editor are missing in the docx reports.

It seems that the supported tags are limited to the one supported by the editor: https://github.com/GhostManager/Ghostwriter/blob/1b684ddd119feed9891e83b39c9b314b41d086ca/ghostwriter/modules/reportwriter.py#L281

There is a reason for that?

**Comment by felix-caboff** [comment]
Hi Chris,
Did you identify if this was an easy thing to implement?  I have a colleague who complains a lot the GhostWriter doesn't support findings with tables.
Thanks!

**Comment by chrismaddalena** [comment]
@felix-caboff There is an open PR for it that needs testing. If there are no issues, it will likely be in the v4.1 release.

**Comment by chrismaddalena** [comment]
We included HTML tables in v4.1 so I'm marking this as closed 😄
