### ISSUE TITLE
CVSS Temporal/Environmental Metrics

### ISSUE THREAD

**Issue by rybaz** [GhostManager/Ghostwriter#232]
First off, we are loving the new CVSS additions for findings. It makes it a lot easier to start with a baseline severity and just adjust if needed once we've a finding into a report.

Temporal and environmental metrics would be useful once a finding has actually been moved into a report so we can tailor the severity of a specific finding to match the environment we were in. Our CVSS rankings are our basis for defending (in the unfortunate circumstance where we have to) our severity rankings, and the discussion usually shifts to environmental metrics if any changes need to be made. We can make these on the fly, but having them included in Ghostwriter would be incredibly convenient.

Thanks for all the hard work you do for the underdogs!

**Comment by chrismaddalena** [comment]
This issue is closed but tracked on the road map.
