### ISSUE TITLE
Missing dependency in requirements/base.txt (django-extensions==3.2.0)

### ISSUE THREAD

**Issue by massot-c** [GhostManager/Ghostwriter#237]
**django-extensions is missing in the file requirements/base.txt.**
As the dependency django-extensions is not mentionned on the file requirements/base.txt, the installation process is not complete and the django docker does not work properly.

**To Reproduce**
1. Git clone the project
2. ./ghostwriter-cli-linux install
3. docker logs ghostwriter_django_1

**Comment by chrismaddalena** [comment]
Hi @massot-c,

The `django-extensions` library is only used for development deployments, so it's part of the _local.txt_ requirements file. If you're trying to install a dev environment and notice a library fails to install properly, you may need to bump up system specs and try rebuilding. The most common cause of a bad build is not enough CPU or memory available to Docker. The minimum requirements are now documented here:

https://www.ghostwriter.wiki/getting-started/quickstart#before-you-begin-system-requirements

**Comment by massot-c** [comment]
Hello Chris,
Thanks for your answer. I think I missed something when I deployed Ghostwriter the first time as I had an error with the django-extensions dependency.
Now everything works well. Thank you very much

**Comment by chrismaddalena** [comment]
Oh, good! Thanks for letting me know you got it working 😄
