### ISSUE TITLE
Error in Server Release

### ISSUE THREAD

**Issue by jllang763** [GhostManager/Ghostwriter#24]
Id:
aeb70a427d2146e385153bf1668490da
Name:
fruit-wolfram-harry-oscar
Func:
ghostwriter.shepherd.tasks.release_servers
Hook:
-
Args:
Kwargs:
{}
Result:
No connection adapters were found for '"https://hooks.slack.com/services/{SNIP}"' : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 377, in worker
res = f(*task['args'], **task['kwargs'])
File "/app/ghostwriter/shepherd/tasks.py", line 175, in release_servers
send_slack_msg(message, project.project.slack_channel)
File "/app/ghostwriter/shepherd/tasks.py", line 63, in send_slack_msg
'application/json'})
File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 116, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 640, in send
adapter = self.get_adapter(url=request.url)
File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 731, in get_adapter
raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '"https://hooks.slack.com/services/{SNIP}"'
Group:
Server Release

**Comment by chrismaddalena** [comment]
Hey there, this traceback shows the error occurred once the task tried to send you a Slack message. I've actually never encountered Requests' `No connection adapters were found for <URL>` error before, so I had to read up on it. The primary cause for it is the URL lacks HTTP or HTTPS or is invalid. The webhook URL looks fine and includes the required HTTPS, so all should be well.

Another possibility is a stray character around the URL causing it to become invalid. In my testing the `send_slack_message` function (which is called by this task and others) is working.

I only managed to break things by manually editing the task and adding new lines to the URL. Even then the web request was sent. It just resulted in no Slack messages being received.

Per docs, this error should mean you have an invalid URL. Please check your `envs` files to confirm the URL is correct. AFAIK, the webhook URLs won't contain any special characters we need to worry about.

**Comment by jllang763** [comment]
I removed the `"` from around the slack url and it is now working.

**Comment by chrismaddalena** [comment]
Great! I'll add a note about that to the documentation. You would expect to use quotations, but the `envs` files are actually bash and you don't need the quotes. When the settings are imported, they are imported literally. That means `"some.url.com"` effectively becomes `'"some.url.com"'` and things get weird.

Thanks for the update.
