### ISSUE TITLE
403 Forbidden error after logging in

### ISSUE THREAD

**Issue by Skadoosh-07** [GhostManager/Ghostwriter#240]
After doing the installation when I login to the admin portal, the application responds with 403 Forbidden error and CSRF verification failed 
<img width="476" alt="403" src="https://user-images.githubusercontent.com/55937942/185291037-a800a3b6-7e2b-4bcc-a51c-b6757040a42e.png">

**Comment by chrismaddalena** [comment]
Hey @Skadoosh-07, are you accessing Ghostwriter through a proxy or a forwarded port? This error means your request lacked the CSRF token, the token was invalid, or the `Origin` header did not match.

**Comment by Skadoosh-07** [comment]
I change the port in the production.yml file because I want to host this on a different port
<img width="503" alt="nginx port" src="https://user-images.githubusercontent.com/55937942/185829117-4b936ea8-9e21-4603-bba6-83cddf1f0b8a.png">

**Comment by chrismaddalena** [comment]
That may explain it. Assuming you're accessing 127.0.0.1, the CSRF token is issued for https://127.0.0.1 with an implied port 443. With this configuration, you're accessing https://127.0.0.1:8443, so your `Origin` and `Referer` headers will not match the `Host` header and CSRF validation will fail.

Give this a try:

```
./ghostwriter-cli trustorigin <YOUR_DOMAIN_OR_IP>:8443
./ghostwriter-cli containers down
./ghostwriter-cli containers up 
```

**Comment by Skadoosh-07** [comment]
I tried its giving the error
Error: unknown command "trustorigin" for "ghostwriter-cli"
Run 'ghostwriter-cli --help' for usage.

**Comment by chrismaddalena** [comment]
Great to hear! Thanks for letting me, @Skadoosh-07. I'll close this issue then.
