### ISSUE TITLE
[Feature Request] Add *_rt to all rich text attribute in the app

### ISSUE THREAD

**Issue by pimps** [GhostManager/Ghostwriter#241]
**Is your feature request related to a problem? Please describe.**
The *_rt functionality only exists for finding fields.

**Describe the solution you'd like**
It would be possible to add  *_rt to every rich text field in the app? That way it don't force the use of remove_html filter.

**Describe alternatives you've considered**
At the moment I'm using the remove_html filter to remove tags from the text and use it in the report generation. Although this loses the formatting and isn't the ideal solution.

**Comment by chrismaddalena** [comment]
Thanks for making this ticket for tracking! This enhancement is complete and will be in the upcoming v3.1 release today.
