### ISSUE TITLE
Failed to install on Mac M1 

### ISSUE THREAD

**Issue by 0xkhaled** [GhostManager/Ghostwriter#243]
First thanks for this awesome tool.
I failed to install on Mac M1, the docker container for nginx failed to start in the production setup with the below error message 

"2022/08/31 13:56:28 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (1: Operation not permitted)
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (1: Operation not permitted)" 

So it would be helpful if you have any tips for this issue?

**Comment by 0xkhaled** [comment]
The issue is solved and I think the root cause was the nginx image version is not compatible with the new M1 ship so the solution was to use a newer version.
in compose/production/ngnix/Dockerfile
change the first line in nginx:stable  fixed the issue with me.

**Comment by chrismaddalena** [comment]
Thanks for letting me know! I will look into the latest nginx image for testing.
