### ISSUE TITLE
Unable to use the GraphQL practically

### ISSUE THREAD

**Issue by ta1c0** [GhostManager/Ghostwriter#244]
Hello,

I'm trying to create a script that will automate the process of creating projects and reports.
After the project and report will be created, the script will ask the user for the findings to be filled in the report.

The problem is, that I can't seem to understand even how to create project using GraphQL.
I can't seem to find any documentation on that subject, only on some basic GraphQL queries.

I'm using the Hasura console with the help of the explorer, but every combination I use for the "insert_project" mutation face the same error. I tried adding almost everything under the insert_project fields.

What am I missing?

Thank you.

{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_project.selectionSet",
        "code": "validation-failed"
      },
      "message": "missing selection set for \"project_mutation_response\""
    }
  ]
}

**Comment by chrismaddalena** [comment]
Hey @ta1c0, what is your query? It looks like you haven't specified a response. Even if you don't need/want response data, GraphQL requires one to be set. For example:

```
mutation MyMutation2 {
  insert_project(objects: {clientId: "1", ...}) {
    returning {
      id
    }
  }
}
```

That would create a project and return the new project's `id` value.

**Comment by ta1c0** [comment]
I can't believe the solution was that simple. Sorry for that.
Closing the ticket.
