### ISSUE TITLE
Assigning findings to a report through GraphQL

### ISSUE THREAD

**Issue by ta1c0** [GhostManager/Ghostwriter#245]
Hello again,

I'm using GraphQL to create projects and reports.
I then try to assign findings from the finding library to my previously created report, but I keep getting unwanted results.

When I try to create a new report with findings from my finding library, I end up creating a new finding without information instead of assigning a finding from the already existing findings.
```
mutation createReport {
  insert_report(objects: {title: "SameAsCODENAME", last_update: "2022-09-04", projectId: "25", pptxTemplateId: "2", docxTemplateId: "3", findings: {data: {title: "Authentication bypass", id: "48", cvss_vector: "1"}}}) {
    returning {
      id
      title
    }
  }
}


# It creates a new finding.
{
  "data": {
    "insert_report": {
      "returning": [
        {
          "id": 31,
          "title": "SameAsCODENAME",
          "findings": [
            {
              "title": "Authentication bypass",
              "id": 48
            }
          ]
        }
      ]
    }
  }
}
```

When I try to assign a finding to an existing report, GraphQL gives me errors that some info is missing. 
When I fill in the required info, it once again creates a new finding instead of assigning it.

```
mutation assignFinding {
  insert_reportedFinding(objects: {reportId: "25", id: "23"}) {
    returning {
      id
    }
  }
}

# I am getting the following error
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_reportedFinding.args.objects",
        "code": "constraint-violation"
      },
      "message": "Not-NULL violation. null value in column \"title\" violates not-null constraint"
    }
  ]
}

```

Do I have to create a new finding each time, or is it possible to assign it from the findings library?
Thank you.

**Comment by chrismaddalena** [comment]
Hey @ta1c0,

In your first query, you created an instance for `findings`. That's the findings library entry. The findings that are associated with a report are referenced as `reportedFinding`. To create a finding in a report, you can use `insert_reportedFinding` as you did in the next query. 

In the second query, the error means `title` cannot be left blank/null. Other fields can be left blank, but no finding can be created without a title. If you add `title: "Some Title"` to your objects dictionary that query looks like it should work.

**Comment by ta1c0** [comment]
Hey @chrismaddalena,

Thank you for the reply.

What I'm trying to achieve using a script is as follows:
1) Login through the Login mutation and collect the JWT.
2) Create a new project with all the required fields.
3) Create a new report and associate it with the previously created project
4) Assign findings from my existing findings library based on the finding's id. 
For example, assign finding id '191' (from the "reporting_finding" table from the screenshot).
<img width="502" alt="image" src="https://user-images.githubusercontent.com/86191609/189489957-256c5eca-82c7-4d6a-8770-24984bda9d53.png">
 

Something like the following query: 
``` mutation createReport {
  insert_report(objects: {title: "Testing", last_update: "2022-09-04", projectId: "25",  findings: {data: {title: "Assigned From ID", id: "191"}}}) {
    returning {
      id
    }
  }
}
```

Is that possible?

**Comment by chrismaddalena** [comment]
That's all possible to do. Steps 1-3 are all simple mutations. Projects require a client, so insert a "lookup client" query \ "create client" mutation before step 2 and you have the proper sequence of events to create a project and new report.

The last mutation (adding a finding) is kind of tricky. I'm going to create an action that boils this down to taking a report ID, a finding ID, and some optional values.

For now, you'll want to break adding a finding to the report into two parts for a script:

1. Look-up the finding you want to add to your report
2. Create a mutation like this one with the values copied from the results

```
mutation AddFinding {
  insert_reportedFinding(objects: {reportId: "1", description: "COPY", findingTypeId: "1", hostDetectionTechniques: "COPY", impact: "COPY", mitigation: "COPY", networkDetectionTechniques: "COPY", references: "COPY", replication_steps: "COPY", severityId: "1", title: "COPY", cvss_vector: "COPY", cvss_score: "1"}) {
    affected_rows
  }
}
```

I used `1` as a placeholder for any ID values and `COPY` for any text values. You can also set values like `affectedEntities` and `assignedToId` to assign the finding editing to a specific person attached to the project.

**Comment by chrismaddalena** [comment]
I added an action to make this simpler. In a future release, you'll be able to do this:

```
mutation AttachFinding {
  attachFinding(findingId: 1, reportId: 1) {
    id
  }
}
```

That will attach a finding from your library (`findingId`) to a report (`reportId`). The server will return the `id` of the new finding in the report.

**Comment by ta1c0** [comment]
Exactly what I was looking for!
Thank you for your hard work, appreciate that.

**Comment by chrismaddalena** [comment]
Great! That will be added to the schema soon.
