### ISSUE TITLE
Install error type: "'3'" is not a valid integer

### ISSUE THREAD

**Issue by 4ndr34z** [GhostManager/Ghostwriter#265]
**Describe the bug**
Getting error on installation. 

root@debian:~/Ghostwriter# ./ghostwriter-cli-linux install
[+] Starting production environment installation
[*] Generating new `ghostwriter.crt` and `ghostwriter.key` files
[*] Skipping DH params because /root/Ghostwriter/ssl/dhparam.pem already exists
Error while attempting to convert service.django.healthcheck.retries to appropriate type: "'3'" is not a valid integer
[-] Error from `docker-compose`: exit status 1
2022/11/09 18:40:51 Error trying to build with production.yml: exit status 1

**To Reproduce**
Run installer

**Expected Behavior**

**Screenshots**

**Server Specs:**
 - OS: Debian 11
 - Docker Docker version 20.10.5+dfsg1, build 55c4c88 and docker-compose version 1.25.0, build unknown
 - Ghostwriter 3.1.3

**Additional context**

**Comment by chrismaddalena** [comment]
It looks like you may be using an old version of `docker-compose` that does not properly handle quotations around values. Please make sure your versions for Docker and `docker-compose` are at or above the minimum supported versions:

https://www.ghostwriter.wiki/getting-started/quickstart#before-you-begin-system-requirements

**Comment by 4ndr34z** [comment]
Ahhh...
I just pulled the latest for Debian and figured it was new:-) Installed version 2.x of docker-compose now. Worked. Thank you! :-)

Kind Regards
Andreas Finstad
