### ISSUE TITLE
Idea: add timeline and key events

### ISSUE THREAD

**Issue by fastlorenzo** [GhostManager/Ghostwriter#27]
Just had an idea to improve the tool: it would be helpful to have a timeline functionality to track key events when performing a red team assessment.

Example of structure:
- Project phase: reconnaisance, initial access, lateral movement, ...
- Activity: start recon, stop recon, start phishing campaign, achieved objective, ...
- Additional information: phishing campaign 1, objective 2, ...
- Date: date of the event

I'll see if I can make a PR with this functionality, but wanted to check with you first is this is something you would like to integrate / are already working on.

**Comment by chrismaddalena** [comment]
This is actually in active development 😄 We're very excited about it. There will be full activity tracking tagged with timestamps, usernames, and event details.

The project phase idea could be a separate addition where we can expand the project execution window to plan assessment phases like recon, phishing, etc.

**Comment by fastlorenzo** [comment]
Nice, that's a really good news!
Let me know if you need some help
