### ISSUE TITLE
Executive Summary - Or other report artifacts

### ISSUE THREAD

**Issue by rschwass** [GhostManager/Ghostwriter#271]
I would like to use this tool and this tool alone to generate my reports. So is there a way to add an executive summary from the web app, that I can then use in the jinja templates for my report. like say {{  Project.Executive_Summary }}.

What are the general steps to extend the functionality?

**Comment by er4z0r** [comment]
Currently there isn't. You could experiment with some hacky things like giving a finding a specific name and adding your exec summary in there. IIRC Adding the concept of sections to the report was on the roadmap, I could not find it on the [trello](https://trello.com/b/sF4om6Fy/ghostwriter) right now though.

**Comment by rschwass** [comment]
Thanks for the update.

**Comment by chrismaddalena** [comment]
That's correct. It's a work-in-progress feature that's currently in the `/feature/customizable-report-content` branch. That's not a branch to use, but it's where the work is being done on the feature.
