### ISSUE TITLE
Password Mismatch

### ISSUE THREAD

**Issue by rschwass** [GhostManager/Ghostwriter#273]
I have had success deploying from git but then when I blow out the install and try to redeploy I get issues.

The first issue is the postgres password mismatch. Easy fix.

But then the admin password does not match that i get from running "./ghostwriter-cli config get admin_password"

I have stopped all containers removed all containers and done "docker system prune -a", removed and recloned the repot, restarted the system, and still same issues.

How does the password not match on a clean install, for both the admin account and the postgres account?

**Comment by chrismaddalena** [comment]
Hi @rschwass,

When you run `docker system prune -a`, Docker removes all unused containers, networks, and images but not data volumes. You can prune volumes by adding the `--volumes` flag.

Your PostgresSQL database is on the volume named `production_postgres_data`. That database already has an entry for the admin user with the password set during your installation. That password is the one you want to use. This is also why you had a PostgreSQL password mismatch.

If you'd like to blow everything away and start completely fresh, delete the data volumes and then re-run the `install` command. If you don't have other Docker containers/volumes, you can wipe out containers and volumes with these commands:

```
docker rm -f $(docker ps -a -q)
docker volume rm $(docker volume ls -q)
```

You can also easily delete individual volumes with the `ghostwriter_` prefix in Docker Desktop.

**Comment by rschwass** [comment]
Yes! That works thank you so much!
