### ISSUE TITLE
Add a report language Property

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#276]
As a pentester with both national and international clients I need to create reports both in my native language and English. So I need to maintain at least two different templates (currently it is actually two sets of templates: cvss and non-cvss for each language). 

This requires some caution both during template naming and selection so I don't end up with e.g. an English template containing findings in German which would necessitate me to regenerate the report.

**Describe the solution you'd like**
I'd like to see the language added as property of report and template so it could be used for:

* short term: 
  - filter the template drop-down in the report by language. So if your report language is EN, you only see templates that are EN.
  - filter the template library by language
* some day: 
  - filter search results from the finding library by language. So you only get finding templates in the language matching your report language.

**Describe alternatives you've considered**
As with report rating scheme you could use the tagging feature (once rolled out) to implement this, but using a model property with well defined values/format and some guarantees to its existence sounds like the better option to me.

**Comment by chrismaddalena** [comment]
As we discussed over Slack, I like this idea. It should be something easy to add and support. In the meantime, tags will soon be available for many models, including templates. You can tag a template with something like `language:de` for a visual indicator. That might help while this idea is investigated.

**Comment by fastlorenzo** [comment]
Quick thinking here, maybe it's a silly idea, but why not having internationalized fields for the finding templates?
This could allow in the future to link findings used in reports with their templates and extract stats more easily.
The downside is that, I believe, would require major changes to how the finding templates are handled in the database.

**Comment by chrismaddalena** [comment]
That's a possibility. I worry less about database changes than making edits difficult. I want to avoid adding international fields to a finding and make the form huge. We'd want some way only to view those fields so you can focus on editing one language at a time.

Linking a reported finding with the template more directly is a good idea. Ghostwriter already tracks if a finding started as a blank template. Linking the attached findings to the original template would be excellent for metrics.

**Comment by chrismaddalena** [comment]
This should be possible in the near-ish future via the extra fields feature we're working for v4.1.

**Comment by er4z0r** [comment]
Extra fields?



Christopher Maddalena ***@***.***> schrieb am Do., 9. Nov.
2023, 22:04:

**Comment by chrismaddalena** [comment]
This is the PR for it: #346 

We'll expand it to other models, like report templates. You can add a language field that way. You won't be able to search or filter on custom fields right away but we want to enable that later.

**Comment by chrismaddalena** [comment]
We included custom fields in v4.1 so I'm marking this as closed 😄
