### ISSUE TITLE
Overwriting Paragraph Style when Inserting Rich-Text

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#278]
**Describe the bug**
As shown below I am currently using the `foo_rt `properties in my finding template (e.g. `{{p finding.description_rt}}` ) 

![finding-template](https://user-images.githubusercontent.com/286428/204323236-cfbbdde6-9a4d-4636-b03a-41674efb3532.png)

In my template those jinja expressions referencing the _rt properties are formatted using a specific custom paragraph style.

Unfortunately the resulting document does not use the special paragraph style. Instead it uses the default style (in my German MS Word it is called 'Standard', probably called 'Normal' in English). Is this something. I'm doing wrong during templating or a bug?

**To Reproduce**
1. Create a template
2. Define a custom paragraph style
3. use a rich-text property like `{{p finding.description_rt}}` in your template and format is using the custom style
4. Use template to export 

**Expected Behavior**
The wiki states " The replacement does not affect any formatting or styling ..." so I would have expected it to be in the correct style instead of default. 

**Server Specs:**
 - Ubuntu 22.04
 - Ghostwriter 3.1.4 (latest main)

**Additional context**

**Comment by chrismaddalena** [comment]
We discussed this on Slack, so I'm copying that conversation here so this doesn't seem to be unaddressed.

Under the hood, the RichText objects (`_rt` suffix) are separate Word documents ("subdocuments"). Ghostwriter does the equivalent of opening a Word doc, copying the contents, and pasting it into a new Word doc (your report). The styling is preserved, even if it is pasted into a section with a different style applied.

The documentation line you mentioned ("The replacement does not affect any formatting or styling ...") is meant to apply to all other variables. For example, if you styled just `{{ client.name }}` in a sentence as bold Comic Sans, the client name would replace that, and it would still be bold Comic Sans in the final report.

To change the paragraph style applied to RichText objects, you can edit the standard style in your template, save it, and upload it to Ghostwriter.

If there is a paragraph style you want to be applied only to a specific section (e.g., a part of a finding), then editing the style in the template would not work. There may be alternatives. You can apply alignment and other style changes in the WYSIWYG editor. Those will carry over to the template.

Being able to apply different paragraph styles would be more convenient and consistent. That could be an interesting feature. It's something I can look into for a future update.

**Comment by ArgentEnergy** [comment]
I'm also running into this issue but it seems to be with lists (bullets and numbers) and code samples.

Looks like on reportwriter.py under _process_text_xml line 1439, the code hardcodes font alignment to be left versus using the Word document style.
```
p.alignment = WD_ALIGN_PARAGRAPH.LEFT
```

and _create_list_paragraph defaults to LEFT alignment versus using the Word document style.

**Comment by chrismaddalena** [comment]
I think this should be addressed with the changes from the PR mentioned above. We included the changes in v3.2 so I'm marking this as closed 😄 

If there's still an issue, we can re-open this and look into it.
