### ISSUE TITLE
Idea: report template cutomization

### ISSUE THREAD

**Issue by fastlorenzo** [GhostManager/Ghostwriter#28]
It would be interesting to allow using custom report templates. This could potentially be achieved by implementing something similar as done with [Serpico](https://github.com/SerpicoProject/Serpico)

**Comment by chrismaddalena** [comment]
We do have plans for something like this. It's a lower priority than what we're working on now (see your idea from issue #27). The key reason being that additional logging will undoubtedly change how we look at report generation. I expect we will hash out details for both enhancements in January.

**Comment by WoBuGs** [comment]
An alternative that might be also interesting, at least for docx reports, would be to use something like https://github.com/elapouya/python-docx-template, which is based on the templating language Jinja2.

**Comment by chrismaddalena** [comment]
Ah, interesting... thanks for sharing that. We use python-docx, so perhaps this might be useful.

**Comment by chrismaddalena** [comment]
Ah ha! I had some folks mentions python-docx-template to me again recently and I forgot why it was already on my mind.

PR #66 has implemented template customization. The new template.docx in the repo is a decent example of a basic template. It's not documented yet, but Ghostwriter will continue to build on this foundation. The basics are covered in the documentation for https://github.com/elapouya/python-docx-template. The Ghostwriter project will have some of its own options that will be documented as we move forwarded.

For now, customization uses the python-docx-template Jinja2 tags (as documented within that project) and a `{{p findings_subdoc }}` variable that drops in the findings as a sub-document.

**Comment by fastlorenzo** [comment]
Awesome, thanks a lot for the good work! I'll try it out later
