### ISSUE TITLE
Error generating the document Invalid date string (12 Déc 2022) passed into 'format_datetime()' filter

### ISSUE THREAD

**Issue by kamz69** [GhostManager/Ghostwriter#282]
In the report template, i added the following jinja code to get a nicer formated date :
`{{ project.end_date | format_datetime("d/m/Y") }}`

When the `project.end_date` is in november, there is no issue but when it is set to December (décembre in french), I got this error : 
![image](https://user-images.githubusercontent.com/43749081/206421924-8b4702c8-ab70-4028-9669-2397ebd4d3ec.png)

I use the last version of GhostWriter.

**Comment by chrismaddalena** [comment]
Hey @kamz69,

Thank you for reporting this. A while back, I switched to Python's `dateutils` for better support for non-English month names. It seems to not like Décembre. I assume any string with an accent mark might cause an issue.

```python
from dateutil.parser import parse
parse("12 Déc 2022")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 12 Déc 2022
```

I get the same result with locale set to `fr_FR`. I've found some conflicting information on the subject, but it may be necessary to provide translations (e.g., `Déc` == `Dec`) for the initial date string formatting. I'll look into more to see what the best solution might be.

**Comment by kamz69** [comment]
Hello @chrismaddalena ,

Very fast response  👍 
ok thank you, have a nice day.
