### ISSUE TITLE
Unable to access projects

### ISSUE THREAD

**Issue by optum-shadow** [GhostManager/Ghostwriter#29]
I have pull the merge request #7 into my STG system but I am now getting the following error when accessing any items that was created before that PR.

**ERROR**
django_1    | ERROR 2019-09-10 13:25:17,294 log 14 140591908080968 Internal Server Error: /rolodex/projects/5
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
django_1    |     return self.cursor.execute(sql, params)
django_1    | psycopg2.errors.UndefinedColumn: column shepherd_transientserver.name does not exist
django_1    | LINE 1: ...r"."id", "shepherd_transientserver"."ip_address", "shepherd_...
django_1    |                                                              ^
django_1    | HINT:  Perhaps you meant to reference the column "shepherd_transientserver.note".
django_1    | 
django_1    | 
django_1    | The above exception was the direct cause of the following exception:
django_1    | 
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1    |     response = get_response(request)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
django_1    |     response = self.process_exception_by_middleware(e, request)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
django_1    |     response = response.render()
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 106, in render
django_1    |     self.content = self.rendered_content
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
django_1    |     content = template.render(context, self._request)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
django_1    |     return self.template.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
django_1    |     return self._render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
django_1    |     return self.nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
django_1    |     return compiled_parent._render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
django_1    |     return self.nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
django_1    |     result = block.nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 308, in render
django_1    |     if match:
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 278, in __bool__
django_1    |     self._fetch_all()
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
django_1    |     self._result_cache = list(self._iterable_class(self))
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
django_1    |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
django_1    |     cursor.execute(sql, params)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
django_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
django_1    |     return executor(sql, params, many, context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
django_1    |     return self.cursor.execute(sql, params)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
django_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
django_1    |     return self.cursor.execute(sql, params)
django_1    | django.db.utils.ProgrammingError: column shepherd_transientserver.name does not exist
django_1    | LINE 1: ...r"."id", "shepherd_transientserver"."ip_address", "shepherd_...
django_1    |                                                              ^
django_1    | HINT:  Perhaps you meant to reference the column "shepherd_transientserver.note".
django_1    |

**Comment by fastlorenzo** [comment]
Did you try the [following](https://github.com/GhostManager/Ghostwriter/issues/26#issuecomment-527774223)

**Comment by jllang763** [comment]
Yes, I got the previous error and was able to resolve that issue. Now I am
able to access the site but not any of the project, client or other stuff
created before deploying the changes in PR #7.

**Comment by jllang763** [comment]
So I tried re-running the migration and got the following. 
`docker-compose -f production.yml run --rm django sh -c "/app/manage.py makemigrations && /app/manage.py migrate"
Starting ghostwriter_postgres_1 ... done
Starting ghostwriter_redis_1    ... done
PostgreSQL is available
Migrations for 'reporting':
  ghostwriter/reporting/migrations/0002_auto_20190918_1402.py
    - Add field delivered to report
    - Add field finding_guidance to reportfindinglink
    - Create model LocalFindingNote
    - Create model FindingNote
Migrations for 'rolodex':
  ghostwriter/rolodex/migrations/0002_objectivestatus_projectobjective.py
    - Create model ObjectiveStatus
    - Create model ProjectObjective
Migrations for 'shepherd':
  ghostwriter/shepherd/migrations/0003_auto_20190918_1402.py
    - Change Meta options on transientserver
    - Add field name to staticserver
    - Add field name to transientserver
    - Alter field domain_status on domain
    - Alter field health_status on domain
    - Alter field whois_status on domain
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, django_q, home, reporting, rolodex, sessions, shepherd, sites, socialaccount, users
Running migrations:
  Applying reporting.0002_auto_20190918_1402...Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "delivered" of relation "reporting_report" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 112, in database_forwards
    field,
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 447, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "delivered" of relation "reporting_report" already exists`
