### ISSUE TITLE
Creating client fails on latest version in specific scenario

### ISSUE THREAD

**Issue by ArgentEnergy** [GhostManager/Ghostwriter#290]
Both versions v3.2.0 and v3.2.1 have a bug where you can't create a new client and point of contact at the same time anymore.

<img width="861" alt="Screenshot 2023-02-13 at 9 25 41 AM" src="https://user-images.githubusercontent.com/26912085/218484854-fbe16bac-baa9-4a0c-8228-aed79a3e0824.png">

This issue happens when you want to create a client and contact at the same time. To reproduce:

1. Enter client details
2. Go to the Point of contact page
3. Add contact details
4. Click the save button on the Point of contact page
5. Error will be thrown as the client wasn't created before saving the client contact

**Comment by ArgentEnergy** [comment]
This issue also happens on the project creation too when you enter details on other tabs such as user assignment to project before saving the new project.

**Comment by chrismaddalena** [comment]
Thanks for letting me know. I'll look into it today.

**Comment by chrismaddalena** [comment]
This should be resolved in the latest release. Let me know if any issues continue 😄
