### ISSUE TITLE
Hyperlinks in Notes not recognizable

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#295]
When adding a hyperlink to a note, it will displayed along with all the other text in the note and not be discernible as a hyperlink unless you explicitly hover over it.

**To Reproduce**
1. Add a note to a client/project
2. Insert a hyperlink 
3. Save the note.
4. See that the hyperlink will not be visually set apart (e.g. different color) from the rest of the note.

**Expected Behavior**
Since I use notes to point my colleagues (or tomorrow-me) to things like the clients on-boarding page, password reset, SSL VPN etc. it would be great if hyperlinks could be easily recognized.

**Screenshots**
![gw-css-hyperlink-bug](https://user-images.githubusercontent.com/286428/226292783-9e13b192-794f-44ab-b4c4-9ce347484f93.png)

**Server Specs:**
 - Ghostwriter 3.2.2 release

**Comment by chrismaddalena** [comment]
Thanks for letting me know, @er4z0r. That's an easy thing to fix. I updated the CSS, and the change will be in the next release sometime this week.
