### ISSUE TITLE
[Feature] Support conflict resolution with multiple editors of a report

### ISSUE THREAD

**Issue by BenEdridge** [GhostManager/Ghostwriter#300]
**Is your feature request related to a problem? Please describe.**
Working on a report with multiple users at the same time and losing work without realising when 2 or more people save.

**Describe the solution you'd like**
Does Ghostwriter support conflict resolution? or a collaborative editing solution? A simple locking solution might even be useful until a full CRDT solution is in place. Perhaps I've missed something.

**Comment by chrismaddalena** [comment]
Hey there,

Nothing will prevent you from overwriting someone else's changes, but a warning toast notification is sent out to anyone with a finding open for editing when another user submits changes.

I've looked into collaborative editing solutions. There has been some discussion here on options that do not require third-party services or licenses, but none are simple to drop into the project. It's on the road map for the future.
