### ISSUE TITLE
Show Assigment Dates instead of Project Dates in Dashboard "Project Assignments" 

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#302]
**Describe the bug**
This follows from the recent change of allowing the assignment of an operator to a project in multiple non-overlapping time slots. 
If you do so, the "Project Assignments" Pane on the Dashboard (you know, the one next to "Top Ten Reporting Tasks" will list the same Project twice (since it is two assignments).

**To Reproduce**
1. Create a Project (e.g Start: 1st April, End: 30 September)
2. Assign yourself as an operator twice (e.g. this week and the week after the next)
3. Navigate back to you dashboard
4. Have the new project listed twice (each time with 1st April and 30th September)

**Expected Behavior**
It would be more useful to show the actual start and end-date of the **assignment** here instead of the project dates.

**Screenshots**
![gw-project-multiple-assign](https://user-images.githubusercontent.com/286428/229448531-b3e455ba-7fc9-4d0b-b31d-e3c0fe9715d8.png)
![gw-project-assignments](https://user-images.githubusercontent.com/286428/229448701-11d0ba19-8abd-452c-ac2b-6bc3f9a76b82.png)

**Server Specs:**
 - Ghostwriter v3.2.2, released 13 February 2023

**Additional context**
Especially interesting with long-running projects that might see some operators involved at multiple distinct intervals during the project.

**Comment by chrismaddalena** [comment]
Hey @er4z0r,

I agree. I updated the dashboard to show the project assignment dates instead of the project dates. The change will be in this week's release.

**Comment by chrismaddalena** [comment]
This is live in v3.2.6.
