### ISSUE TITLE
Editing a newly created Oplog entry clears Start/End Dates 

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#308]
**Describe the bug**
When I manually create new oplog entry using the "create" button, it is added to the log with start and end date pre-filled. As soon as I double click a field like "source" and the editing dialogue comes up, the start and end fields are blanked out

**To Reproduce**
1. Create oplog entry using "create" button -> entry added to the log with start/end prefilled
2. Double-Click a field e.g. "source" --> dialoge w/ start/end display as empty

As you can see from the screenshots my date format is d.m.Y when looking at the field in the edit entry dialogue using "Inspect Element" in Firefox I get:

```html
<input type="datetime-local" name="start_date" value="28.04.2023 17:17:53" autocomplete="off" step="1" class="datetimeinput form-control" required="" id="id_start_date">
```
**Expected Behavior**
Start and End fields should display the pre-filled values.

**Screenshots**
![gw-oplog-bug](https://user-images.githubusercontent.com/286428/235215328-1b3d6557-1dbd-4ccc-aa4b-ca00f647a30a.png)

![gw-oplog-bug2](https://user-images.githubusercontent.com/286428/235215372-bbac5b05-2778-4817-bebf-f5d8276b9df1.png)

**Server Specs:**
 - Ghostwriter v3.2.6, released 10 April 2023

**Additional context**
 - Firefox 102.9.0esr , German Locale

**Comment by chrismaddalena** [comment]
To acknowledge this for anyone looking at it here: this was discussed over Slack, and I expect it has to do with an issue between the `datetime-local` field type and the locale. I'll look into this.
