### ISSUE TITLE
Dashboard: Make Role Visible in Assignments

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#311]
**Is your feature request related to a problem? Please describe.**
As an operator I would like to be able to see with what role I'm assigned to a project. Example: If I am assigned as an operator makes big difference compared to being assigned as just person doing technical QA for the final report.

**Describe the solution you'd like**
It would be great to be able to see in what role you are assigned to a project on the dashboard. 
Places I could see that happening:
- Calendar
- Assignments Pane

**Describe alternatives you've considered**
Instead of always including the information one could also just display it if the user hovers over an element like a calendar entry. I'd prefer it to be visible without knowing you can hover over stuff :)

**Additional context**

**Comment by chrismaddalena** [comment]
Thanks for the suggestion! That can be easily added to these displays.

**Comment by chrismaddalena** [comment]
I added the roles to the calendar and dashboard card. I also added a popover tooltip for the events when they get cut off. These changes will be merged into the main branch and included in the next release.
![image](https://github.com/GhostManager/Ghostwriter/assets/10526228/ae17cec9-a680-40cf-b987-20aa1fdec5c7)
