### ISSUE TITLE
Inconsistant variable names and squashed HTML tags

### ISSUE THREAD

**Issue by felix-caboff** [GhostManager/Ghostwriter#317]
**Describe the bug**
Some variables in the JSON output from a report are not the same as those used by the Jinja2 template engine for docx output. 

**To Reproduce**
1. Create a new template that includes the following variables (mine was in a for loop):
finding.mitigation_rt
finding.references_rt
finding.id
3. Attempt to upload, but get a linting error
4. Use these variable names (I guessed at them correctly) instead:
finding.recommendation_rt
finding.references (not the rich text version)
no known alternative to finding.id
6. It works, but these are different to the JSON output which the docs say should be all the variables available.

**Expected Behavior**
Consistant variable declaration

**Additional context**
This was on a new install of v3.2.7

This doesn't feel like a pebkac issue on my part, I would expect consistency on these variable names.  Though it is possible I have missed some crucial bit of documentation.

It probably should also b noted that there are differences in the variable names and the user interface as well.

**Comment by felix-caboff** [comment]
Thank you for getting back to me.  It seems that this field is duplicated with the JSON output.  We have the variable 'recommendation' and 'mitigation' both of which have the same contents.  (Is one of these deprecated?). In the docx though, we don't have mitigation.  I think this is doubly confused by the fact that the web UI uses the title 'mitigation' not 'recommendation'.  Hopefully that clarifies things a little.

Relatedly, but possibly a separate problem is the fact that the 'references' field doesn't appear to have a 'references_rt' version for the docx output.  I am not worried about seeing them in the JSON output, but it would be nice if this particular field existed within the docx output.  Again, I might be mistaken, but, I can't find it and all my other variables with '_rt' work correctly within the same for loop...

And finally, the 'id' field is in the JSON, but is not in the docx output.

I hope that helps clarify the situation!

**Comment by chrismaddalena** [comment]
The `mitigation` key is an alias for `recommendation` for older templates from older versions of Ghostwriter. You can ignore it and use `recommendation`.

The `references_rt` field will exist for all findings. The reporting engine creates that key for every finding, even if the field is empty. If you'd like to see what's available in your template, you can use the Jinja2 `debug` tag as described here: https://www.ghostwriter.wiki/features/reporting/report-templates/word-template-variables#debugging-a-template

As for the `id` key, that is excluded from the findings, but you don't want to use that in a report template. The `id` is the internal index field for the database. Your findings `id` values will not be sequential or meaningful in the template. 

For example, if I add five findings to a report, their `id` values might be 1002, 1005, 1015, 1016, and 1026. You could get sequential values if no one else adds any findings to a report while adding yours, but they will mean little in a report. You can reference the' ordering' key if you want to use a numerical value for ordering findings.

The `ordering` key starts at 0 and resets for each severity category. The values match the ordering you see in the web UI.

**Comment by felix-caboff** [comment]
Hey,

Thank you for all the above and that does answer a couple of the questions.

The mitigation / recommendation key is resolved thank you. There probably should be a bit of documentation about deprecated keys, and I would suggest that the title within the UI needs to reflect the new variable.

The id key vs the order key is ideal, also, thank you.

The `references_rt` field does not generate Rich Text though.  It is my only field that does not create output.  If I use references then I get HTML output, if I use `references_rt` I get blank space.

Thank you!

**Comment by chrismaddalena** [comment]
You're right. I mixed up `position` and `ordering`. Everything I wrote above applies to `position`. The community requested the `ordering` key be added, so there was a key that tracked a finding's position in the list (from the first critical finding to the last informational finding) and did not reset.

You can use the' position' value if you want to reference a unique value in a finding.

For the `references_rt` issue, I can't reproduce this and haven't had any other reports. What is the HTML content of the field?

**Comment by felix-caboff** [comment]
I would still like to suggest that there is variable naming consistency between the various output formats. IMO, either the keys / variables are present or they are not present.  The whole, present in JSON but not present in DOCX is unhelpful.  If that isn't possible for whatever reason, I would still like to suggest that documentation updates would be a good idea.  I am happy to help with this if that is wanted.  (Separate comment on its way for the references issue)

**Comment by chrismaddalena** [comment]
The `id` value for the finding is available in the template. I just don't recommend using it for anything. You can check all the keys and values with lines like:

```
{% for finding in findings %}
{{ finding.keys() }}
{{ finding.values() }}
{% endfor %}
```

The problem you're running into is the linter does not expect to see an `id` value for a finding, so it flags it as an error. That's easy to change.

**Comment by felix-caboff** [comment]
Cool, glad it is an easy fix.  I just think that as your documentation says that all the variables that are in the JSON output are also available in the DOCX output, this should probably be without exceptions.

![image](https://github.com/GhostManager/Ghostwriter/assets/125881693/bf8649ee-706f-4c92-b851-de95e192f985)

So that would be for ID as well as for mitigation (or remove deprecated things?)

**Comment by felix-caboff** [comment]
As for the references rich text issue...

This is the contents of the template:

<img width="307" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/125881693/309ff653-cf97-4659-bdbe-d926812878a1">

This is the contents of the references variable for a test finding:

![image](https://github.com/GhostManager/Ghostwriter/assets/125881693/16f5b1de-0801-41c2-a429-0d117e211b52)

This is the DOCX output opened in LibreOffice:

<img width="260" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/125881693/0143e8ee-54ab-44a4-b06b-9290ad8d98e0">

Your earlier thought about which HTML tags was spot on.  It is stripping `a` tags.  Please can it not do this, or at least flatten it rather than just remove it outright.  If this is intentional, this could also be improved in the documentation.  We use a document collaboration system that allows user's to click on links within the documents, so our preference would be for this feature to be enabled.

Thanks again!

**Comment by chrismaddalena** [comment]
You can use `a` tags as needed. Here is an example using the sample template in Microsoft Word:

![image](https://github.com/GhostManager/Ghostwriter/assets/10526228/9206990e-3a2d-4adf-ae4c-21054eb806f0)

The issue you're encountering is caused by LibreOffice. Others have reported this with Libre as well. LibreOffice's interprets the OpenXML made for Microsoft Word and strips hyperlinks for some reason. Unfortunately, there's no way to avoid that. It's not feasible for me to test and support all the different software that interprets docx documents (e.g., Libre, OpenOffice, Google Docs). Each one has unique quirks, so making a document that works 100% with all of them likely is not possible.

If you see the same issue when downloading and opening a document in Microsoft Word (don't open it in LibreOffice first), I can look into it. When I worked with others on this, the issue was isolated to LibreOffice.

**Comment by felix-caboff** [comment]
Well that is interesting, but unfortunate.  Sounds like this should be reflected in the documentation.  (Happy to help!)

We don't have MSWord licenses so I can't test it unfortunately.  We tend to be a Google Docs organisation and I was only using LibreOffice to deal with a Table of Contents issue.  Interestingly that is a similar issue where if you upload the docx output straight to GDocs, it claims that the embedded links in the ToC are invalid (can't remember exact wording).

**Comment by chrismaddalena** [comment]
That might be something I can look into. If Google Docs reports some issues with links, maybe I can use that to investigate and make Word, Libre, and Docs happy. 

I'll add a note to the wiki about Word and add a note to myself to look into that error in Docs. If I can tweak the OXML to make links work with more than Word, I'm happy to do that. As one person, it's not feasible to test all the apps, but I do try to find a balance that keeps Ghostwriter flexible for different needs.

**Comment by felix-caboff** [comment]
Thank you very much for taking it on, very much appreciated.  If I can be useful, please do let me know.

**Comment by felix-caboff** [comment]
Closing as in practice I think this will be gradually improved over time and does not need a specific Issue.  Thanks again for all the work on this system.
