### ISSUE TITLE
Ability to turn off and rename selected fields in user interface

### ISSUE THREAD

**Issue by felix-caboff** [GhostManager/Ghostwriter#318]
**Is your feature request related to a problem? Please describe.**
We don't use and have no plans to use, some fields that are available in the findings / findings templates.  It would be helpful to be able to remove these so that no one puts any information in them.

**Describe the solution you'd like**
This is potentially achieved in two different steps.  The first would be to have a toggle switch in the admin interface to allow selected fields to be disabled.  The second, and more complex option, would be to be able to rename the fields (and their associated variables for the template engine).  Again, this would need to be within the admin interface.

**Describe alternatives you've considered**
We have thought about just ignoring some of the fields as they aren't pervasive if not filled in.  However, I guarantee someone will use a field we don't have in our templates and then wonder why their text is missing.

**Additional context**
This functionality was not found in v3.2.7
This might already be possible, if so, there is likely a documentation / UI change required to make it more obvious.

**Comment by chrismaddalena** [comment]
This is a feature I have on the roadmap. The plan is to implement it in the next year.

https://trello.com/c/9FgmZX50

**Comment by felix-caboff** [comment]
Oh cool!  I didn't realise there was a road map.
