### ISSUE TITLE
[Enhancement] Evidence as pasted plaintext

### ISSUE THREAD

**Issue by felix-caboff** [GhostManager/Ghostwriter#319]
**Is your feature request related to a problem? Please describe.**
At the moment it is possible to paste plain text into the report fields, however, this can lead to awkward formatting issues.  For example, a block of plaintext that get's highlighted and the 'code' button in the WYSIWYG editor sometimes turns that into lots of small codeblocks rather than one bigger one.

**Describe the solution you'd like**
One way to resolve this would be to introduce a plaintext field in the 'insert evidence' workflow which the system then handles in the same way as a normal .txt file.  This removes the need to save the plaintext into a .txt file first and then upload.

**Comment by chrismaddalena** [comment]
You can paste a text block (e.g., terminal output, logs) into a field without uploading it as a text or log file. If you highlight that text and select the "Inline Code" style, you will get what you're describing, a series of lines formatted as code.

To insert a code block, use the "Code Sample" option to format all that text as one block. In the quick access bar, it's the option that has the `{;}` symbol. The hover text says, "Insert/edit code sample."

**Comment by felix-caboff** [comment]
Hey, thank you again for getting back to me.
The inline code works perfectly, but the codeblock button in the WYSIWYG editor always turns a pasted block into lots of smaller blocks.
For example, like the following when the source is viewed:
![image](https://github.com/GhostManager/Ghostwriter/assets/125881693/187182d9-e7ae-4ac4-97b2-23634319fbff)
This is essentially the same output as the inline code style.  This is why I was wondering if it would be possible to just upload plaintext as evidence.

**Comment by chrismaddalena** [comment]
That HTML shows the inline code style. The code sample / code block style looks like this:

![image](https://github.com/GhostManager/Ghostwriter/assets/10526228/57320759-19c9-432e-a5f0-b3d4083977b6)

If you view the HTML source, you'll see `pre` tags:

```
<pre class="language-markup"><code>$ cd ~/Documents/GitHub/Ghostwriter
$ ls -l
total 31168
-rw-r--r--   1 cmaddalena  staff     54054 May 23 16:17 CHANGELOG.md
-rw-r--r--   1 cmaddalena  staff      5224 May 10  2022 CODE_OF_CONDUCT.md
-rw-r--r--   1 cmaddalena  staff      4600 May 10  2022 CONTRIBUTING.md
-rw-r--r--   1 cmaddalena  staff       367 May 10  2022 CONTRIBUTORS.txt
drwxr-xr-x  12 cmaddalena  staff       384 Jun 22  2022 DOCS</code></pre>
```

If you pasted everything into the editor, highlighted it, and applied the inline code style, your lines will be wrapped in `p` and `code` tags. Each newline/return will close the tags and start a new set.

That will also depend on what you are pasting. If you're copying out of a terminal window, some OS/terminal apps will add returns at the end of every line, leading to an HTML source like your example if you apply the inline code style.

The inline code style is best used for brief inline code (e.g., "The `ls` command..."). If you have a block of text, use the code sample button.

**Comment by felix-caboff** [comment]
Hey,

That is what I am doing...

![image](https://github.com/GhostManager/Ghostwriter/assets/125881693/81895b04-bcda-4d1b-aa70-1c2bb354420a)

I am highlighting the text and clicking the right hand button `<>`.  That just achieves my screenshot(s)

Thanks!

**Comment by chrismaddalena** [comment]
The `<>` button is the inline code style, so you're getting the expected output from that. If you want to create a code block/sample, click the `{;}` button.

**Comment by felix-caboff** [comment]
Actually if you already have your text in the field and you click on either of those buttons they do the same thing.

The one bit that helps is if you click on the `{;}` button before you put the text in you get a 'pop-up' div that gives you more formatting options.  This behaviour should be the same irrespective of if you have text selected as otherwise it leads to confusion like this post.

I think I have also spotted that the WYSIWYG editor prefers to use `<p>` tags rather than `<br/>` tags.  This makes sense for normal text, but less so for code / pen test evidence.  This issue report is probably now more of a usage warning to others and probably, more than anything, implies that there is a documentation improvement required here.  Again, I am happy to help with documentation if you would like.

**Comment by chrismaddalena** [comment]
@felix-caboff That's a good shout. I've never tried clicking the code sample button while selecting text. I would like to know if I can control that. I bet I can't while using the built-in TinyMCE plugin for code samples, but it's easy to customize a plugin.

You're right about the `p` tags. TinyMCE will strip `br` tags, too. I have found cases where it won't strip `br,` but you don't want to have to add `br` to the end of things manually.

I welcome feedback and suggestions for Ghsotwriter and the documentation, and I appreciate your offer! I haven't had anyone try this, but the `Documentation` repo syncs with GitBook.

https://github.com/GhostManager/Documentation

If you submit a PR there with a suggestion it will appear on the wiki.

**Comment by chrismaddalena** [comment]
No problem, @felix-caboff! This is something we can address to. Contributions are always welcome, but not expected. Hopefully your year eases up.
