### ISSUE TITLE
Workflow for retesting

### ISSUE THREAD

**Issue by massot-c** [GhostManager/Ghostwriter#321]
Hello guys,

First, thank you very much for this project! It is awsome.

I have a question about how to properly perform a retest on a scope/project thank to Ghostwriter.

I was tempted to remove the corrected vulnerabilities from my report and regenerate it. But by doing that, I will lose the history of the inital test and I will need to modify the project date, and so one.
Then I was tempted to create a new report inside the project by using the "clone" functionality. But as previously, I need to change the project date and so one, and I will lose some information about the inital test.
The last solution I am working on is to create a new project, with new date and new assignees, and create a new report. But it is time consuming and as my Ghostwriter is linked with another internal tool, it will cause another problem : a vulnerability duplication (as the vulnerability that are not fixed will be present in both report).

So at this time, I did not found a proper way to handle a retest. Do you have any clue ? It might be a good idea for the author of Ghostwriter to explain in the documentation the workflow he imagined for making retests.

Thank you

**Comment by chrismaddalena** [comment]
Hey @massot-c,

Your best options are creating a new project or using the initial one. I did not bake re-testing into Ghostwriter's workflows. Ghostwriter's workflows assume all projects are discrete, with start and end dates. If you expect a project will involve re-testing, you could do something like this:

1. Set the project's end date to that of the final date of re-testing
2. Create project assignments for the initial test and then re-testing

Let's say you have a test starting on Monday, June 20th. The test runs for one week, with one week of re-testing to take place one month after the test is complete. You'd set the project to start on June 20th and end on Friday, July 28th. Then you'd assign people for testing for June 20-25 and July 21-28.

That way, you aren't recreating projects or trying to clone data between projects. I view re-testing as part of that initial project. The project isn't complete until the re-testing is done.

**Comment by massot-c** [comment]
Hello @chrismaddalena,

Thanks a lot for this answer. Everything is clear
