### ISSUE TITLE
Backup PostgreSQL via CLI failing

### ISSUE THREAD

**Issue by DrorDvash** [GhostManager/Ghostwriter#322]
I tried to make a backup through the CLI but I get an error.
Tried with sudo, and also tried when containers are up or down.
![image](https://github.com/GhostManager/Ghostwriter/assets/8413651/2eaec09c-675f-4b29-ae33-cea200d5b4ca)

**Server Specs:**
 - OS: Ubuntu 22.04
 - Ghostwriter v3.2.8
 - Ghostwriter-CLI v0.2.13

**Comment by chrismaddalena** [comment]
The Postgres `backup` command comes from a script from the Django community. It follows general advice not to use the default `postgres` user for backups. You can make a different user and update `POSGTRES_USER` in the configuration or change this line in the command file:

https://github.com/GhostManager/Ghostwriter/blob/master/compose/production/postgres/maintenance/backup#L23

The lines can be commented out or removed.

**Comment by DrorDvash** [comment]
Ok, so those are the steps I did, and it worked. (maybe you can put it in the documentation or something).
Get into Postgres
```
sudo docker exec -it ghostwriter-postgres-1 bash
psql -U postgres
```
Create superuser read-only and grant permissions
```
CREATE USER backup_user SUPERUSER  password 'my_pass';
ALTER USER backup_user set default_transaction_read_only = on;
exit
exit
```
Update configuration file
```
./ghostwriter-cli config set POSTGRES_USER backup_user
./ghostwriter-cli config set POSTGRES_PASSWORD my_pass
```
Backup the DB
```
sudo ./ghostwriter-cli backup
```
Done :))![image](https://github.com/GhostManager/Ghostwriter/assets/8413651/f663b832-9c7f-4248-a3ac-78071347691a)

**Comment by chrismaddalena** [comment]
Thanks for sharing here! I'll close this for now, but let me know if you run into any other issues.
