### ISSUE TITLE
Incorrect Password Issue During Login Attempt

### ISSUE THREAD

**Issue by 0xAnon101** [GhostManager/Ghostwriter#324]
**Describe the bug**
I freshly installed this and up the containers using-
```
docker compose -f local.yml build
docker compose -f local.yml up
```
I got admin password from `./ghoswtriter-cli-linux config get admin_password` but when i tried to login, I got incorrect password. I even uninstalled application , removed volumes , removed docker and then re-installed but same issue persists.
I also did installation like the one mentioned in ghostwriter.wiki using ./ghoswtriter-cli-linux  but no resolution.

**Expected Behavior**
The username "admin" and password from `./ghoswtriter-cli-linux config get admin_password`, should've allowed me to login at webapp running on https://127.0.0.1

**Server Specs:**
 - OS: Ubuntu 22LTS  jammy
 - Docker: latest
 - Ghostwriter: latest

What is the issue here ? Why a freshly installed application is having such problems.

**Comment by chrismaddalena** [comment]
Hi @0xAnon101,

If the admin password generated by Ghostwriter does not work for you, an account with that username may have already existed. Depending on how you deleted volumes, a pre-existing database may not have been removed. By default, Docker will delete unused and temporary volumes and leave named volumes untouched. Also, if the admin password is changed in the config, that change isn't reflected in the database.

You can add another user, login as that user, and update the original user's password or continue using your new user.
Run this command:

`docker compose -f production.yml run django python manage.py createsuperuser`
