### ISSUE TITLE
ghostwriter-cli not working on Alpine Linux

### ISSUE THREAD

**Issue by v1ru6** [GhostManager/Ghostwriter#326]
**Describe the bug**
On a fresh install of [Alpine Standard v3.18.2-x86_64](https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86_64/alpine-standard-3.18.2-x86_64.iso) ghostwriter-linux-cli is not producing any results when invoked.

**To Reproduce**
1. Download Ghostwriter using git clone https://github.com/GhostManager/Ghostwriter.git
2. Run cd Ghostwriter
3. Run ./ghostwriter-cli-linux help

**Expected Behavior**
The script should execute and display the help menu.

**Screenshots**

**Server Specs:**
 - OS: Alpine Linux version 3.18.2
 - Docker version 23.0.6, API version 1.42, GO version go1.20.4
 - Docker-compose version v2.17.3
 - Ghostwriter version 3.2.9

**Comment by chrismaddalena** [comment]
Hey @v1ru6,

Ghostwriter CLI uses `net` and other libraries that use dynamic links to `libc` which does not exist on Alpine. That means the pre-built Linux binary won't work on Alpine. You can try compiling Ghostwriter CLI with this env var set: `CGO_ENABLED=0`

The build command is: `go build -ldflags="-s -w -X 'github.com/GhostManager/Ghostwriter_CLI/cmd/config.Version=`git describe --tags --abbrev=0`' -X 'github.com/GhostManager/Ghostwriter_CLI/cmd/config.BuildDate=`date -u '+%d %b %Y'`'" -o ghostwriter-cli main.go`

The other option is using a version of Alpine that support the dynamic links. I understand there are some out there.
