### ISSUE TITLE
ghostwriter-cli install hangs if docker is not running on Windows

### ISSUE THREAD

**Issue by rufflabs** [GhostManager/Ghostwriter#327]
**Describe the bug**
When running `ghostwriter-cli install` on Windows with Docker Desktop installed, if Docker Desktop does not have the docker engine running, ghostwriter hangs after `[*] Generating a new 'dhparam.pem' file (this could take a few minutes)` indefinitely. 

**To Reproduce**
1. Stop Docker engine
2. Run `ghostwriter-cli install`
3. Hangs after generating dhparam.pem

**Expected Behavior**
Detect that docker engine is not available or running and error stating to start the docker engine.

**Screenshots**
With docker engine stopped:
```
PS C:\Code\Ghostwriter> .\ghostwriter-cli.exe install
[+] Checking status of Docker and the Compose plugin...
[+] Starting production environment installation
[*] Generating new `ghostwriter.crt` and `ghostwriter.key` files
[*] Skipping DH params because C:\Code\Ghostwriter\ssl\dhparam.pem already exists
[... no further progress ...]
```
With docker engine running:
```
PS C:\Code\Ghostwriter> .\ghostwriter-cli.exe install
[+] Checking status of Docker and the Compose plugin...
[+] Starting production environment installation
[*] Generating new `ghostwriter.crt` and `ghostwriter.key` files
[*] Skipping DH params because C:\Code\Ghostwriter\ssl\dhparam.pem already exists
#1 [redis internal] load build definition from Dockerfile
#1 transferring dockerfile: 58B done
#1 DONE 0.0s
[... etc until completed ...]
```

**Server Specs:**
 - OS: Windows 11
 - Docker version 24.0.2, build cb74dfc / Docker Compose version v2.18.1
 - Ghostwriter-CLI ( v0.2.13, 23 May 2023 )

**Additional context**
I had just installed Docker Desktop, and then followed quick start wiki to get ghostwriter working. I did not realize that Docker engine was not running. After a few different tries and investigating docker I found it wasn't running. Starting docker engine and then install command ran fine.

**Comment by chrismaddalena** [comment]
Thanks for raising this, @rufflabs. I've never tried to build a container without the Docker daemon running, but the Compose plugin does hang. Compose throws an error if you try to run `up`, but doesn't check if Docker is running for `build`. This is what happens:

```
$ docker compose -f local.yml build
[+] Building 0.0s (0/0)

« Hangs Forever »
```

I'll see if I can add a check for the Docker daemon.

**Comment by chrismaddalena** [comment]
It was easy to check this with `docker info`, so I've added it. You'll now see a message like this:

```
$ ./ghostwriter-cli containers up        
[+] Checking status of Docker and the Compose plugin...
2023/06/28 11:02:35 Docker is installed on this system, but the daemon is not running
```

That change is live on GitHub. I'll update the pre-built binaries in the Ghostwriter repo with the next release.
