### ISSUE TITLE
Changing the default port

### ISSUE THREAD

**Issue by b00n3t0wn** [GhostManager/Ghostwriter#329]
I need to change the default port for Ghostwriter. I've tried changing it in production.yml and nginx.conf, but that seems to just break it. What is the best way to change the default port?

**Comment by chrismaddalena** [comment]
Which port(s) are you trying to change? 443?

If you need to change it, you can update the _production.yml_ file to change 443 to your new port under `ghostwriter_nginx`. Then update the _nginx.conf_ file with the new listening port. That should be fine as long as you aren't trying to use a port already used by another container or service on the host system, like 8080.
