### ISSUE TITLE
Local commands don't run for me.

### ISSUE THREAD

**Issue by commandodev** [GhostManager/Ghostwriter#330]
**Describe the bug**
I'm not able to run the commands here

https://www.ghostwriter.wiki/development/modifying-code

e.g. I run

```
docker-compose -f local.yml run --rm django python manage.py makemigrations
```

And I see a callback with missing dependecies 

```
ModuleNotFoundError: No module named 'anymail'
```

I had another one which I solved by adding `Collectfast==2.2.0` to the local.txt requirements

**To Reproduce**

As above

**Expected Behavior**

**Screenshots**

**Server Specs:**
 - OS: [e.g., Ubuntu]

Digital Ocean droplet:
```
uname
 #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

 - Docker [e.g., output of `docker --version` and `docker-compose -v`]
 
`docker-compose version 1.29.2, build unknown`

 - Ghostwriter [e.g., 2.2.3 or whatever is printed at the bottom of the left-hand sidebar]

I'm running some internal changes on top of this commit. No changes to dependencies

```
commit 36edd8903bde927772c2addc06a75efb735872a8 (master)
Merge: 3781a69 ea8489c
Author: Christopher Maddalena <chris.maddalena@protonmail.com>
Date:   Tue May 9 17:35:07 2023 -0700

    Merge pull request #314
    
    Patch: Add roles to assignment displays
```

**Comment by chrismaddalena** [comment]
Are you trying to make modifications to v2.2.3? You only want to use the  _local.yml_ when you're developing or testing something.

That version is also very old. Release v2.2.3 is from February 2022. If you're trying to install Ghostwriter on this DO droplet, I recommend pulling the latest from `main` or the latest release.
