### ISSUE TITLE
Can't access web app on AWS EC2

### ISSUE THREAD

**Issue by klausware** [GhostManager/Ghostwriter#331]
**Describe the bug**
Portal not accessible on https://127.0.0.1 after fresh install on AWS EC2 Ubuntu.

**To Reproduce**
1. Follow exact install instructions to install.
2. `curl -k https://127.0.0.1` --> returns nothing but `curl -k https://0.0.0.0` works and returns the web page

**Expected Behavior**
Should get a valid response back.

**Screenshots**
<img width="528" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/87043130/d4cde1d6-1eb3-431a-949a-72188ce24d62">

<img width="467" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/87043130/0838cf81-d40d-4baa-aa21-026021f17871">

**Server Specs:**
 - OS: AWS Ubuntu Jammy 22.04, t2.xlarge
 - Docker: Docker version 24.0.5, build ced0996, docker-compose version 1.21.0, build 5920eb0
 - Ghostwriter: Ghostwriter-CLI ( v0.2.13, 23 May 2023 )
 
**Additional context**
At this point I've tried adding the EC2 instance's local interface ip, the public ip, and even 0.0.0.0 using `./ghostwriter-cli config allowhost $IP` and I've allowed ports 80 and 443 in my NSGs. Yes there is an elastic ip associated with the instance, but I get no responses when accessing https://{$AWS_EC2_IP}. Is there something else that needs to be done to expose the web app publicly?

**Comment by klausware** [comment]
I realize this might not actually be a bug and could be a config issue but I wasn't sure where else to post this question.

**Comment by chrismaddalena** [comment]
Hey @klausware, if you're able to connect with 0.0.0.0, the server is running and should be accessible on localhost or your elastic IP. You can check the logs by running `./ghostwriter-cli-linux logs<container>`. Check `django` and `nginx` with that command while you try your requests.

Do you see the request logged? If not, then the request isn't making it to the nginx container and something may be blocking it.

You might also check to see if an AWS Security Group is blocking requests for 80/443 on the elastic IP or localhost.

A basic `curl` won't return anything if the server doesn't return a 200 OK response. You can try running it with `--include` to see the response code. That may help determine the problem.

**Comment by klausware** [comment]
Thanks for reply @chrismaddalena. After looking at everything I could think of in the app folders I finally learned from our cloud team that some of the prefixes used for allowing access from a range of ip blocks for a certain zero trust network solution had been updated without my knowledge and that was reason nothing was loading from the outside.

**Comment by chrismaddalena** [comment]
Thanks for the update! I'm glad you found the problem.
