### ISSUE TITLE
Adding Additional Columns to Logs

### ISSUE THREAD

**Issue by SN0WIS** [GhostManager/Ghostwriter#332]
**Is your feature request related to a problem? Please describe.**
No, this feature request would be primarily used for QoL and allow my team to operate solely under Ghostwriter. Currently we use an excel document. We use this because we need an artifacts column to easily track artifacts that we drop to disk with a hash value and artifact location.

**Describe the solution you'd like**
Being able to add additional columns to the logs in Ghostwriter. Or import a CSV file to create the log table.

**Describe alternatives you've considered**
Currently we have to use an excel doc for our operator logs; however, we use Ghostwriter for everything else. We'd like to make Ghostwriter our one stop shop for everything. 

**Additional context**
We met at Black Hat and I discussed this with you. I gave you all of my input there as well. Solely a feature request and QoL issue.

**Comment by chrismaddalena** [comment]
@SN0WIS Thanks for submitting this as an issue for tracking!
