### ISSUE TITLE
Install Fails when building Django container with incorrect permissions

### ISSUE THREAD

**Issue by aidden-laoch** [GhostManager/Ghostwriter#333]
**Describe the bug**
Install fails/hangs waiting for Django to start.

**To Reproduce**
1. Spin up Ubuntu 22.04 on AWS
2. Git Clone Ghostwriter
3. Follow install instructions
4. Run ./ghostwriter-cli-linux install
5. See error

**Expected Behavior**
Ghostwriter to install

**Screenshots**
![gw-cli-install](https://github.com/GhostManager/Ghostwriter/assets/24680240/85ae85db-62eb-47bc-ba00-98a5cc1bd8a1)
![docker-cont-list-django-restarting](https://github.com/GhostManager/Ghostwriter/assets/24680240/9ce48434-4dbf-4821-a940-6f3d9d6cdb22)
![django-docker-logs](https://github.com/GhostManager/Ghostwriter/assets/24680240/8bb3cac6-32c6-402a-962e-d32e8ef0b2e7)

**Server Specs:**
 - OS: Ubuntu 22.04 AWS
 - Docker version 20.10.25, build 20.10.25-0ubuntu1~22.04.1
 - docker-compose version 1.29.2, build unknown
 - Ghostwriter: latest version in GIT as of 8/22/2023

**Comment by chrismaddalena** [comment]
Hey @aidden-laoch, when you say you've tried multiple times, what have you tried?

These permission errors can happen when the container image does not build correctly. It's usually easy to fix by re-running the `build` command: `./ghostwriter-cli containers build`

**Comment by aidden-laoch** [comment]
I tried killing all the containers and volumes then redoing install and I also tried build after clearing it as well.

I ended up killing that VM and starting fresh. The new fresh install on a new VM worked. Not sure what happened on the other one. Only difference between the two was I got cloned to OPT initially and the new fresh box I git clones to /home/user/. Shouldn't have effected anything.

Either way we probably can close it. I imagine it had nothing to do with the code but instead my environment somehow.

**Comment by lwangenheim** [comment]
I had a similar issue installing on a fresh Ubuntu VM and solved it by re-rolling a new VM as well. I'm not sure what the issue was but I wanted to chime in that I've also experienced the same situation. The django install just took forever.

**Comment by chrismaddalena** [comment]
Thanks for the updates and info @aidden-laoch and @lwangenheim. I'll see about publishing images to Docker Hub to avoid any weirdness with building the images.
