### ISSUE TITLE
Add short_name and address to company

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#339]
I just noticed when overhauling our template, that we had things like the company name, address and shortname hardcoded in the template. When looking why I did like that back then, I discovered that the ``company`` object other than the ``client`` does not have fields for `address` and `short_name`.

**Describe the solution you'd like**
It would be great if you could add those two extra attributes. None of them is bound to change very frequently, but when they do it would be way more convenient not having to chase through the template for any hardcoded instaces of them.

**Describe alternatives you've considered**
Leave is. It's no biggie. Just a nice-to-have albeit one that introduces yet another schema change.

**Comment by chrismaddalena** [comment]
That would be an easy thing to add to the Company Info configuration in the settings. I'll look at it today.

The one minor complication is the address should probably be a text field so newlines can be added, if desired. That's easy but I'll need to do some testing to see how it all looks in a report.

**Comment by chrismaddalena** [comment]
<img width="249" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/10526228/9deb473b-2623-4465-9dc4-a565d81eee70">
<img width="200" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/10526228/f0b82ff3-ccee-491b-a72b-cebc3fe105d3">

This is in now, @er4z0r. I'll add this to v4.0.0 soon.

**Comment by er4z0r** [comment]
Holy smokes! I opened this just six hours ago. Your round-trip time is simply amazing 😍. If we ever attend a conference at the same time, prepare for an awkward hug and beverages!

**Comment by chrismaddalena** [comment]
@er4z0r haha, no problem!
