### ISSUE TITLE
Export feature within Operation Logs broken

### ISSUE THREAD

**Issue by patagoniasecurity** [GhostManager/Ghostwriter#341]
**Describe the bug**
After updating to version 4 of Ghostwriter, the export feature of the Operation Logs is broken. Any attempt to export any of the operation logs as CSV is outputting a CSV file with HTML code indicating that "the page was not found".

**To Reproduce**
1. Go to your current project
2. Click on 'Logs' tab
3. Select an active operation log or create a new one and add some entries
4. Select "Export Entries" and check the resulting file

**Expected Behavior**
It should export a CSV file with all the entires within the operation log.

**Screenshots**
Here is the output file:

![image](https://github.com/GhostManager/Ghostwriter/assets/142328349/d2208aaa-1c76-4f92-a37c-c993edb4c750)

**Server Specs:**
 - OS: Ubuntu
 - Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
 - v4.0.0, released 20 September 2023

**Comment by chrismaddalena** [comment]
Hey @patagoniasecurity, thank you for reporting this! The export was still trying to use the old REST API. I resolved this and a new export feature will be in the upcoming v4.0.1 release later today.

**Comment by patagoniasecurity** [comment]
wooow that was fast! Thank you. I really appreciate it and thank you for this amazing software.

Have a great day!
