### ISSUE TITLE
Automatically adjusted text box size

### ISSUE THREAD

**Issue by felix-caboff** [GhostManager/Ghostwriter#344]
**Is your feature request related to a problem? Please describe.**
It is frustrating when working with larger report finding entries that the default size of the input text box (tinyMCE stuff) is so small and I always have to resize it.

**Describe the solution you'd like**
For it to become dynamic and resize according to the size of the text being displayed at any given time.

**Describe alternatives you've considered**
Alternatively, the ability to set a bigger default aperture size would probably do the trick.

I have looked but can't find any configuration options for this - sorry if this already exists.

**Comment by chrismaddalena** [comment]
That's something TinyMCE can accommodate. I will enable resizing to match content with a max size the same height as the browser window height.

**Comment by felix-caboff** [comment]
That sounds ideal!  Thank you!

**Comment by chrismaddalena** [comment]
This feature in in release v4.02, so I am closing this issue.

**Comment by felix-caboff** [comment]
I upgraded to the latest version (v4.0.3) recently and this doesn't appear to be implemented.  Is there a configuration option somewhere that needs to be enabled?
