### ISSUE TITLE
Django No such file or directory error

### ISSUE THREAD

**Issue by DemanNL** [GhostManager/Ghostwriter#347]
**Describe the bug**
A fresh Ghostwriter install using the ghostwriter-cli install command will result in Django giving the following error:
cp: can't stat '/app/ghostwriter/reporting/templates/reports/template.docx': No such file or directory

**To Reproduce**
git clone
./ghostwriter-cli install
Inspect django container after install

**Expected Behavior**
A working Django container.

**Comment by chrismaddalena** [comment]
Hey @DemanNL – As mentioned in the other issue you opened, it looks like the Django container did not build properly. This can happen occasionally. It's rare but it happens. You can resolve it by running `./ghostwriter-cli containers build` or re-running the `install` command.

Eventually I plan to publish images to Docker Hub which will remove the need to build the images locally and reduce the chance of a bad build to zero.
