### ISSUE TITLE
Seed_data instructions missing from wiki

### ISSUE THREAD

**Issue by DemanNL** [GhostManager/Ghostwriter#349]
**Describe the bug**
There used to be seed_data instructions about how to populate the database after an install. This however is missing in the wiki nowadays and ghostwriter-cli didn't populate the database for me.

**To Reproduce**
Search for seed_data in the wiki

**Expected Behavior**
Instructions about seed_data

**Solution**
Please include instructions about running `docker-compose -f production.yml run --rm django /seed_data` after installation.

**Comment by chrismaddalena** [comment]
Hey @DemanNL – You do not need to run that command anymore. That used to be necessary for a new installation but Ghostwriter CLI's `install` and `upgrade` commands handle it these days. The database is populated once the Django container finishes starting. Then the install wraps up with the admin user creation.

Based on the other issue you opened, it looks like your Django container did not build correctly. If you have the `install` output, you should see the database seeding output from Django or an error logged like `Error trying to seed the database: <error>`.
