### ISSUE TITLE
Reassigning Report to different Project

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#368]
**Describe the bug**
I noticed that it is no longer possible to assign a (copied) report to another project. I've tried it with two different users. Neither the first onne(a manager) nor the other (manager with admin privs) can assign the report to a different project

**To Reproduce**
1. Go to a project
2. Create a report
3. Copy the report
4. Edit the copy
5. Observe project drop-down to be read-only (grayed out)

**Expected Behavior**
Project drop-down is editable so you can re-assign the report to a different project

**Server Specs:**
 - OS: Ubuntu 22.04.3 LTS 
 - Docker: 20.10.21, build baeda1f
 - Docker-compose: version v2.4.1
 - Ghostwriter v4.0.1, released 27 September 2023

**Additional context**
We discussed this on Slack on Dec. 7th adding here so it is documented for others.

**Comment by chrismaddalena** [comment]
This issue is closed but tracked on the road map.

**Comment by chrismaddalena** [comment]
This is addressed with #492 that is awaiting review before release.
