### ISSUE TITLE
Namecheap pull error

### ISSUE THREAD

**Issue by kcoble** [GhostManager/Ghostwriter#37]
When running the task ghostwriter.shepherd.tasks.fetch_namecheap_domains to pull domains from namecheap, the following error appears in the logs. The task completes successfully without error in the interface, but no values populate and there are no exceptions thrown.

```
postgres_1  | 2019-10-15 20:54:43.859 UTC [385] DETAIL:  Failing row contains (84, domain.net, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1, 1, null, 1).
postgres_1  | 2019-10-15 20:54:43.859 UTC [385] STATEMENT:  INSERT INTO "shepherd_domain" ("name", "registrar", "dns_record", "health_dns", "creation", "expiration", "all_cat", "ibm_xforce_cat", "talos_cat", "bluecoat_cat", "fortiguard_cat", "opendns_cat", "trendmicro_cat", "mx_toolbox_status", "note", "burned_explanation", "whois_status_id", "health_status_id", "domain_status_id", "last_used_by_id") VALUES ('domain.net', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 1, NULL) RETURNING "shepherd_domain"."id"
postgres_1  | 2019-10-15 20:54:43.865 UTC [385] ERROR:  null value in column "creation" violates not-null constraint
```

**Comment by chrismaddalena** [comment]
What sort of data do you get back from the Namecheap API for this domain name?

The error you provided shows all values returned from Namecheap were blank/null. That shouldn't be possible unless there's something wrong. A solution would be checking each value to see if it exists in the response but any domain returned by the API should have the minimum values when the call is successful.

**Comment by kcoble** [comment]
I added some tests to the fetch_namecheap_domain function, and get the following for each applicable TEST statement.

TEST1 pulls all fields from NameCheap for ech individual domain...
`TEST1: {'ID': 'domain_id', 'Name': 'domain.com', 'User': 'user', 'Created': '02/11/2019', 'Expires': '02/11/2020', 'IsExpired': 'false', 'IsLocked': 'false', 'AutoRenew': 'false', 'WhoisGuard': 'ENABLED', 'IsPremium': 'false', 'IsOurDNS': 'true'}`

TEST2 verifies that all pulled domains are stored in domains_list.

Ignore TEST3 and TEST4. 

It never gets past the try block to TEST5, and the NameCheap information pulled it not stored.

`def fetch_namecheap_domains():
    """Fetch a list of registered domains for the specified Namecheap account. A valid API key, 
    username, and whitelisted IP address must be used. The returned XML contains entries for
    domains like this:
    
    <RequestedCommand>namecheap.domains.getList</RequestedCommand>
    <CommandResponse Type="namecheap.domains.getList">
        <DomainGetListResult>
            <Domain ID="127"
            Name="domain1.com"
            User="owner"
            Created="02/15/2016"
            Expires="02/15/2022"
            IsExpired='False'
            IsLocked='False'
            AutoRenew='False'
            WhoisGuard="ENABLED"
            IsPremium="true"
            IsOurDNS="true"/>
        </DomainGetListResult>
    """
    domains_list = []
    session = requests.Session()
    get_domain_list_endpoint = 'https://api.namecheap.com/xml.response?ApiUser={}&ApiKey={}&UserName={}&Command=namecheap.domains.getList&ClientIp={}&PageSize={}'

    client_ip = settings.NAMECHEAP_CONFIG['client_ip']
    enable_namecheap = settings.NAMECHEAP_CONFIG['enable_namecheap']
    namecheap_api_key = settings.NAMECHEAP_CONFIG['namecheap_api_key']
    namecheap_username = settings.NAMECHEAP_CONFIG['namecheap_username']
    namecheap_page_size = settings.NAMECHEAP_CONFIG['namecheap_page_size']
    namecheap_api_username = settings.NAMECHEAP_CONFIG['namecheap_api_username']

    try:
        # The Namecheap API call requires both usernames, a key, and a whitelisted IP
        req = session.get(
            get_domain_list_endpoint.format(
                namecheap_api_username, namecheap_api_key, namecheap_username,
                client_ip,namecheap_page_size))
        # Check if request returned a 200 OK
        if req.ok:
            # Convert Namecheap XML into an easy to use object for iteration
            root = objectify.fromstring(req.content)
            # Check the status to make sure it says "OK"
            namecheap_api_result = root.attrib['Status']
            if namecheap_api_result == 'OK':
                # Get all "Domain" node attributes from the XML response
                print('[+] Namecheap returned status "{}"'.format(namecheap_api_result))
                for domain in root.CommandResponse.DomainGetListResult.Domain:
                    domains_list.append(domain.attrib)
                    print('TEST1: {}'.format(domain.attrib))
            elif namecheap_api_result == 'ERROR':
                print('[!] Namecheap returned an "ERROR" response, so no domains were returned.')
                if 'Invalid request IP' in req.text:
                    print('L.. You are not connecting to Namecheap using your whitelisted IP address.')
                print('Full Response:\n{}'.format(req.text))
            else:
                print('[!] Namecheap did not return an "OK" response, so no domains were returned.')
                print('Full Response:\n{}'.format(req.text))
        else:
            print('[!] Namecheap API request failed. Namecheap did not return a 200 response.')
            print('L.. API request returned status "{}"'.format(req.status_code))
    except Exception as error:
        print('[!] Namecheap API request failed with error: {}'.format(error))
    # There's a chance no domains are returned if the provided usernames don't have any domains
    if domains_list:
        print('TEST2: {}'.format(domains_list))
        for domain in domains_list:
            entry = {}
            print('TEST3: {}'.format(entry))
            # Set the WHOIS status based on WhoisGuard
            if domain['IsExpired'] == 'true':
                print("GOT EM")
                entry['whois_status'] = WhoisStatus.objects.get(pk=2)
            else:
                try:
                    entry['whois_status'] = WhoisStatus.objects.get(
                        whois_status__iexact=domain['WhoisGuard'].capitalize())
                # Anytying no `Enabled` or `Disabled`, set to `Unknown`
                except:
                    entry['whois_status'] = WhoisStatus.objects.get(pk=3)
            # Convert Namecheap dates to Django
            entry['creation'] = datetime.datetime.strptime(
                domain['Created'], "%m/%d/%Y").strftime("%Y-%m-%d")
            entry['expiration'] = datetime.datetime.strptime(
                domain['Expires'], "%m/%d/%Y").strftime("%Y-%m-%d")
            print('TEST4: {}'.format(entry))
            try:
                instance, created = Domain.objects.update_or_create(
                    name=domain.get('Name')   
                )
                print('TEST5: {}'.format(entry))
                # TODO: something with IsExpired & AutoRenew
                for attr, value in entry.items():
                    setattr(instance, attr, value)
                instance.save()
                print('TEST6: {}'.format(entry))
                print('TEST7: {}'.format(instance))
                print('TEST8: {}'.format(domain))
            except Exception as e:
                pass
    else:
        print('[!] No domains were returned for the provided account!')
`

**Comment by strangerdanger010** [comment]
This worked for me.... Once your GW instance is up and running, shell into your postgresql container and perform the following commands. 

COMMAND: psql -d DATABASENAME - U username
COMMAND: \c ghostwriter
COMMAND: ALTER table shepherd_domain alter column expiration drop not null;
COMMAND: ALTER table shepherd_domain alter column creation drop not null;

These commands lift the "NOT NULL" constraint from the creation and expiration columns. Once you alter the columns, try and rerunning the domain update automation within the GW web interface.

**Comment by sadpanda010** [comment]
This worked for me.... Once your GW instance is up and running, shell into your postgresql container and perform the following commands. 

COMMAND: psql -d DATABASENAME - U USERNAME
COMMAND: \c ghostwriter
COMMAND: ALTER table shepherd_domain alter column expiration drop not null;
COMMAND: ALTER table shepherd_domain alter column creation drop not null;

These commands lift the "NOT NULL" constraint from the creation and expiration columns. Once you have altered the columns, try and rerunning the domain update automation within the GW web interface.
