### ISSUE TITLE
Copy paste image in reproduce vulnerability steps

### ISSUE THREAD

**Issue by HacKeD0x90** [GhostManager/Ghostwriter#376]
When writing the steps to reproduce the vulnerability I have to upload the image to the ghost writer server, which means I need to to save each screen shot.

It would be nice if it's possible to copy paste images directly from notebooks like cherry tree, or word or whatever.
Just copy/paste the image without the need to upload it will save tons of time.

**Comment by andrewchiles** [comment]
I agree this would be an awesome enhancement

**Comment by chrismaddalena** [comment]
We would like to make this possible in the future. It'd be really convenient. WYSIWYG editors, like the one Ghostwriter uses, can support inline images you add on the fly. I'm not sure if you'd be able to copy/paste with TinyMCE, but there may be a solution for it.

In the meantime, you can paste your image into the new evidence form without saving your screenshot to a file first.
