### ISSUE TITLE
Can't delete Notes from findings in the Ghostwritter UI (version v4.0.5)

### ISSUE THREAD

**Issue by marcioalm** [GhostManager/Ghostwriter#381]
**Describe the bug**
In the version v4.0.5, released 12 January 2024 is not possible to delete notes from findings using ghostwritter UI.

**To Reproduce**
1. Create a finding
2. Create a note in the finding and save
3. Go back in the finding, click in notes and click in the delete button. Observe that the action will not work

The following is the debug error message received from WebConsole Firefox:

```
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! [1216](https://xxx/reporting/reports/findings/update/1216)
Uncaught ReferenceError: escapeHtml is not defined
    <anonymous> https://xxx/reporting/reports/findings/update/1216:1464
    jQuery 7
    show https://xxx/static/js/bootstrap.min.js:6
    toggle https://xxx/static/js/bootstrap.min.js:6
    Ct https://xxx/static/js/bootstrap.min.js:6
    jQuery 2
    _jQueryInterface https://xxx/static/js/bootstrap.min.js:6
    <anonymous> https://xxx/static/js/bootstrap.min.js:6
    jQuery 2
```
**Expected Behavior**
Once the click in delete its expected the note to be deleted.

**Comment by chrismaddalena** [comment]
Hey @marcioalm, I'm not able to reproduce this issue with v4.0.5. However, some JavaScript handles the note confirmation dialog and deletion. If there is a console error like this when the page loads or when you try to delete a note, that JavaScript won't be working. This error mentions `escapeHtml`. This is a function defined in _js/project.js_ and a parameter/function in the Toastr library we use. The error is probably referencing the former. Your browser may have an older cached version of _project.js_ that doesn't have `escapeHtml`. Try holding SHIFT while clicking refresh to force the browser to re-fetch all the CSS and JS files.

**Comment by marcioalm** [comment]
Geez... feelz so bad now man... I thought that I had refreshed the browser cache... anyway, really sorry mate. It happened after I updated ghostwritter, so it makes completely sense now. 

Closing the issue and sorry for wasting ur time.

Cheers.

**Comment by chrismaddalena** [comment]
No problem at all @marcioalm! I'm happy to help. I love an easy fix 😄
