### ISSUE TITLE
Jinja2 variables not accessible in word document properties

### ISSUE THREAD

**Issue by domwhewell-sage** [GhostManager/Ghostwriter#389]
The Jinja2 variables don't seem to be accessible in the document properties section. (In MS word select "File" > "Info")
For example:
![image](https://github.com/GhostManager/Ghostwriter/assets/122788350/146f9a4a-8618-444d-a147-8a1867201fba)
These variables don't get replaced. Filling out document properties in word has the added benefit of being available to the operating system so in windows you can use the search function.
![image](https://github.com/GhostManager/Ghostwriter/assets/122788350/934077bd-c977-4ccf-a70e-d895bec82ace)
![image](https://github.com/GhostManager/Ghostwriter/assets/122788350/e2d547de-47a3-4462-bb5e-9b6506ec6833)

**Describe the solution you'd like**
Being able to add the jinja variables into the properties section would be the ideal solution.

**Describe alternatives you've considered**
There are set properties such as "Authors" where all operators of the project could be automatically added or there is the "Tags" section which is where the project.tags could automatically get put.
Its probably best to leave it up to the user though that way they can fill out as much or as little information as they want in the document properties

**Additional context**
I have used python-docx before to add document properties so could contribute a PR if you are open to adding this feature.

**Comment by chrismaddalena** [comment]
I hadn't considered looking at document properties. I think that would be a neat addition. If you'd like to submit another PR for it, I'd be happy to accept the feature 😄 

Otherwise, I'll make a note to take a look at how it might be done.
