### ISSUE TITLE
./ghostwriter-cli install doesn't work as it always shows "-bash: ./ghostwriter-cli: No such file or directory" on Windoes Laptop/Ubantu

### ISSUE THREAD

**Issue by island7** [GhostManager/Ghostwriter#391]
**Describe the bug**
./ghostwriter-cli install doesn't work as it always shows "-bash: ./ghostwriter-cli: No such file or directory" on Windoes Laptop/Ubantu

**To Reproduce**
1. Go to 'Ubantu'
2. Command ./ghostwriter-cli install doesn't work as it always shows "-bash: ./ghostwriter-cli: No such file or directory" on Windoes Laptop/Ubantu

**Expected Behavior**

**Screenshots**

**Server Specs:**
 - OS: [e.g., Ubuntu]
 - Docker [e.g., output of `docker --version` and `docker-compose -v`]
 - Ghostwriter [e.g., 2.2.3 or whatever is printed at the bottom of the left-hand sidebar]

**Additional context**

**Comment by unixerius** [comment]
@chrismaddalena, @island7 was making typos. They did not clone the GhostWriter repo into a directory called "Ubantu", they mean they are trying to install and run GhostWriter in Ubuntu Linux, under Windows. I suspect they are using WSL2. 

This also means that @island7 should be using `ghostwriter-cli-linux` and **not** `ghostwriter-cli` (despite what the quickstart in the wiki says). 

Please go ahead and close this issue.
