### ISSUE TITLE
Provide access to upload / choose finding type icons

### ISSUE THREAD

**Issue by felix-caboff** [GhostManager/Ghostwriter#396]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to supply my own icons for different finding types.  At the moment, there is no way of selecting / uploading an icon for these.  If you create a new finding type, you end up with a generic computer icon instead of anything more meaningful.

**Describe the solution you'd like**
The ability to upload new icons / select from the ones that are already in GhostWriter

**Comment by chrismaddalena** [comment]
That's a great idea. We could add a file field to the finding types for SVG icons. Right now, the webpages use SVG icons from FontAwesome CSS.

**Comment by felix-caboff** [comment]
From Chris' comments, this looked to be a relatively easy enhancement and I think gives it a nice touch and makes it a little easier to navigate in places.  Forgive the "bump" following its auto-closure.

**Comment by chrismaddalena** [comment]
This issue is closed but tracked on the road map.
