### ISSUE TITLE
Link style

### ISSUE THREAD

**Issue by federicodotta** [GhostManager/Ghostwriter#398]
**Is your feature request related to a problem? Please describe.**

Hi! When I generate a report with some links, the style of the links is different from the one generated from Word itself (links are in the same color but not underlined).

**Describe the solution you'd like**

I think that maybe the problem could be fixed by adding a custom style for the links, as the style added for bullet list, numbered list, code, etc.

Thank you for the help and for your great tool!
Federico

**Comment by chrismaddalena** [comment]
Hey, the hyperlink style is managed by a style similar to lists and code blocks. It's the `Hyperlink` style in the Styles pane. There is also the `FollowedHyperlink` style for links that have been clicked. These are some of the default styles Word typically has available in every document so there isn't a need to create it to make sure it's available in the styles XML file.

I'm not sure why links you create in Word would look any different unless you've applied a style other than `Hyperlink`. Perhaps your template lacks the `Hyperlink` style until you insert your own. Try creating a hyperlink in your template, save it, upload that to Ghostwriter, and try generating a report with it to see if that makes a difference.

For example, here is a link in a document I just generated and it's accompanying style displayed in the Style pane.

<img width="710" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/10526228/d0420622-485a-4705-9aa6-f5704b2da33a">
<img width="290" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/10526228/1e1db0d5-9d26-4283-b648-870aa9ff026a">
