### ISSUE TITLE
Support ODT format for report templates 

### ISSUE THREAD

**Issue by stormyordos** [GhostManager/Ghostwriter#399]
**Is your feature request related to a problem? Please describe.**
Being mostly a Linux user and doing most of my pentests on various distros, I am still tied to Windows due to the Office DOCX report template format. Having the option to import an ODT template would allow me to stay on Linux 100% of the time when I'm writing reports.

**Describe the solution you'd like**
Support for the ODT open document format for importing templates and generating reports.

**Describe alternatives you've considered**
Although I know Libreoffice has limited support for this, it's never perfect and ends up messing more complex reports with headers/footers, tables, image placement and non-basic formatting in general.

**Comment by chrismaddalena** [comment]
I have looked into supporting other Office-style products (e.g., LibreOffice, OpenOffice, Google Docs) and it's not feasible right now. The first issue is the API libraries Ghostwriter uses don't support those document types. You can convert them to docx and use them, but then there is another bigger issue.

The bigger issue is the XML content of the documents. If you've ever opened a Word document in OpenOffice or Google Docs (or vice versa), you've probably noticed the contents don't look identical. Some formatting may be completely lost or require a lot of work to fix. The XML written by Ghostwriter for Word doesn't translate 100% to the other products. To support Libre, Open, and Google, Ghostwriter would need multiple versions of its reporting library to pick from based on the product you're using. That would be very difficult to develop, test, and maintain.

I'd like to support more than just Word, but we'll have to see if a better path forward becomes possible.
