### ISSUE TITLE
Idea: support multiple public IPs per server

### ISSUE THREAD

**Issue by fastlorenzo** [GhostManager/Ghostwriter#4]
When using cloud providers to setup re-directors for red teaming, we usually take multiple IPs per server (to be more cost-efficient).

It might be interesting to have that view in the tool, I guess we are not the only ones doing that

**Comment by fastlorenzo** [comment]
Implemented in PR #7

**Comment by chrismaddalena** [comment]
Closing this as PR #7 has been merged.
