### ISSUE TITLE
'NoneType' error for Fetching NameCheap Domains

### ISSUE THREAD

**Issue by SecretSantaa** [GhostManager/Ghostwriter#402]
When trying to use the function "tasks.fetch_namecheap_domains", I'm getting the following error:
```
'NoneType' object is not callable : Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
TypeError: 'NoneType' object is not callable
```

This is what my Scheduled Task looks like:
![image](https://github.com/GhostManager/Ghostwriter/assets/70647055/bc9784cd-386c-4698-b55a-39ee0eef1bf5)

And this is what the "Failed tasks" looks like:
![image](https://github.com/GhostManager/Ghostwriter/assets/70647055/c10dbe99-9b9b-4701-a3d3-51fe96e0ddcf)

**Expected Behavior**
I can authenticate to NameCheap given the API without any issues, and I can verify this under DJANGO Q --> Successful tasks.
![image](https://github.com/GhostManager/Ghostwriter/assets/70647055/c952e495-5dcb-49ae-85b7-68798bdc4d93)

I'm doing this via the "Test Namecheap API" button located at the bottom of https://x.x.x.x/home/management/
![image](https://github.com/GhostManager/Ghostwriter/assets/70647055/bb1f8d06-1b7b-4077-b72d-9078a5c0bad3)

I'm a bit confused because I don't know why I'm getting an error trying to run "tasks.fetch_namecheap_domains" when I'm getting success for testing my authentication to the API.

Any help would be greatly appreciated :)

**Server Specs:**
 - OS: RHEL 7.1
 - Docker: 25.0.4, build 1a576v5
 - Docker Compose: v2.24.7
 - Ghostwriter v4.0.8

**Comment by chrismaddalena** [comment]
Hey @SecretSantaa, that error means Django Q couldn't find the function. You should be good to go with a small change to your task. Provide the full path to it, like you see in the authentication test result:

`ghostwriter.shepherd.tasks.fetch_namecheap_domains`

**Comment by SecretSantaa** [comment]
You're a saint, thank you!
