### ISSUE TITLE
Add Description to Extra Fields

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#404]
**Is your feature request related to a problem? Please describe.**
When I introduce new extra fields that are for instance used in the report, it would be great to able to add a description so new users of our Ghostwriter instance know what a specific extra field is used for and maybe where to obtain the value.

**Describe the solution you'd like**
- Add a 'description' field for extra fields
- Make content available in the web interface as a tooltip for the field name

**Describe alternatives you've considered**
Adding the description as the default value might cause problems down the line (i.e., reporting), if people forget to fill out the extra-field (e.g. an internal project id) and now have the description in the report where the value of the extra field should be (e..g when using the project id as a prefix for finding ids).

**Comment by chrismaddalena** [comment]
We'll look into this. It's a good idea. We'll need to figure out a way to display the description in the UI. It doesn't fit neatly into the current iteration, but that shouldn't be too much work to fix.

**Comment by ColonelThirtyTwo** [comment]
Added https://github.com/GhostManager/Ghostwriter/commit/d972077823e0fef152f62088ad1f3f3d69dd7ed4

**Comment by hash1524** [comment]
hey @er4z0r @chrismaddalena , ive been exploring the tool and i absolutely loved it. Installed it on my windows system and was tinkering around it. I have come across a problem nwhere I'm not able to see any of my screenshopts attached as evidences in the report. Can you please guisde me through it? TIA.

**Comment by er4z0r** [comment]
First of all,welcome to the Ghostwriter Community.

Secondly, please do not post unrelated questions in existing issues. Please open a separate one or join the slack channel so we can discuss your problem.

**Comment by hash1524** [comment]
Sincere apologies from my side. I'm unable to join the slack channel. Can you please send me a link through which I can join? would do me a huge help. Thanks in Advance.

**Comment by ColonelThirtyTwo** [comment]
Closing this since it's merged into v4.1

**Comment by ColonelThirtyTwo** [comment]
> Sincere apologies from my side. I'm unable to join the slack channel. Can you please send me a link through which I can join? would do me a huge help. Thanks in Advance.

You should be able to join the Slack group here: https://join.slack.com/t/bloodhoundhq/shared_invite/zt-1tgq6ojd2-ixpx5nz9Wjtbhc3i8AVAWw .
