### ISSUE TITLE
Keep Findings as Default Tab for Report

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#405]
**Is your feature request related to a problem? Please describe.**
Coming from the pre-4.1 release with an installed base and several users I can foresee acceptance problems when we have to tab to the findings tab every time a report is selected. My bold claim is: Most interaction the operators have with the report is when adding/editing findings. So let's make that as smooth and painless as possible.

**Describe the solution you'd like**
Either make "Findings" the default tab when opening a report **or** make the default tab configurable.

**Describe alternatives you've considered**
I wonder if including a "customizations.js" in the views would allow for better tailoring...

**Comment by chrismaddalena** [comment]
That's good feedback. I tend to agree with the assessment that the Findings tab is likely to be the most used. I'll make the Findings tab the default active tab. We can also experiment with returning you to whatever tab you last looked at, similar to how Ghostwriter remembers if you like to keep your sidebar open or closed.

**Comment by chrismaddalena** [comment]
Added with 006da98bd298f61b4da61e5e1a2145df4ae49254.
