### ISSUE TITLE
Nested {{.inline_code}} keyword doesn't render properly

### ISSUE THREAD

**Issue by danms0** [GhostManager/Ghostwriter#41]
Hi,

It seems utilizing inline_code keyword nested within another keyword (e.g. numbered_list or bulleted_list) doesn't render properly. Example here:

`{{.numbered_list}}Browse target system for {{.inline_code}}.txt{{.end_inline_code}} files containing encrypted password
Step 2, bla bla bla
{{.end_numbered_list}}`

Thanks.

**Comment by chrismaddalena** [comment]
Thank you for reporting this. This is a known issue and has been fixed. I will be pushing some code that resolves it in the next release coming soon.
