### ISSUE TITLE
List Machine Status in Cloud Review Notifications

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#417]
**Is your feature request related to a problem? Please describe.**
As a user reading the slack notifications from the Cloud Review task I'd like to see if any of the listed cloud instances is in a running or shut down state. 

**Describe the solution you'd like**
Add a 'State' field to the slack message showing "Running" or "Shut down". 

**Describe alternatives you've considered**
Manually checking the state. Extra effort that kinda negates the usefulness of the "Cloud Review" task.

**Additional context**
It puts me in a more informed position when arguing with whomever created the instance. With the way things currently are I always have to check the control panel of $cloudprovider before heckling my colleagues about having left an instance running.

**Comment by chrismaddalena** [comment]
That would be a simple change. The task already tracks the state by name (e.g., `running`, `shutting-down`). The task does default to returning only instances that are still running, so most states would show "Running" in the message. However, there are arguments (`aws_only_running` and `do_only_running`) to check all instances, even those shut down, so there are cases where you might have non-running instances returned.

I've added an `Instance State` block to the Slack messages for teardown and untracked notifications. It'll be in the next release from the `v4-1-dev` branch.
