### ISSUE TITLE
.envs_template not saving?

### ISSUE THREAD

**Issue by 0xffff0800** [GhostManager/Ghostwriter#42]
Hey, 

Currently having an issue when I git clone or download manually via .zip. Seems the .envs_templates are not saving to disk the folder nor any of the files inside .envs_templates, even if downloaded / extracting individually. Maybe I'm missing something? Tested on Kali, Ubuntu.

Thanks

**Comment by covertgeek** [comment]
What do you see when you type `ls -la` from the extracted folder?

**Comment by 0xffff0800** [comment]
Thanks for the reply, I see the folders there but cd into them no files are in there.

**Comment by covertgeek** [comment]
The directories inside the `.env_templates` folder are also dotfiles.  Just for a sanity check, are you also doing an `ls -la` in there?

**Comment by 0xffff0800** [comment]
Did a bit of playing around and got it to work using your suggestion. Thanks!
