### ISSUE TITLE
Issue with v4.1 and extra fields

### ISSUE THREAD

**Issue by felix-caboff** [GhostManager/Ghostwriter#428]
**Describe the bug**
Sorry this isn't a great bug report, just want it to get raised in case someone else has spotted this / similar.  I also want to prepend this whole thing with a level of uncertainty that it is related to the use of rich text extra fields.

We upgraded to v4.1 a few weeks ago and it worked fine.  Today I made a change to the configuration to include a report-level extra rich text field "limitations".  I updated the Jinja2 template accordingly to take advantage of the new field and whilst the template lints correctly, it fails on document generation.  From the GW logs I can see this:

```shell
ERROR 2024-05-03 12:46:26,102 views 15 139201525775160 DOCX generation failed unexpectedly for Report 43 and user felix
Traceback (most recent call last):
  File "/app/ghostwriter/reporting/views.py", line 2078, in get
    docx = exporter.run()
  File "/app/ghostwriter/modules/reportwriter/report/docx.py", line 90, in run
    self.process_richtext(self.data)
  File "/app/ghostwriter/modules/reportwriter/report/docx.py", line 59, in process_richtext
    finding["description_rt"] = finding_render(finding["description"])
  File "/app/ghostwriter/modules/reportwriter/report/docx.py", line 49, in finding_render
    return self.process_rich_text_docx(text, finding_context, finding_evidences)
  File "/app/ghostwriter/modules/reportwriter/base/docx.py", line 187, in process_rich_text_docx
    text = self.preprocess_rich_text(text, template_vars)
  File "/app/ghostwriter/modules/reportwriter/base/base.py", line 98, in preprocess_rich_text
    template = self.jinja_env.from_string(text_pagebrea_subbed)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 4, in template
jinja2.exceptions.TemplateSyntaxError: tag name expected
```

In an effort to debug this I have since removed the extra fields and the problem has remained.  I am now at the stage where I am trying to diff DB backups to see if the table structure is at fault here but its a bit dense / difficult to eyeball.

Other debugging steps have included reverting to a previous Jinja2 template and it also experiences the issue and (for boring reasons) I have access to another instance of Ghost Writer which uses one plain text extra field at the project level and it does not have this issue.  These things suggest to me that it is specifically related to rich text extra fields / report-level extra fields, but I am happy to be proven wrong.

**To Reproduce**
1. Add an extra rich text field
2. Reconfigure Jinja2 template
3. Generate report
4. See short-form error, top right of the web GUI

**Expected Behavior**
It should generate the document using the new fields.

**Comment by ColonelThirtyTwo** [comment]
Hi Felix Caboff,

Ghostwriter v4.1 now processes rich text fields as Jinja2 templates. This can cause issues with existing text if it has "{{" or "{%" somewhere in it, since those are now processed as Jinja2 substitutions. You can use `{{ "{{" }}` to escape it or surround the text in `{% raw %}` and `{% endraw %}` to prevent Jinja2 from processing the text.

The line `finding["description_rt"] = finding_render(finding["description"])` in your error indicates that it comes from the description of a finding (we're working on better reporting of where the error comes from).

**Comment by felix-caboff** [comment]
Well, I am happy to report that you were correct.  I found a text-based evidence piece inside a description a finding that included `{%` and that was the issue.  Got to be honest, this is confusing as hell as there are so many debugging steps that I took that would suggest this isn't the case.  Shrug.  Thank you for your suggestion.

**Comment by ColonelThirtyTwo** [comment]
Glad you fixed it. We're working on improving the handling of these errors to hopefully catch them earlier and give more direction as to where it occurred. PR #426 is a first step which will hopefully be merged and released soon.
