### ISSUE TITLE
Project Type problem?

### ISSUE THREAD

**Issue by kernelimage266** [GhostManager/Ghostwriter#44]
I'm currently trying to add a Project in Ghostwriter, and under "Project Type" There is nothing displayed there to enter just a check mark? Any ideas on why nothing is showing up? There is also nothing under "Finding type" neither. Am I missing something? Steps I've done so far:

- Create a new client
- Go to Projects
- selected the client I just made, and input start and end dates

But there is nothing under Project Type or can be selected.

Thanks!

<img width="1569" alt="Screen Shot 2020-01-06 at 11 30 18 PM" src="https://user-images.githubusercontent.com/59592816/71868547-89240900-30dc-11ea-88a2-bf7c0050826d.png">

**Comment by covertgeek** [comment]
It sounds like you might have skipped the database seeding as mentioned in
the wiki.

If you haven't already done so, please follow the steps at
https://github.com/GhostManager/Ghostwriter/wiki/Database-Setup

**Comment by kernelimage266** [comment]
Thank you! Everything is working fine now.
