### ISSUE TITLE
Extra Fields UI Screen Readability Improvement

### ISSUE THREAD

**Issue by v3r5ace** [GhostManager/Ghostwriter#453]
**Is your feature request related to a problem? Please describe.**
Navigating the "Extra Fields" UI is somewhat difficult with large amounts of extra fields, as the text title of the field and the "Preview" button are different sizes, and very far apart on the screen. This has resulted in clicking around several preview buttons until landing on the correct page. 

**Describe the solution you'd like**
There are several solutions possible:
 1. Placing divider lines between each row, allowing an easier correlation between which title corresponds to which preview button
 2. Moving the preview button to be a small eyeball icon directly adjacent to the current edit button
 3. Changing the behavior of clicking on the title of the field to preview by default, and allowing editing only by clicking the edit icon, and removing the preview button altogether 

**Describe alternatives you've considered**
A current workaround is to shrink your window size temporarily to force the preview button closer to the test name of the extra fields. This issue is more apparent on large monitors. 

**Additional context**
See screenshot for a large amount of fields, and the large amount of preview buttons
<img width="1477" alt="Screenshot 2024-06-10 at 12 22 04 PM" src="https://github.com/GhostManager/Ghostwriter/assets/12716538/95a405ba-fc76-4e4c-af6b-f68c1f2780aa">

**Comment by chrismaddalena** [comment]
I forgot to comment on this, but we included an update for this in one of the recent releases. Luke and I discussed it off GitHub.
