### ISSUE TITLE
Observations Tab

### ISSUE THREAD

**Issue by caderob** [GhostManager/Ghostwriter#455]
I'm attempting to add some custom development to the "Current Observations" tab. **My goal is to make the layout of the Observations just like the Findings, but instead of grouping by "severity", I would like to group by "day of observation" and have it reflect that value in the database. My goal is to make the Observations table to look just like the Findings table on the front end.**

Please let me know if this is possible and any guidance you may have.

I cloned the *Observation Table Section* to look like the *Finding Table Section* in the 
ghostwriter > reporting > templates > reporting > report_detail.html page

I swapped the "severity" term from the  to "observationday"  in the 
 section

Here is the error I keep getting
```
django-1  | django.db.utils.ProgrammingError: relation "reporting_observationday" does not exist
django-1  | LINE 1: ..."."weight", "reporting_observationday"."color" FROM "reporting...
```
It appears that I can't figure out how to add reporting_observationday to the database and results in an Internal Server Error

-------------------------------------------------------------------------

Secondly, is there features in place to use DREAD score instead of CVSS?

Thanks!

**Comment by chrismaddalena** [comment]
Hey @caderob, it looks like you're trying to reference `observationday` as a foreign key on the `Observation` table. You'd have to add your `observationday` table to the database and create a foreign key field on the `Observation` table. If this is meant to be the date you added the observation to the report, you can add a timestamp field that tracks that.

To group by day like findings are grouped by severity, you'd also need to create a custom filter like the one used for findings (e.g., `group_by_severity`). You need the equivalent of this for sorting by "observation day":

```
            {% group_by_severity report.reportfindinglink_set.all as severity_groups %}
            {% for group, values in severity_groups.items %}
```

As for the DREAD scoring, the built-in calculator uses CVSS v3 for now. There is a PR in progress to add CVSS v4. DREAD isn't planned, but I'd consider a PR for it if someone had the time to add it.

**Comment by caderob** [comment]
Thanks for the input! I added the 'observationday' table using an SQL command post-installation of Ghostwriter. However, I was wondering if there's a way to add an 'observationday' table to the database and create a foreign key field on the Observation table within the actual repository itself, so it creates the tables during the install. Is this possible, and if so, what files need to be manipulated to add that table?

Thanks!

**Comment by chrismaddalena** [comment]
Take a look at the other forms with date fields. You can copy one of those, like the start date field configuration from the project form. You'll add your new date field to the observation form.
