### ISSUE TITLE
Header bookmarks

### ISSUE THREAD

**Issue by domwhewell-sage** [GhostManager/Ghostwriter#460]
**Is your feature request related to a problem? Please describe.**
When adding a link in the tinymce editor you can make it an internal link to a heading ->
(Entering in `#` makes it an internal hyperlink)
<img width="369" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/122788350/eb4a920e-0740-48fd-a828-2820560c310f">
The tinymce editor then adds an `id` attribute to the heading tag, e.g.
```html
<h1 id="h_1741158734421718551414403">Introduction</h1>
```

This id tag is currently stripped and does not end up as a bookmark in the generated docx

**Describe the solution you'd like**
The hyperlink currently gets generated correctly
<img width="519" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/122788350/ffcffc2f-0a1e-47a4-a262-2d152b4656e4">

But the bookmark does not
<img width="307" alt="image" src="https://github.com/GhostManager/Ghostwriter/assets/122788350/51495952-eca8-408e-903b-bc7386bdeecc">

It would be good if bookmarks could be added into the renderer 

**Describe alternatives you've considered**
I had considered adding in a `title_bookmark` field to each finding by adding in the function which only adds in the rich text
```python3
def bookmark_rich_text(self, text, url):
        bookmark = RichText()
        bookmark.xml = '<w:bookmarkStart w:id="" w:name="{}"/>{}<w:bookmarkEnd w:id=""/>'.format(url, text)
        return bookmark
```

**Comment by chrismaddalena** [comment]
Thanks for submitting a PR for this. We'll check it out!

**Comment by er4z0r** [comment]
I'm a bit confused as to what headings I should be able to reference here.

- Can I reference one finding from another finding?
- Can I reference only within the same tinymce window?

**Comment by domwhewell-sage** [comment]
> Can I reference only within the same tinymce window?

Yes any `<hX>` tags within the same tinymce editor will be available. Essentially if you open the "Insert/Edit Link" dialog (Insert > Link) and type `#` in the URL bar it'll generate a list of all headings you can link to (In the same TinyMCE editor).

> Can I reference one finding from another finding?

Not natively but there is a workaround that I use to create links to other findings. I have a Report Extra Field for my entire report template and for each finding I have this in the template `<h2 id="{{ finding.id }}">{{ finding.title }}</h2>`
This allows me to link to other findings provided I know the finding ID (Found in the URL bar) by just typing in `#{finding_id}` into the "Insert/Edit Link" dialog
<img width="243" alt="image" src="https://github.com/user-attachments/assets/e7b9573c-b12e-4d3d-99ff-d55a1e607297">
In my screenshot `502` is a finding ID that exists in my report
