### ISSUE TITLE
Mange personas like you manage domains. 

### ISSUE THREAD

**Issue by dmaynor** [GhostManager/Ghostwriter#47]
This is an idea for further usability. 

Give the user the ability to populate their personas used on engagements. For instance when simulating multiple attacks I create an individual character for each team member on the attacking team. It’s kinda like building a DnD character. How I respond to certain situations depends on which persona is on keyboard. 

Some stats I track:
Best OS
nano vs vim vs emacs 
Sysadmin skill
Developer skill
Operator skill
Self taught or military or college 
Keep updated on TTP?
Go-to attack
Are they moonlighting?
Typing ticks.

The idea would be to track personas in use on each test so operators can check them in and out like a domain. If a persona gets caught to many times he gets blown like domain names do.

**Comment by dmaynor** [comment]
Added note about this being an idea for future visibility.

**Comment by er4z0r** [comment]
I like the idea, though I have a slightly different "angle" on personas. I look at them as sleeves that can be used as part of SE campaigns. They have attributes like any regular person (name, age, sex, date and place of birth), picture and a CV/Vita. They might also have accounts on public services (free-mail providers, twitter, LinkedIn etc.) with associated mobile numbers.
