### ISSUE TITLE
WYSIWYG editor evidence ref AutoComplete

### ISSUE THREAD

**Issue by domwhewell-sage** [GhostManager/Ghostwriter#479]
**Is your feature request related to a problem? Please describe.**
The autocomplete function in the wysiwyg editor currently shows evidence files you have uploaded
<img width="128" alt="image" src="https://github.com/user-attachments/assets/44737511-bb01-4d88-84fe-9b411a794d50">
Could it also autocomplete `{{.ref }}` for the given evidence aswell?

**Describe the solution you'd like**
When typing `@{` it to suggest `{{. evidencefile }}` as it currently does but I propose adding `{{.ref evidencefile}}` aswell just to make it easier to reference all evidence you have in your report.

**Additional context**
It currently autocompletes on `local_edit.html` and `local_observation_edit.html` which would both have to be changed

**Comment by chrismaddalena** [comment]
Yes, we can add that. I'll make the change for the next release.
