### ISSUE TITLE
django.core.exceptions.DisallowedHost

### ISSUE THREAD

**Issue by hellor00t** [GhostManager/Ghostwriter#48]
Having an issue with django.core.exceptions.DisallowedHost hitting when browsing right after creating a super user.

Running in a Ubuntu 18.04 VM, Host OS - MacOS, .env files are stock, local mode

<img width="1279" alt="Screen Shot 2020-01-29 at 8 24 43 PM" src="https://user-images.githubusercontent.com/30711011/73419245-a2833400-42db-11ea-96ce-22e3c4af2689.png">

Has anyone else seen this?

**Comment by covertgeek** [comment]
You might try setting the ALLOWED_HOSTS variable in your .env/.django file.
Please refer to the wiki for more details.

**Comment by hellor00t** [comment]
> You might try setting the ALLOWED_HOSTS variable in your .env/.django file. Please refer to the wiki for more details.
> […](#)

Tried that, no dice. It’s also odd that it works out of the box for others but not my build. Also tried DJANGO_ALLOWED_HOSTS.

**Comment by covertgeek** [comment]
Can you post the ALLOWED_HOSTS in your `.env/.local/.django` file?  Also are you using `docker-compose -f local.yml up -d` or `docker-compose -f production.yml up -d` when bringing up the server?

**Comment by hellor00t** [comment]
IP changed from original, I changed the VM Networking from NAT to bridge to rule out any weirdness there.

Using `docker-compose -f local.yml up -d` from the root of the Ghostwriter directory after doing a git clone from the repo master

```
# General
# ------------------------------------------------------------------------------
USE_DOCKER=yes
IPYTHONDIR=/app/.ipython
DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
DJANGO_ACCOUNT_EMAIL_VERIFICATION=none
ALLOWED_HOSTS= ['192.168.1.144', '*']
# QCluster
# ------------------------------------------------------------------------------
QCLUSTER_NAME=soar
# QCLUSTER_CONNECTION=

# Virustotal
# ------------------------------------------------------------------------------
VIRUSTOTAL_API_KEY=XYZ123

# Slack
# ------------------------------------------------------------------------------
SLACK_ENABLE=True
SLACK_EMOJI=:ghost:
SLACK_CHANNEL=#ghostwriter
SLACK_ALERT_TARGET=<!here>
SLACK_USERNAME=ghostwriter
SLACK_URL=https://hooks.slack.com/services/<your_webhook_url>

# Company Info
# ------------------------------------------------------------------------------
COMPANY_NAME=Ghostwriter
COMPANY_TWITTER=@ghostwriter
COMPANY_EMAIL=info@ghostwriter.local

# Namecheap
# ------------------------------------------------------------------------------
NAMECHEAP_ENABLE=False
NAMECHEAP_API_KEY=
NAMECHEAP_USERNAME=
NAMECHEAP_API_USERNAME=
CLIENT_IP=
NAMECHEAP_PAGE_SIZE=100
```
# Cloud Services
# ------------------------------------------------------------------------------
AWS_KEY=
AWS_SECRET=
DO_API_KEY=
```

**Comment by WoBuGs** [comment]
The configuration variable should be `DJANGO_ALLOWED_HOSTS=['...']`, instead of `ALLOWED_HOSTS` for the production environment configuration file (.env/.production/.django).

For the local environment, the ALLOWED_HOST variable is not taken from the configuration file (.env/.local/.django), but is instead hard-coded in [config/settings/local.py](https://github.com/GhostManager/Ghostwriter/blob/master/config/settings/local.py).

To fix your issue, you can change the local.py file above, and add your IP address to the `ALLOWED_HOST` variable and then run 
`docker-compose -f local.yml stop; docker-compose -f local.yml rm -f; docker-compose -f local.yml build; docker-compose -f local.yml up -d`
