### ISSUE TITLE
KeyError: "no style with name 'ListParagraph'" during export

### ISSUE THREAD

**Issue by shm0sby** [GhostManager/Ghostwriter#499]
Hi, I just started to create my own template for Ghostwriter and after a few iterations, the linting was successful and I created all mentioned formats from the linting output.

Suddenly, I wasn't able to create any report anylonger. I created a report with the default template in the beginning to see the output, but now both templates, mine and the default Word template does not seem to work.

When I try to create the report, I get the error: `KeyError: "no style with name 'ListParagraph'"` paired with a long stacktrace.

I already tried to create a new report and even a new project, but I have no idea, what could suddenly cause that issue.

I add the complete stacktrace as a screenshot. Maybe as a note, I created the Word-format in a German Word installation. I already noticed some missing formats just because of the wording. But that does not explain why the default template doesn't work anymore. :-)

![image](https://github.com/user-attachments/assets/576388bc-922b-4796-b2c1-29088ea30428)

Some additions: I could narrow down that issue to a specific report. In a new report, I could use both templates.

**Comment by ColonelThirtyTwo** [comment]
While we should clean up the error, the issue is that the templates you are using do not have the "ListParagraph" style that GW uses for lists.

My copy of Word includes the style in new documents by default, but you should be able to make it manually by opening the template in Word, selecting "Create a Style" and naming it "List Paragraph".

**Comment by shm0sby** [comment]
I initially expected the template to be wron, but I could solve that issue with creating a new report. I used the same template. So that must have been some kind of temporary issue with that report-object being independent from the template itself. Unfortunately I cannot reproduce it now since the new report-object solved it. :/

**Comment by ColonelThirtyTwo** [comment]
Ok. I'll take a look at it.

**Comment by er4z0r** [comment]
> Yes, indeed the Word installation was also using German language as well as the report.

And do your templates also have linter warnings about Bullet List and Number List? 
If they do not: How did you make that happen :)

**Comment by er4z0r** [comment]
> While we should clean up the error, the issue is that the templates you are using do not have the "ListParagraph" style that GW uses for lists.
> 
> My copy of Word includes the style in new documents by default, but you should be able to make it manually by opening the template in Word, selecting "Create a Style" and naming it "List Paragraph".

I think I may have found a fix: When changing to "List Paragraph" [in the code](https://github.com/GhostManager/Ghostwriter/blob/3519d656c82fedfdfe1ff0b1f7683e811e147ce2/ghostwriter/modules/reportwriter/richtext/docx.py#L583), my report builds again using both my template and the default word template. I believe this has something to do with how styles are referenced in python-docx. There seem to be [differences between builtin-styles and custom styles](https://python-docx.readthedocs.io/en/latest/user/styles-using.html#access-a-style) when it comes to names.

**Comment by shm0sby** [comment]
I could solve the linter warnings with copying the example report formats into my custom format. That solved it for me after the nth iteration.

**Comment by er4z0r** [comment]
Did you do that using word functionality to import styles or did you hack
the styles.xml with an editor?

Lorenz Woth ***@***.***> schrieb am Do., 12. Sept. 2024,
11:33:
