### ISSUE TITLE
Fullscreen is unreadable in Fedora 40

### ISSUE THREAD

**Issue by tweezers-otg** [GhostManager/Ghostwriter#504]
**Describe the bug**
Fullscreen is unreadable in Fedora 40

**To Reproduce**
1. Select the Fullscreen toggle on lower right-hand side of Ghostwriter

**Expected Behavior**
See Ghostwriter in glorious fullscreen.

**Screenshots**
Screen print:
![signal-2024-08-23-03-07-03-075-1](https://github.com/user-attachments/assets/6f91cfa9-609e-49d5-a237-a18266ba1db6)
![signal-2024-08-23-03-07-03-075](https://github.com/user-attachments/assets/d7397efc-af5a-482a-ba29-9746ed175b97)

Phone camera:
![before](https://github.com/user-attachments/assets/c5e2d066-f15a-4965-b5da-b8f0d02085a5)
![after](https://github.com/user-attachments/assets/fc16fae8-2078-44db-9b93-cf824b8e893c)

*Screen print of the fullscreen issue just shows a line across the bottom of the image or but the actual effect on the screen is blurred text - I had to take a phone picture to show the blurring effect on the screen.

**Server Specs:**
 - OS: Fedora 40
 - Ghostwriter Version 24.05.2

**Additional context**
Ghostwriter rules.

**Comment by tweezers-otg** [comment]
These are the screen prints: 

![Screenshot from 2024-08-23 03-01-40](https://github.com/user-attachments/assets/98917b2e-064b-4f58-ad14-c86dd6fd047b)
![Screenshot from 2024-08-23 03-01-48](https://github.com/user-attachments/assets/b6fc59a7-bd99-4c58-878c-9570d0343d6b)

**Comment by chrismaddalena** [comment]
Hey @tweezers-otg, I think you may be looking for the MarkDown editor project for KDE: https://github.com/KDE/ghostwriter
