### ISSUE TITLE
Numbered/ordered list numbering not being restarted in generated reports

### ISSUE THREAD

**Issue by smcgu** [GhostManager/Ghostwriter#506]
**Describe the bug**

Numbered lists are not properly restarting numbering.

**To Reproduce**

1. Add finding to report
2. Add numbered lists to finding
3. Generate report (DOCX)
4. Scroll down to finding

**Expected Behavior**

Numbered lists should restart numbering when there are separate/different lists.

**Screenshots**

Input:

```
<p>First paragraph/list</p>
<ol>
<li>Numbered item 1</li>
<li>Numbered item 2</li>
</ol>
<p>Second paragraph/list</p>
<ol>
<li>This should be item 1, list 2</li>
<li>This should be item 2, list 2</li>
</ol>
```

Incorrect output:

```
First paragraph/list
  1. Numbered item 1
  2. Numbered item 2
Second paragraph/list
  3. This should be item 1, list 2
  4. This should be item 2, list 2
```

Expected output:

```
First paragraph/list
  1. Numbered item 1
  2. Numbered item 2
Second paragraph/list
  1. This should be item 1, list 2
  2. This should be item 2, list 2
```

**Server Specs:**
 - OS: Ubuntu
 - Docker: v27.1.2, build d01f264
 - Docker Compose: v2.29.1
 - Ghostwriter: v4.2.5 (but, this has been present for multiple versions)

**Comment by chrismaddalena** [comment]
Hey @smcgu, we'll take a look at it.
