### ISSUE TITLE
Periodic Purging of expired Django Sessions

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#515]
**Describe the bug**
Ghostwriter keeps accumulating session data.

I just clicked through my admin console and happened upon the sessions section, which contained several hundred sesssions. According to [django documentation](https://docs.djangoproject.com/en/5.1/topics/http/sessions/#clearing-the-session-store):

> Django does not provide automatic purging of expired sessions. Therefore, it’s your job to purge expired sessions on a regular basis. Django provides a clean-up management command for this purpose: [clearsessions](https://docs.djangoproject.com/en/5.1/ref/django-admin/#django-admin-clearsessions). It’s recommended to call this command on a regular basis, for example as a daily cron job.

**Expected Behavior**
Expired sessions should be purged on a regular basis. Not sure (how) it would work inside a container. Can this be done using djangoq? 

**Server Specs:**
 - OS: Ubuntu 22.04
 - Ghostwriter 4.2.1

**Additional context**

**Comment by chrismaddalena** [comment]
Yes, you can call this command (and other commands) by scheduling `django.core.management.call_command` to run. Provide `"clearsessions"` as the only argument to run this command. We can add this to the documentation about session management.
