### ISSUE TITLE
Connecting To Exsiting Accounts not Working with Adapter

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#521]
**Describe the bug**
The changelog for 4.3.0-RC1 states:

> If an existing account has the same email address, the accounts will be linked

I found this to not work in my case. Let's start with my setup. 

```python
SOCIALACCOUNT_PROVIDERS = { 
        'google': { 
            'SCOPE': ['profile','email'],
            'AUTH_PARAMS': { 'access_type': 'online' }
        }
}

SSO_PROVIDERS = ["allauth.socialaccount.providers.google"]
INSTALLED_APPS = INSTALLED_APPS + SSO_PROVIDERS
SITE_ID = 1

SOCIAL_AUTH_AUTHENTICATION_BACKENDS = "social_core.backends.google.GoogleOAuth2"

SOCIAL_ACCOUNT_DOMAIN_ALLOWLIST= ["mycorpdomain.de"]
ACCOUNT_EMAIL_REQUIRED = True
SOCIAL_ACCOUNT_ALLOW_REGISTRATION = True
```
0. Create a user named testuser, with email testuser.tilman@mycorpdomain.de. Have no social logins assigned to that user.
1. Log out of the system.
2. Click on Google 
3. Log in with testuser.tilman@mycorpdomain.de
4. Confirm the OAuth Consent Dialogue with Google
5. Get redirected to the Sign Up screen with the Email field prefilled.
6. Set username testuser and click "Sign Up"
7. Receive error "An account already exists with this email. Please sign into that account frist, then connect your Google account"

**Expected Behavior**

In step  5-7 I'd actually expect there to be no "Sign Up" (see Additional Context) but a "Connect Account" form where you basically confirm, that you want to link your local account to your Google Account. I think all-auth does have a /connect endpoint. Actually it might also be nice to have that reachable from the user's profile.

**Workaround**
I'm considering not pre-creating accounts locally and just allowing people to do "Sign Up" via Google for Work, but I'm not entirely comfortable with it.

**Screenshots**
![ghostwriter_sso_existing_user_mtd_google_allow_reg_redacted](https://github.com/user-attachments/assets/fa5901cf-df94-4779-a595-43cf2e26e0c1)
![ghostwriter_sso_existing_user_mtd_google_allow_reg_error_redacted](https://github.com/user-attachments/assets/2865a288-2071-4925-8a76-fc4cddea342a)

**Server Specs:**
 - OS: irrelevant
 - Docker irrelevant
 - Ghostwriter 4.3.0-rc1

**Additional context**
Originally I wanted to have the tightest control possible over who gets an account. So I'd preferably have registration turned of and only allow existing users to connect their Google for Work account. That way I can assure that only accounts I created will have access to the system. I'm pondering to drop that requirement now that RBAC assigns new users the low 'user' role by default.

**Comment by chrismaddalena** [comment]
I used those settings to add Google to my SSO providers, made a new user with my Google email address, logged-in with my Google account, and the existing account connected.

The only difference is you have this config line:

```
SOCIAL_AUTH_AUTHENTICATION_BACKENDS = "social_core.backends.google.GoogleOAuth2"
```

I don't know if `django-allauth` uses that or if it matters. I don't think it has an effect on this. I tried adding it to my config and didn't notice any changes to the results or the login flow.

**Comment by chrismaddalena** [comment]
I think your config was based on an older version. Prior versions of Ghostwriter had an older `django-allauth` that was a release just prior to come consolidation they did. I know `azure` got rolled into `microsoft` where `microsoft` now encompasses anything Azure or Microsoft Graph. Maybe these settings are newer than what you looked at from while back.

I have some details here: https://www.ghostwriter.wiki/features/access-authentication-and-session-controls/single-sign-on#sso-registration-and-domain-allowlist

It's discussed here in the `allauth` docs: https://docs.allauth.org/en/latest/socialaccount/configuration.html
