### ISSUE TITLE
Ghostwriter installation issue

### ISSUE THREAD

**Issue by akshay575** [GhostManager/Ghostwriter#522]
**Describe the bug**
I've been trying to install Ghostwriter on my Windows machine for the past few days, but it keeps failing due to a Docker error. I tried it a couple of times but no success.

**To Reproduce**
1. `ghostwriter-cli.exe install`
2. See error

**Expected Behavior**
Installation should be successful.

**Screenshots**
![image](https://github.com/user-attachments/assets/996e5c97-7e80-4bf1-940d-49d113a9382e)

![image](https://github.com/user-attachments/assets/1ec712ba-ea64-4bef-8cb8-be42ac4b8f01)

**Server Specs:**
 - OS: Windows 10 Home - Build 19045.4894
 - Docker version 27.1.1, build 6312585
 - Docker Compose version v2.29.1-desktop.1
 - Ghostwriter v4.2.5

**Comment by chrismaddalena** [comment]
That error occurs during the build step. It's a Docker error so it's not something we can troubleshoot through the CLI. The first thing I recommend is updating Docker. Your version, v2.29.1, is relatively recent, but the changelogs for v2.29.2-6 (the latest) mention multiple bug fixes for problems with Compose on Windows and WSL2.

If that doesn't fix it, you can try running the commands to see if Docker provides more context.

Run: `docker compose -f production.yml build`

**Comment by akshay575** [comment]
I think the error occurs while starting the container. 

Output from the build command:
![image](https://github.com/user-attachments/assets/c902a879-5f67-46dc-952a-70eb534471b6)

**Comment by akshay575** [comment]
I updated the Docker and pulled latest code but still the same error.

Docker version 27.2.0, build 3ab4256
Docker Compose version v2.29.2-desktop.2

**Comment by chrismaddalena** [comment]
It's happening during the final stages of the build and start-up. The error suggests the Dockerfile does not provide a command to start the container, but the command is in the Dockerfile. It could be something preventing the command from being executed, like a permissions issue with the entrypoint script file.

Do you have integration with WSL enabled under the settings for Docker Desktop? I'd try toggling that to see if it helps. I don't have any issues with Windows, but some coworkers have had issues with WSL causing problems with VMs and containers.

**Comment by chrismaddalena** [comment]
Did you resolve this issue? Was it anything related to WSL?
