### ISSUE TITLE
When submitting project scope lists with a duplicate name, the form generates form validation errors for the duplicate and all subsequent scope lists

### ISSUE THREAD

**Issue by mynoc96** [GhostManager/Ghostwriter#529]
**Describe the bug**

When submitting project scope lists with a duplicate name, the form generates form validation errors for the duplicate and all subsequent scope lists

**To Reproduce**

1. Go to a project scope list
2. Add scope lists: A, B, C, and D with scope list contents of X
3. Submit it.
4. You shouldn't see an error.
5. Rename B to A and submit.
6. You should see form validation errors for B, C, and D.

**Expected Behavior**

Only B should display a form validation error.

**Server Specs:**

 - OS: WSL Ubuntu 22.04 LTS
 - Docker 24.0.7
 - Ghostwriter 4.3.0

**Additional context**

I realize this is a nit-picky bug report, but figured I'd bring it up and you can triage as you see fit.

**Comment by chrismaddalena** [comment]
This comes from how we check for duplicate names. Once we encounter a duplicate, we set a flag and add a validation error to the field. That causes a validation error to be added to each subsequent name field if there are any. It should still work as intended and not do this if we unset the flag after adding the error.
