### ISSUE TITLE
Add report version

### ISSUE THREAD

**Issue by mynoc96** [GhostManager/Ghostwriter#531]
**Is your feature request related to a problem? Please describe.**

You can track project notes, but there doesn't appear to be a way to track report versions.

**Describe the solution you'd like**

Ideally a versions or revisions list under reports to track the user, date, version/revision number, and a note.

**Describe alternatives you've considered**

Adding notes to the report and parsing the text there (that would probably require a split jinja filter).

**Additional context**

None

**Comment by chrismaddalena** [comment]
We could consider making this a default value, but you can get what you want with more flexibility via a custom field. I explained this in your related issue, #532.

The custom field allows you to pick the field type: string, integer (whole numbers), or number (allows for decimal values). The best choice for you will depend on what you want a report version to look like.

**Comment by mynoc96** [comment]
The use case case here would be for tracking changes over the course of the engagement, so would probably need to use some kind of a list of tuples like:` [revision1: ((user: string, date: string, revision/version: string, note: string)), revision2, revision3, etc. ]`

**Comment by chrismaddalena** [comment]
You can call Python's `split` like this: https://github.com/GhostManager/Ghostwriter/issues/532#issuecomment-2386431709

You might be better off making your custom field a formatted text field with a table for your specific use case. As changes are made, the user can add their change notes to the table like a CHANGELOG. Have you tried that?

It would remove the need for the user to update a string with specific requirements and to split and loop over the results in a template.

We could still consider adding some sort of custom split filter.

**Comment by mynoc96** [comment]
Thanks. I used the approach you pointed out.
