### ISSUE TITLE
Inconsistent handling of zero and null values for extra fields

### ISSUE THREAD

**Issue by smcgu** [GhostManager/Ghostwriter#541]
**Describe the bug**

There is inconsistent handling of 0 and null values. For example, the findings extra fields show "No Value Set" under the Findings Library when 0, regardless of the value being null or 0. However, for findings attached to a report, they will always show 0 in the JSON export. And, in the finding editing view, there will be an empty input box for null values and 0 when the value is set to 0.

**To Reproduce**

For the Findings Library:

1. Add an integer extra field in admin panel
2. Open any finding in Findings Library
3. Scroll down to extra fields area of finding
4. Observe that extra field shows as "No Value Set"
5. Edit library finding
6. Set value to 0
7. Save the finding
8. Observe that the finding still shows "No Value Set"

For finding attached to report and the JSON export:

1. Add an integer extra field in the admin panel
2. Open a report
3. Open a finding
4. Scroll to extra fields area
5. Observe that the new extra field is blank
6. Exit finding
7. Switch to Generate tab
8. Generate JSON export
9. Observe that the finding extra field JSON value is 0, even though it is unset

**Expected Behavior**

1. Values explicitly set to 0 should be 0.
2. Values not set should be null.

**Additional context**

Ghostwriter version: v4.2.5

Not running the latest version, yet. Need some additional time to test SSO changes introduced in v4.3.0.

**Comment by chrismaddalena** [comment]
This is because a value of `0` is the same as `None` when checking if a value exists in Python. It's a simple UI adjustment to show the value if it exists or is equal to `0`. I'll push a small change for the UI to check if a value is `0` so it shows the integer or float instead of registering it as no value.

**Comment by smcgu** [comment]
I see it now. If you haven't started on the PR, I'll submit one up real quick this afternoon that should resolve the issue.
