### ISSUE TITLE
Severity calculators supplemental elements do not change score

### ISSUE THREAD

**Issue by felix-caboff** [GhostManager/Ghostwriter#542]
**Describe the bug**
The two CVSS calculators work well, however, the score only changes when the base score is updated.  The CVSS vector updates, but, not the score itself and therefore the qualitative severity rating do not.

This vector for example:

`CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N`

has a 5.3 rating.  But this vector:

`CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N/E:P/RL:O/RC:U/CR:L/IR:L/AR:L/MAV:P/MAC:H/MPR:H/MUI:R/MS:C/MC:H/MI:H/MA:H`

Also has a 5.3 rating and it should be a 4.2.  For clarity this also does not change the qualitative severity rating when crossing a boundry say Medium -> Low.

**To Reproduce**
1. In a finding open the calculator slider
2. Either select values from the calculator or paste in the vector from above.
3. Change the values of any quality that is not in the "base" section.
4. Observe the vector changing in all situations
5. Observe the score not changing except when updating the base section.

**Expected Behavior**
All areas of the calculator should update the score and qualitative severity rating

**Server Specs:**
v4.3.2, released 30 September 2024

**Comment by domwhewell-sage** [comment]
I think this is a duplicate of #536 I have opened a PR to fix that here #537 pending approval

**Comment by felix-caboff** [comment]
Ah cheers @domwhewell-sage I hadn't spotted the other issue, but also aware that the CVSS calc stuff has changed significantly since.  :shrug: Thanks for joining the two together though - I will close this and comment on the one you have linked.
