### ISSUE TITLE
`tag_br` method in `docx.py` file causes an AttributeError and docx generation failure

### ISSUE THREAD

**Issue by d3af90d** [GhostManager/Ghostwriter#562]
**Describe the bug**
A missing *null check* causes an AttributeError and docx generation failure.
Problematic code [here](https://github.com/GhostManager/Ghostwriter/blob/master/ghostwriter/modules/reportwriter/richtext/docx.py#L109)

**To Reproduce**
1. Create a finding using the GraphQL API. 
    The problem does not appear by using the GUI because GW *corrects* the user input when the finding gets saved.
2. Add the following content to a field that is rendered in a your Word template: 
```
<p><strong>This is strong</strong></p><br/><p>\n</p><pre class=\"rich-code\">This is code</pre>
```
I don't use `<br/>` tags but i noticed that GW insert them sometimes in my input and causes crashes in the report generation because of that.
3. If you try to generate the report, it fails with message `'NoneType' object has no attribute 'add_run'`.

**Expected Behavior**
Not Failing.

**Screenshots**

Example of finding with problematic input:
![replication_steps](https://github.com/user-attachments/assets/d72b819f-8722-4cb8-a046-6a1bb2c0b882)

Error:
![image](https://github.com/user-attachments/assets/0c2244d9-f70e-4801-bf9c-a271a905f6eb)

**Server Specs:**
 - Ghostwriter v4.3.5

**Additional context**
The code was introduced in commit [de7af81755ba1ba7bdff026aef4ecb50bb33c185](https://github.com/GhostManager/Ghostwriter/commit/de7af81755ba1ba7bdff026aef4ecb50bb33c185).
The missing check is present in file `ghostwriter/modules/reportwriter/html_to_pptx.py` but not in `ghostwriter/modules/reportwriter/html_to_docx.py` (now the file has a different filename?).

The problem is visible even just by looking at the code since the default value of the `par` argument is None and the method `add_run` is called without checking if it is None or not.

---

**Edit** - **More Context**
I don't exactly know why that kind of input causes the `tag_br` method to be called with `par=None` because I'm not that familiar with GhostWriter internals.

Though, after adding the check of the related pull request, I noticed that various strange behaviours that appeared from time to time, disappeared.

I sometimes had newlines added from nowhere in the generated documents or other strange formatting error that I always attributed to errors in my docx template or poor GW knowledge.

The problem always arised when using the GraphQL API and uploading html code that had a paragraph with just a `<strong>` or `<em>` tag just before a paragraph with `<pre class="rich-code">` tag.

The input presented at the start of the issue is a variant of the problematic input.

**Comment by ColonelThirtyTwo** [comment]
The HTML-to-DOCX converter that GW uses is unlikely going to be able to handle converting arbitrary HTML, since the two are very different formats and have different semantics. I wrote the module tailored to what TinyMCE outputs, since that's what the UI uses.

In this case, a plain `<br>` currently needs to be a descendant of a `<p>` tag, or any other block tag that is converted to a DOCX paragraph.

I can certainly add additional checks to avoid the module from raising an exception, and I will as they come up, but be aware that it may not produce the results that you expect.

**Comment by d3af90d** [comment]
Thanks a lot for the clarification, I'll check out how TinyMCE structures its input.

Btw, I found out about tags needing to be descendant of a `<p>` tag the hard way (the exception message informed me :3).

I will update on any other issue/exception I'll run into.

And thanks for all the great work on GW :D

**Comment by chrismaddalena** [comment]
Thanks for reporting the issue with an excellent write-up! I looked at the PR, and everything looked fine, so I have merged it.
