### ISSUE TITLE
Idea: Add option to activate 2FA for user login.

### ISSUE THREAD

**Issue by joonhohw** [GhostManager/Ghostwriter#58]
The idea is to add the option to activate 2FA for users to login.
This could be implemented with either Duo or Google Authenticator.

**Comment by chrismaddalena** [comment]
That would be a nice feature. I have not done any research into how that might be done with Django. It's probably possible, but we'll have to see.

**Comment by fastlorenzo** [comment]
Another option would be to support radius authentication, then you can setup MFA on that server (using freeradius and Google OTP is quite easy).

**Comment by chrismaddalena** [comment]
This feature is live in v4.x, so I'm closing this issue.
