### ISSUE TITLE
BUG - Typo in reportwriter critical_color

### ISSUE THREAD

**Issue by swisskyrepo** [GhostManager/Ghostwriter#70]
Hello, 
There is a typo in report writer.

```python
File "/app/ghostwriter/reporting/views.py", line 665, in generate_docx
    docx = spenny.generate_word_docx()
  File "/app/ghostwriter/modules/reportwriter.py", line 874, in generate_word_docx
    finding_color = self.critcal_color
AttributeError: 'Reportwriter' object has no attribute 'critcal_color'

```

You can fix it by replacing `self.critcal_color` to `self.critical_color`

https://github.com/GhostManager/Ghostwriter/blob/77ae1f66e685f48795a12a9423bfde3180f5fa73/ghostwriter/modules/reportwriter.py#L874

**Comment by chrismaddalena** [comment]
Thanks! Just fixed it.
