### ISSUE TITLE
Domain Controls Slack Update Repetitive 

### ISSUE THREAD

**Issue by migvic3** [GhostManager/Ghostwriter#78]
When performing an update for the domain health statuses, categories and DNS records for all domains within Ghostwriter slack provides repetitive updates. See below for example:

`@ghostwriter domain.com has been flagged as burned because: Tied to a VirusTotal detected URL, Tied to a VirusTotal detected URL, Tied to a VirusTotal detected URL, Tied to a VirusTotal detected URL, Tied to a VirusTotal detected URL (Bad categories: uncategorized, No Tags, Phishing URLs)`

**Comment by chrismaddalena** [comment]
I forgot to update this when I saw it, so I apologize for the silence. We fixed this so it shouldn't happen wit next release.
