### ISSUE TITLE
Uploading Evidence in production mode

### ISSUE THREAD

**Issue by KitefanaticNL** [GhostManager/Ghostwriter#83]
We are finally running Ghostwriter in production mode after some changes we made.

We were trying to upload evidence true multiple options. First in the finding during the reporting stage and also in the django database section. But on both options we received an: Ooops something went wrong error.

After looking in the django logs I found the following:

_django_1    |   File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
django_1    |     mkdir(name, mode)
django_1    | PermissionError: [Errno 13] Permission denied: '/app/ghostwriter/media/evidence'_

I logged into the docker it self and the media directory existed but the strange thing was that every folder in the ghostwriter directory had the owner "django" except for the media directory.

I fixed this issue by logging in to the docker with root:

_docker exec -ti -u root  ghostwriter_django_1 /bin/sh_

moved into the directory ghostwriter and run the following command:

_chown -R media/_

Now we can upload evidence as needed. The only issue that remains is that when we remove the evidence from ghostwriter is seems to be deleted, but the uploaded file remains on disk in the docker. If you re-upload that file again then it uploads a second one under a different name.

I checked if the django user has the rights to delete the file and he does. when i remove them straight from the docker it works.

**Comment by g3ksmithington** [comment]
@KitefanaticNL is it related to this: https://github.com/GhostManager/Ghostwriter/issues/74#issuecomment-662521118 ?
