### ISSUE TITLE
<p> HTML tag is not rendered

### ISSUE THREAD

**Issue by ReverseBrain** [GhostManager/Ghostwriter#89]
I created a custom Word template using python-docx-template documentation guideline but finding references, affected entities, description, impact, mitigation, replication steps and proably other variables contain HTML \<p> paragraph tags.

This is my template:
![Screenshot_1](https://user-images.githubusercontent.com/8024261/91566830-81072b00-e944-11ea-9fbe-54c45cac584c.png)

This is the generated template:
![Screenshot_2](https://user-images.githubusercontent.com/8024261/91566882-8feddd80-e944-11ea-8499-f52728317c56.png)

Looking at the source code of the editor via Tools -> Source code menu I can see the HTML paragraph tags, maybe the error is related to this behaviour:
![Screenshot_3](https://user-images.githubusercontent.com/8024261/91566911-9d0acc80-e944-11ea-8e32-061761aa5fd4.png)

**Comment by chrismaddalena** [comment]
Hey – yes, Ghostwriter stores all fields related to findings as HTML. When you edit something and see a WYSIWYG editor in the UI (findings, notes) that text will be saved as raw HTML. That is done so you can style the text in the WYSIWYG editor. The report engine will convert the HTML to Open XML for Microsoft Office.

Currently, Ghostwriter does that when generating the content that you can reference as `{{p findings_subdoc }}` in your template.

We plan to eventually support what you are trying to do here. For this template you're built, Ghostwriter would have to parse each of the fields and return a `RichText()` object. Then you could reference them like `{{r finding.description }}`, where the `r` marks it as pre-styled rich text content. We are working on that for a future release.

In the meantime, we could potentially strip the HTML for use cases like this. An optional set of context variables like `pt_findings` for plaintext findings could be useful.

**Comment by Gimpy42** [comment]
+1 on this,
We are having the same limitation with our template were we use table for the vulnerabilities and there are not really any other way to proceed. Also, Richtext would help with special characters that we have in french reports.

**Comment by chrismaddalena** [comment]
We are working on this now. I don't want to promise any timelines, but it's in active development.
