### ISSUE TITLE
Namcheap Domain Pull fails with DoesNotExist

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#92]
Ghostwriter version: current master (c9a5bbc14cba17ec8ebec8309280362e679b5bad )

### Steps to reproduce:
* verify namecheap configuration params (api-key etc.) manually (working)
* configure namechap api accces in `.envs/.local/.django` (partially redacted)
```
# Namecheap
# ------------------------------------------------------------------------------
NAMECHEAP_ENABLE=True
NAMECHEAP_API_KEY=49aXXXXXXXXXXXXXXXXXXXX62
NAMECHEAP_USERNAME=er4z0r
NAMECHEAP_API_USERNAME=er4z0r
CLIENT_IP=XXXXX
NAMECHEAP_PAGE_SIZE=100
```
* rebuild containers as shown in docs: 
```
docker-compose -f local.yml stop; docker-compose -f local.yml rm -f; docker-compose -f local.yml build; docker-compose -f local.yml up -d
``` 
* verify API configuration was updated correctly
* login & trigger 'Pull From Namecheap'

### Observed behavior: 
* Scheduled Task fails with the following error:
```
Domain matching query does not exist. : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 381, in worker
res = f(*task['args'], **task['kwargs'])
File "/app/ghostwriter/shepherd/tasks.py", line 876, in fetch_namecheap_domains
domain_instance = Domain.objects.get(name=domain["Name"])
File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
```

File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
self.model._meta.object_name
ghostwriter.shepherd.models.Domain.DoesNotExist: Domain matching query does not exist.
```
* List of domains stays empty

### Expected behavior
* Successful pull
* Domain List populated with existing domains (5 in my case)

Where can I find more about the actual responses returned by the NC API so I can provide you with more detail?

**Comment by er4z0r** [comment]
So I had a look at  `ghostwriter/shepherd/tasks.py`. So here goes my interpretation based on my quasi-non-existent knowledge of Django:
In my specific case, the problem seems to be that the list of domains returned by NC contains a locked domain
Since this is the first attempt to pull domains, the locked domain is not yet in the database so the query in [line 876](https://github.com/GhostManager/Ghostwriter/blob/c9a5bbc14cba17ec8ebec8309280362e679b5bad/ghostwriter/shepherd/tasks.py#L876) fails.

Can anyone with a better grasp of the code/django confirm that?

**Comment by chrismaddalena** [comment]
Hey @er4z0r , thanks for another detailed report like #93.

Your interpretation is correct. The task assumes a locked domain will already be in the library and attempts to update the record. That's not true in your case, so there is an exception when the query fails.

As mentioned in #93, I am coincidentally working on this task and others, so I'll fix this over the next few days.
