### ISSUE TITLE
Namecheap Domain Pull: Parameter APIUser is missing

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#93]
Just a small gotcha when it comes to the Namecheap API. 

I initially did not test my API access outside Ghostwriter so I did not realize you really needed both the `NAMECHEAP_USERNAME` and `NAMECHEAP_API_USERNAME` so I did not fill in the latter one.
Allthough the Q Task received an error response, it still showed as successful so it took me a moment
to find the problem.

Ghostwriter version: current master (c9a5bbc14cba17ec8ebec8309280362e679b5bad )

### Steps to reproduce:
* configure namechap api accces in `.envs/.local/.django` (Note the missing APIUsername)
```
# Namecheap
# ------------------------------------------------------------------------------
NAMECHEAP_ENABLE=True
NAMECHEAP_API_KEY=49aXXXXXXXXXXXXXXXXXXXX62
NAMECHEAP_USERNAME=er4z0r
NAMECHEAP_API_USERNAME=
CLIENT_IP=XXXXX
NAMECHEAP_PAGE_SIZE=100
```
* rebuild containers as shown in docs: 
```
docker-compose -f local.yml stop; docker-compose -f local.yml rm -f; docker-compose -f local.yml build; docker-compose -f local.yml up -d
``` 
### Observed behavior:
* empty list of domains
* Namecheap Update Task shows as **successfull** despite containing the following response:

```

[!] Namecheap returned an "ERROR" response, so no domains were returned.
Full Response:
<?xml version="1.0" encoding="utf-8"?>
<ApiResponse Status="ERROR" xmlns="http://api.namecheap.com/xml.response">
<Errors>
<Error Number="1010101">Parameter APIUser is missing</Error>
</Errors>
<Warnings />
<RequestedCommand />
<Server>PHX01APIEXT04</Server>
<GMTTimeDifference>--4:00</GMTTimeDifference>
<ExecutionTime>0</ExecutionTime>
</ApiResponse>
```
### Expected behavior
* empty list of domains
* Namecheap Update Task shows as **failed**

Probably best to check for the `<Error>` element in the response and make the Q Task fail based
on the [error-code ](https://www.namecheap.com/support/api/error-codes/) in the value of the `Number` attribute.

**Comment by chrismaddalena** [comment]
Hey @er4z0r, that's for submitting this! Love the details, super helpful.

The task currently reports back the `Error Number` and maps it to status output. I had not considered error 1010101. During testing, I provided invalid usernames, but never tried no username. I am currently rewriting some of the tasks to provide better status output so you won't need to look at stdout or hunt for the cause of an error like this.

I'll look into a better way to log these Namecheap errors. Should have these tasks updated in the repo soon.
