### ISSUE TITLE
Unable to install newest version

### ISSUE THREAD

**Issue by fuckup1337** [GhostManager/Ghostwriter#94]
Hi, I am unable to install the newest master - based on the wiki. Local and production does not work. With  older branches - for example 953a345 i can at least make the local running - but when i try to setup a superuser it breaks and says it can not create any hashes because of a missing lib - which is actually installed. Is there anything to do different to get the actual version running?

**Comment by er4z0r** [comment]
I built and installed the latest just yesterday with Docker on an Arch Linux system. Have you checked that you did properly copy the .envs (there is a mistake in the wiki)?

**Comment by fuckup1337** [comment]
yea i copied just the whole folder

**Comment by er4z0r** [comment]
Yes but did you do it recursively so as described in #49 ? Have you re-done the whole build-process (after removing the docker containers, if that is an option for you)

**Comment by fuckup1337** [comment]
yea ive done it recursively. Just on it :)

**Comment by fuckup1337** [comment]
worked now at least the local one - seems like i had some container problems. Will try prod now. Thanks !

**Comment by er4z0r** [comment]
Have a look at the developer documentation. There are some useful things such as [log access](https://ghostwriter.wiki/development/modifying-code#troubleshooting)

**Comment by fuckup1337** [comment]
hmm in prod i had the same issue as before alway getting 502 Bad Gateway - for some reason the prod django container restarts every few seconds will check log access if i can see something there. Do you have it running in local or in prod ?

**Comment by fuckup1337** [comment]
fixed the restart of the container by manage.py migrate but still receiving the 502 :/

**Comment by fuckup1337** [comment]
after rebuild the whole thingy it worked. jeez what a ride :D 
thanks again!

**Comment by er4z0r** [comment]
LOL. Now it is me who is not able to restart. Just saw @chrismaddalena  had mered some PRs and wanted check it out.
Now my django containers does not seem to start anymore

**Comment by fuckup1337** [comment]
try docker-compose -f production.yml run --rm django poython manage migrate

then it will say u need to do makemigrations and again migrate - did that but idk if it changes something because giving access denied error

**Comment by fuckup1337** [comment]
then after that do docker-compose -f production.yml down --rmi all 
and once thats done do docker-compose -f production.yml up -d

**Comment by fuckup1337** [comment]
For those who struggle with the same stuff here is the way i made it work (Ubunutu 18.04): 
sudo apt update
sudo apt install docker-compose
sudo usermod -aG docker $USER
sudo reboot

git clone https://github.com/GhostManager/Ghostwriter
cd Ghostwriter
cp -r .envs_template .envs
Change .envs/.production/.django to your needs
Not forget to set DJANGO_ALLOWED_HOSTS to * or whatever u need
Set DJANGO_SECRET_KEY
And what else you need
Change in .envs/.production/.postgres the username and password
apt install certbot
certbot certonly --standalone --preferred-challenge http -d DOMAIN
sudo cp /etc/letsencrypt/live/DOMAIN/fullchain.pem ssl/ghostwriter.crt
sudo cp /etc/letsencrypt/live/DOMAIN/ghostwriter.key
cd ssl
openssl dhparam -out dhparam.pem 4096
cd ..
docker-compose -f production.yml stop; docker-compose -f production.yml rm -f; docker-compose -f production.yml build; docker-compose -f production.yml up -d
docker-compose -f production.yml run --rm django /seed_data
docker-compose -f production.yml run --rm django python manage.py migrate
docker-compose -f production.yml run --rm django python manage.py makemigration
docker-compose -f production.yml run --rm django python manage.py migrate
docker-compose -f production.yml down --rmi all
docker-compose -f production.yml up -d

# not sure if these things are needed because giving access denied error for makemigration but i ran it anyway
docker-compose -f production.yml run --rm django python manage.py makemigration
docker-compose -f production.yml run --rm django python manage.py migrate

Tested this twice worked both times.
