### ISSUE TITLE
Missing: oplog.cna

### ISSUE THREAD

**Issue by dru1d-foofus** [GhostManager/Ghostwriter#97]
Hey, folks!

I was very stoked about the added oplog functionality. I read in the documentation that a server-side opglog.cna aggressor script was also released, but I cannot find it anywhere! Are there any plans to release this anytime soon?

**Comment by chrismaddalena** [comment]
Hey @dru1d-foofus! I missed this issue, but this came up in the Slack channel. We'll get this in the documentation soon, but @hotnops made a gist in the interim:

https://gist.github.com/hotnops/e19a42a792950f4ef996d75a6e1bae35

I'll leave this open so others can find it.

**Comment by dru1d-foofus** [comment]
Thanks, @chrismaddalena! Don't worry about it; you guys are great and I appreciate the hard work you folks put into your public releases.

**Comment by chrismaddalena** [comment]
Update for close: This is now in the documentation on ghostwriter.wiki.
